// Generated by @flighthq/tool-compiler from @flighthq/bitmapfont/packages/bitmapfont/src/bitmapFontFromGlyphAtlas.ts#BitmapFontFromGlyphAtlas at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <memory>
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/texture_atlas.hpp>

#include <flight/types/glyph_source.hpp>

#include <flight/types/create_texture_options.hpp>

#include <flight/types/bitmap_font.hpp>

#include <flight/bitmapfont/bitmap_font.hpp>

// Override: forward-declare refused functions so callers compile.
// create_texture was refused (cpp-typescript-utility-unexpanded:Extract).
// create_texture_atlas was refused (cpp-partial-shape-unresolvable).
namespace flight::texture {
  flight::Ref<flight::types::Texture2D> create_texture(flight::types::CreateTextureOptions opts);
}

namespace flight::bitmapfont {

using flight::types::BitmapFontData;
using flight::types::BitmapFontGlyphData;
using flight::types::CreateTextureOptions;
using flight::types::GlyphAtlas;
using flight::types::GlyphAtlasRuntime;
using flight::types::GlyphMetrics;
using flight::types::TextureAtlas;

using flight::types::BitmapFont;

inline flight::Ref<BitmapFont> create_bitmap_font_from_glyph_atlas(flight::Ref<GlyphAtlas> atlas) {
  flight::Ref<GlyphAtlasRuntime> runtime = atlas->runtime;
  flight::Array<flight::Ref<BitmapFontGlyphData>> glyphs = flight::Array<flight::Ref<BitmapFontGlyphData>>{};
  for (auto array_pattern_value : runtime->entries) {
    const double codepoint = std::get<0>(array_pattern_value);
    auto entry = std::get<1>(array_pattern_value);
    glyphs.push(flight::make_ref<BitmapFontGlyphData>(BitmapFontGlyphData{.advance = entry->advance, .bearing_x = entry->bearing_x, .bearing_y = entry->bearing_y, .codepoint = codepoint, .height = entry->height, .page = 0.0, .width = entry->width, .x = entry->x, .y = entry->y}));
  }
  // Override: the emitter wrote create_texture_atlas({.texture = create_texture(make_ref<CreateTextureOptions>(CreateTextureOptions{.source = runtime->bitmap}))})
  // which has three defects: (1) CreateTextureOptions is a variant, not an aggregate, so designated
  // initializers cannot be used on it; (2) create_texture_atlas is refused (Partial<T>); (3)
  // create_texture is refused (Extract utility). Fixed by constructing the variant alternative
  // explicitly, inlining the TextureAtlas construction, and qualifying create_texture.
  flight::Ref<TextureAtlas> page = flight::make_ref<TextureAtlas>(TextureAtlas{
      .image_height = 0.0,
      .image_width = 0.0,
      .regions = flight::Array<flight::Ref<flight::types::TextureAtlasRegion>>{},
      .scale = 1.0,
      .texture = std::optional<flight::Ref<flight::types::Texture2D>>{
          flight::texture::create_texture(
              CreateTextureOptions{
                  std::in_place_type<flight::Ref<flight::types::flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_source_dimension_resource_56b24da6433b9dfa>>,
                  flight::make_ref<flight::types::flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_source_dimension_resource_56b24da6433b9dfa>(
                      flight::types::flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_source_dimension_resource_56b24da6433b9dfa{
                          .source = std::variant<flight::Ref<flight::types::TextureSource>, flight::Null, flight::Undefined>{
                              std::in_place_type<flight::Ref<flight::types::TextureSource>>,
                              std::reinterpret_pointer_cast<flight::types::TextureSource>(runtime->bitmap)
                          }
                      }
                  )
              }
          )
      }
  });
  return create_bitmap_font(flight::make_ref<BitmapFontData>(BitmapFontData{.glyphs = glyphs, .metrics = flight::make_ref<GlyphMetrics>(*runtime->metrics), .pages = flight::Array{page}}));
}

} // namespace flight::bitmapfont
