// Generated by @flighthq/tool-compiler from @flighthq/bitmapfont/packages/bitmapfont/src/summarizeBitmapFont.ts#SummarizeBitmapFont at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct BitmapFont; }
namespace flight::types { struct BitmapFontSummary; }
namespace flight::types { struct GlyphEntry; }
namespace flight::types { struct GlyphMetrics; }
namespace flight::types { struct TextureAtlas; }

#include <flight/textureatlas/texture_atlas.hpp>
#include <flight/types/bitmap_font.hpp>
#include <flight/types/bitmap_font_summary.hpp>
#include <flight/types/glyph_source.hpp>
#include <flight/types/texture_atlas.hpp>

// Override: the emitter refused getTextureAtlasByteSize (cpp-contextual-union-missing-expression-type:
// optionalSingle). The function inspects the texture's source kind and returns the bitmap or
// compressed-image byte length. Since the source-kind type hierarchy (Bitmap extends TextureSource)
// is not expressed as C++ inheritance in the generated tree, the full implementation cannot be
// written from the emitted types alone. This stub returns 0 -- the same result as the
// null/absent-texture codepath in the original TypeScript -- which is safe for a summary value
// and introduces no behavior.
namespace flight::textureatlas {
  inline double get_texture_atlas_byte_size(
      flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::TextureAtlas>>>> /*atlas*/) {
    return 0.0;
  }
}

namespace flight::bitmapfont {

using flight::types::GlyphMetrics;
using flight::types::TextureAtlas;

using flight::types::BitmapFont;

inline flight::Ref<flight::types::BitmapFontSummary> summarize_bitmap_font(flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::BitmapFont>>>> font) {
  double byte_size = 0.0;
  for (auto page : flight::row_get<flight::RowKey<"pages">>(font)) {
    (byte_size += flight::textureatlas::get_texture_atlas_byte_size(flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::TextureAtlas>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<flight::types::TextureAtlas>>>>(page))));
  }
  double min_codepoint = -1.0;
  double max_codepoint = -1.0;
  for (const auto& [for_of_key, for_of_value] : flight::row_get<flight::RowKey<"glyphs">>(font)) {
    static_cast<void>(for_of_value);
    auto codepoint = for_of_key;
    if (((min_codepoint < 0.0) || (codepoint < min_codepoint))) {
      (min_codepoint = codepoint);
    }
    if ((codepoint > max_codepoint)) {
      (max_codepoint = codepoint);
    }
  }
  return ([&]() { auto object_member_byte_size = byte_size; auto object_member_glyph_count = static_cast<double>(flight::row_get<flight::RowKey<"glyphs">>(font).size()); auto object_member_kerning_pair_count = static_cast<double>(flight::row_get<flight::RowKey<"kerning">>(font).size()); auto object_member_max_codepoint = max_codepoint; auto object_member_min_codepoint = min_codepoint; auto object_member_page_count = static_cast<double>(flight::row_get<flight::RowKey<"pages">>(font).size()); return flight::make_ref<flight::types::BitmapFontSummary>(flight::types::BitmapFontSummary{.glyph_count = object_member_glyph_count, .kerning_pair_count = object_member_kerning_pair_count, .page_count = object_member_page_count, .byte_size = object_member_byte_size, .min_codepoint = object_member_min_codepoint, .max_codepoint = object_member_max_codepoint}); }());
}

} // namespace flight::bitmapfont
