// Generated by @flighthq/tool-compiler from @flighthq/scene2d/packages/scene2d/src/displayObjectAnimation.ts#DisplayObjectAnimation at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/any.hpp>
#include <flight/structural_ref.hpp>
#include <optional>
#include <stdexcept>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct AnimationChannel; }
namespace flight::types { struct AnimationClip; }
namespace flight::types { struct AnimationClipEvent; }
namespace flight::types { struct AnimationTrack; }
namespace flight::types { struct Node2DAnimationTarget; }
namespace flight::types { struct Node2DTraits; }
namespace flight::types { template <typename Traits> struct Node; }

#include <flight/animation/animation_track.hpp>
#include <flight/node/revision.hpp>
#include <flight/types/animation_channel.hpp>
#include <flight/types/animation_clip.hpp>
#include <flight/types/animation_clip_event.hpp>
#include <flight/types/animation_track.hpp>
#include <flight/types/node.hpp>
#include <flight/types/node2_d.hpp>
#include <flight/types/node2_danimation_path.hpp>
#include <flight/types/node2_danimation_target.hpp>

namespace flight::scene2d {

using flight::types::AnimationTrack;
using flight::types::Node;
using flight::types::Node2DTraits;

inline flight::Array<double> scratch = flight::Array<double>{0.0, 0.0, 0.0, 0.0};

inline std::shared_ptr<flight::types::NodeRuntime<flight::Ref<Node2DTraits>>>
get_animation_node_runtime(flight::types::Node2D node) {
  using NodeOwner = Node<flight::Ref<Node2DTraits>>;
  auto node_row = flight::structural_ref_cast<
      flight::StructuralRef<flight::RowReadonly<flight::RowOf<std::shared_ptr<NodeOwner>>>>>(node);
  auto runtime = flight::structural_ref_cast<std::shared_ptr<NodeOwner>>(node_row)->entity_runtime_key;
  if (!runtime.has_value()) {
    throw flight::Error(flight::String("Cannot invalidate an animated Node2D without its runtime"));
  }
  return runtime.value();
}

inline void invalidate_animation_node_appearance(flight::types::Node2D node) {
  auto runtime = get_animation_node_runtime(node);
  runtime->appearance_id = flight::unsigned_right_shift(runtime->appearance_id + 1.0, 0.0);
}

inline void invalidate_animation_node_transform(flight::types::Node2D node) {
  auto runtime = get_animation_node_runtime(node);
  runtime->local_transform_id = flight::unsigned_right_shift(runtime->local_transform_id + 1.0, 0.0);
}

inline void apply_animation_clip_to_node2_d(flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::AnimationClip>>>> clip, double time) {
  for (auto channel : flight::row_get<flight::RowKey<"channels">>(clip)) {
    auto target = ([&]() -> std::optional<flight::Ref<flight::types::Node2DAnimationTarget>> { const auto& erased_value = channel->target_ref; if (static_cast<bool>(erased_value.object_if<flight::types::Node2DAnimationTarget>())) return std::optional<flight::Ref<flight::types::Node2DAnimationTarget>>{erased_value.object_if<flight::types::Node2DAnimationTarget>()}; if (erased_value.is_nullish()) return std::nullopt; throw std::logic_error("erased value holds no alternative this union represents"); }());
    if (((!target.has_value() || (flight::String("object") != flight::String("object"))) || false)) {
      continue;
    }
    flight::animation::sample_animation_track(std::variant<flight::Array<double>, flight::Float32Array>{std::in_place_type<flight::Array<double>>, scratch}, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::AnimationTrack>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<flight::types::AnimationTrack>>>>(channel->track)), time);
    flight::types::Node2D node = target.value()->node;
    {
      auto switch_value = target.value()->path;
      if (switch_value == flight::String("Alpha")) {
        flight::row_set<flight::RowKey<"alpha">>(node, scratch.element(0.0));
        invalidate_animation_node_appearance(node);
      }
      else if (switch_value == flight::String("Pivot")) {
        flight::row_set<flight::RowKey<"pivotX">>(node, scratch.element(0.0));
        flight::row_set<flight::RowKey<"pivotY">>(node, scratch.element(1.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("PivotX")) {
        flight::row_set<flight::RowKey<"pivotX">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("PivotY")) {
        flight::row_set<flight::RowKey<"pivotY">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Position")) {
        flight::row_set<flight::RowKey<"x">>(node, scratch.element(0.0));
        flight::row_set<flight::RowKey<"y">>(node, scratch.element(1.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Rotation")) {
        flight::row_set<flight::RowKey<"rotation">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Scale")) {
        flight::row_set<flight::RowKey<"scaleX">>(node, scratch.element(0.0));
        flight::row_set<flight::RowKey<"scaleY">>(node, scratch.element(1.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("ScaleX")) {
        flight::row_set<flight::RowKey<"scaleX">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("ScaleY")) {
        flight::row_set<flight::RowKey<"scaleY">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Skew")) {
        flight::row_set<flight::RowKey<"skewX">>(node, scratch.element(0.0));
        flight::row_set<flight::RowKey<"skewY">>(node, scratch.element(1.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("SkewX")) {
        flight::row_set<flight::RowKey<"skewX">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("SkewY")) {
        flight::row_set<flight::RowKey<"skewY">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Visible")) {
        flight::row_set<flight::RowKey<"visible">>(node, (scratch.element(0.0) >= 0.5));
        invalidate_animation_node_appearance(node);
      }
      else if (switch_value == flight::String("X")) {
        flight::row_set<flight::RowKey<"x">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
      else if (switch_value == flight::String("Y")) {
        flight::row_set<flight::RowKey<"y">>(node, scratch.element(0.0));
        invalidate_animation_node_transform(node);
      }
    }
  }
}

} // namespace flight::scene2d
