// Generated by @flighthq/tool-compiler from @flighthq/textbidi/packages/textbidi/src/resolveBidiLevels.ts#ResolveBidiLevels at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the emitter refused four declarations after losing the represented BidiClass union and
// rejecting the source's fully-populated `new Array(length)` temporaries as potentially sparse.
// This override supplies the complete module while preserving the generated carriers.

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <optional>

#include <flight/runtime.hpp>
#include <flight/structural_ref.hpp>
#include <flight/types/bidi.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2",
              "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::textbidi {

using flight::types::BidiClass;
using flight::types::BidiClassKernel;
using flight::types::BidiDirection;

inline double compute_paragraph_level(flight::Array<BidiClass> types, double start, double end) {
  double isolate_depth = 0.0;
  for (double index = start; index < end; index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("LRI") || type == flight::String("RLI") ||
        type == flight::String("FSI")) {
      isolate_depth += 1.0;
    } else if (type == flight::String("PDI")) {
      if (isolate_depth > 0.0) isolate_depth -= 1.0;
    } else if (isolate_depth == 0.0) {
      if (type == flight::String("L")) return 0.0;
      if (type == flight::String("R") || type == flight::String("AL")) return 1.0;
    }
  }
  return 0.0;
}

inline void pair_isolates(flight::Array<BidiClass> types,
                          flight::Int32Array matching_pdi,
                          flight::Int32Array matching_initiator) {
  flight::Array<double> stack;
  for (double index = 0.0; index < static_cast<double>(types.size()); index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("LRI") || type == flight::String("RLI") ||
        type == flight::String("FSI")) {
      stack.push(index);
    } else if (type == flight::String("PDI") && !stack.empty()) {
      const double initiator = stack.pop().value();
      matching_pdi.set_index(initiator, index);
      matching_initiator.set_index(index, initiator);
    }
  }
}

inline std::optional<BidiClass> strong_bidi_direction(BidiClass type) {
  if (type == flight::String("L")) return flight::String("L");
  if (type == flight::String("R") || type == flight::String("EN") ||
      type == flight::String("AN")) {
    return flight::String("R");
  }
  return std::nullopt;
}

inline bool is_neutral_or_isolate(BidiClass type) {
  return type == flight::String("B") || type == flight::String("S") ||
         type == flight::String("WS") || type == flight::String("ON") ||
         type == flight::String("FSI") || type == flight::String("LRI") ||
         type == flight::String("RLI") || type == flight::String("PDI");
}

inline bool is_reset_type(BidiClass type) {
  return type == flight::String("WS") || type == flight::String("LRI") ||
         type == flight::String("RLI") || type == flight::String("FSI") ||
         type == flight::String("PDI") || type == flight::String("LRE") ||
         type == flight::String("RLE") || type == flight::String("LRO") ||
         type == flight::String("RLO") || type == flight::String("PDF") ||
         type == flight::String("BN");
}

inline void apply_line_reset(flight::Array<BidiClass> original,
                             flight::Array<double> level_array,
                             double paragraph_level) {
  const double length = static_cast<double>(original.size());
  for (double index = 0.0; index < length; index += 1.0) {
    const auto type = original.element(index);
    if (type != flight::String("B") && type != flight::String("S")) continue;
    level_array.element(index) = paragraph_level;
    for (double previous = index - 1.0;
         previous >= 0.0 && is_reset_type(original.element(previous)); previous -= 1.0) {
      level_array.element(previous) = paragraph_level;
    }
  }
  for (double index = length - 1.0;
       index >= 0.0 && is_reset_type(original.element(index)); index -= 1.0) {
    level_array.element(index) = paragraph_level;
  }
}

inline flight::String neutral_direction(BidiClass type) {
  return type == flight::String("L") ? flight::String("L") : flight::String("R");
}

inline double next_even(double level) {
  return flight::bitwise_and(level + 2.0, flight::bitwise_not(1.0));
}

inline double next_odd(double level) { return flight::bitwise_or(level + 1.0, 1.0); }

inline void apply_explicit_levels(flight::Array<BidiClass> original,
                                  flight::Array<BidiClass> working,
                                  flight::Array<double> level_array,
                                  flight::Int32Array matching_pdi,
                                  double paragraph_level) {
  constexpr double max_depth = 125.0;
  flight::Array<double> stack_level{paragraph_level};
  flight::Array<std::optional<BidiClass>> stack_override{std::optional<BidiClass>{}};
  flight::Array<bool> stack_isolate{false};
  double overflow_isolate = 0.0;
  double overflow_embedding = 0.0;
  double valid_isolate = 0.0;

  for (double index = 0.0; index < static_cast<double>(original.size()); index += 1.0) {
    const auto type = original.element(index);
    const double top = static_cast<double>(stack_level.size()) - 1.0;

    if (type == flight::String("RLE") || type == flight::String("LRE") ||
        type == flight::String("RLO") || type == flight::String("LRO")) {
      level_array.element(index) = stack_level.element(top);
      working.element(index) = flight::String("BN");
      const double new_level =
          type == flight::String("RLE") || type == flight::String("RLO")
              ? next_odd(stack_level.element(top))
              : next_even(stack_level.element(top));
      if (new_level <= max_depth && overflow_isolate == 0.0 && overflow_embedding == 0.0) {
        stack_level.push(new_level);
        stack_override.push(type == flight::String("RLO")
                                ? std::optional<BidiClass>{flight::String("R")}
                                : type == flight::String("LRO")
                                      ? std::optional<BidiClass>{flight::String("L")}
                                      : std::nullopt);
        stack_isolate.push(false);
      } else if (overflow_isolate == 0.0) {
        overflow_embedding += 1.0;
      }
      continue;
    }

    if (type == flight::String("RLI") || type == flight::String("LRI") ||
        type == flight::String("FSI")) {
      level_array.element(index) = stack_level.element(top);
      const auto active_override = stack_override.element(top);
      if (active_override.has_value()) working.element(index) = active_override.value();
      bool as_rtl = type == flight::String("RLI");
      if (type == flight::String("FSI")) {
        as_rtl = compute_paragraph_level(original, index + 1.0,
                                         matching_pdi.get_index(index)) == 1.0;
      }
      const double new_level = as_rtl ? next_odd(stack_level.element(top))
                                      : next_even(stack_level.element(top));
      if (new_level <= max_depth && overflow_isolate == 0.0 && overflow_embedding == 0.0) {
        valid_isolate += 1.0;
        stack_level.push(new_level);
        stack_override.push(std::nullopt);
        stack_isolate.push(true);
      } else {
        overflow_isolate += 1.0;
      }
      continue;
    }

    if (type == flight::String("PDI")) {
      if (overflow_isolate > 0.0) {
        overflow_isolate -= 1.0;
      } else if (valid_isolate > 0.0) {
        overflow_embedding = 0.0;
        while (!stack_isolate.element(static_cast<double>(stack_level.size()) - 1.0)) {
          static_cast<void>(stack_level.pop());
          static_cast<void>(stack_override.pop());
          static_cast<void>(stack_isolate.pop());
        }
        static_cast<void>(stack_level.pop());
        static_cast<void>(stack_override.pop());
        static_cast<void>(stack_isolate.pop());
        valid_isolate -= 1.0;
      }
      const double new_top = static_cast<double>(stack_level.size()) - 1.0;
      level_array.element(index) = stack_level.element(new_top);
      const auto active_override = stack_override.element(new_top);
      if (active_override.has_value()) working.element(index) = active_override.value();
      continue;
    }

    if (type == flight::String("PDF")) {
      if (overflow_isolate > 0.0) {
        // Isolate overflow shields embeddings.
      } else if (overflow_embedding > 0.0) {
        overflow_embedding -= 1.0;
      } else if (!stack_isolate.element(top) && stack_level.size() >= 2) {
        static_cast<void>(stack_level.pop());
        static_cast<void>(stack_override.pop());
        static_cast<void>(stack_isolate.pop());
      }
      level_array.element(index) =
          stack_level.element(static_cast<double>(stack_level.size()) - 1.0);
      working.element(index) = flight::String("BN");
      continue;
    }

    if (type == flight::String("B")) {
      stack_level.resize(1.0);
      stack_override.resize(1.0);
      stack_isolate.resize(1.0);
      overflow_isolate = 0.0;
      overflow_embedding = 0.0;
      valid_isolate = 0.0;
      level_array.element(index) = paragraph_level;
      continue;
    }

    level_array.element(index) = stack_level.element(top);
    if (type != flight::String("BN")) {
      const auto active_override = stack_override.element(top);
      if (active_override.has_value()) working.element(index) = active_override.value();
    }
  }
}

inline flight::Array<double> bidi_bracket_pairs = flight::Array<double>{
    40.0, 41.0, 91.0, 93.0, 123.0, 125.0, 3898.0, 3899.0, 3900.0, 3901.0,
    5787.0, 5788.0, 8261.0, 8262.0, 8317.0, 8318.0, 8333.0, 8334.0, 8968.0,
    8969.0, 8970.0, 8971.0, 9001.0, 9002.0, 10088.0, 10089.0, 10090.0,
    10091.0, 10092.0, 10093.0, 10094.0, 10095.0, 10096.0, 10097.0, 10098.0,
    10099.0, 10100.0, 10101.0, 10181.0, 10182.0, 10214.0, 10215.0, 10216.0,
    10217.0, 10218.0, 10219.0, 10220.0, 10221.0, 10222.0, 10223.0, 10627.0,
    10628.0, 10629.0, 10630.0, 10631.0, 10632.0, 10633.0, 10634.0, 10635.0,
    10636.0, 10637.0, 10640.0, 10638.0, 10639.0, 10641.0, 10642.0, 10643.0,
    10644.0, 10645.0, 10646.0, 10647.0, 10648.0, 10712.0, 10713.0, 10714.0,
    10715.0, 10748.0, 10749.0, 11810.0, 11811.0, 11812.0, 11813.0, 11814.0,
    11815.0, 11816.0, 11817.0, 12296.0, 12297.0, 12298.0, 12299.0, 12300.0,
    12301.0, 12302.0, 12303.0, 12304.0, 12305.0, 12308.0, 12309.0, 12310.0,
    12311.0, 12312.0, 12313.0, 12314.0, 12315.0, 65113.0, 65114.0, 65115.0,
    65116.0, 65117.0, 65118.0, 65288.0, 65289.0, 65339.0, 65341.0, 65371.0,
    65373.0, 65375.0, 65376.0, 65378.0, 65379.0};

inline double get_bidi_bracket_closing(double codepoint) {
  for (double index = 0.0; index < static_cast<double>(bidi_bracket_pairs.size());
       index += 2.0) {
    if (bidi_bracket_pairs.element(index) == codepoint) {
      return bidi_bracket_pairs.element(index + 1.0);
    }
  }
  return -1.0;
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_CLOSE_POSITION_375BFC973604D8E3
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_CLOSE_POSITION_375BFC973604D8E3
struct close_position_375bfc973604d8e3 : public flight::ReferenceEnabled {
  double close;
  double position;
};
#endif

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_CLOSE_OPEN_81643C227079C726
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_CLOSE_OPEN_81643C227079C726
struct close_open_81643c227079c726 : public flight::ReferenceEnabled {
  double close;
  double open;
};
#endif

inline void resolve_paired_brackets(flight::Array<double> codepoints,
                                    flight::Array<double> sequence,
                                    flight::Array<BidiClass> types,
                                    BidiClass embedding_direction,
                                    BidiClass sos) {
  flight::Array<flight::Ref<close_position_375bfc973604d8e3>> stack;
  flight::Array<flight::Ref<close_open_81643c227079c726>> pairs;

  for (double index = 0.0; index < static_cast<double>(sequence.size()); index += 1.0) {
    if (types.element(index) != flight::String("ON")) continue;
    const double codepoint = codepoints.element(sequence.element(index));
    const double closing = get_bidi_bracket_closing(codepoint);
    if (closing != -1.0) {
      if (stack.size() == 63) break;
      stack.push(flight::make_ref<close_position_375bfc973604d8e3>(
          close_position_375bfc973604d8e3{.close = closing, .position = index}));
      continue;
    }
    for (double candidate = static_cast<double>(stack.size()) - 1.0; candidate >= 0.0;
         candidate -= 1.0) {
      if (stack.element(candidate)->close != codepoint) continue;
      pairs.push(flight::make_ref<close_open_81643c227079c726>(
          close_open_81643c227079c726{.close = index,
                                      .open = stack.element(candidate)->position}));
      stack.resize(candidate);
      break;
    }
  }

  pairs.sort([](const auto& left, const auto& right) { return left->open - right->open; });
  const BidiClass opposite_direction = embedding_direction == flight::String("L")
                                           ? flight::String("R")
                                           : flight::String("L");
  for (const auto& pair : pairs) {
    bool contains_embedding_direction = false;
    bool contains_opposite_direction = false;
    for (double index = pair->open + 1.0; index < pair->close; index += 1.0) {
      const auto direction = strong_bidi_direction(types.element(index));
      if (direction == embedding_direction) {
        contains_embedding_direction = true;
        break;
      }
      if (direction == opposite_direction) contains_opposite_direction = true;
    }

    std::optional<BidiClass> resolved;
    if (contains_embedding_direction) {
      resolved = embedding_direction;
    } else if (contains_opposite_direction) {
      BidiClass preceding_direction = strong_bidi_direction(sos).value();
      for (double index = pair->open - 1.0; index >= 0.0; index -= 1.0) {
        const auto direction = strong_bidi_direction(types.element(index));
        if (!direction.has_value()) continue;
        preceding_direction = direction.value();
        break;
      }
      resolved = preceding_direction == opposite_direction ? opposite_direction : embedding_direction;
    }
    if (resolved.has_value()) {
      types.element(pair->open) = resolved.value();
      types.element(pair->close) = resolved.value();
    }
  }
}

inline void resolve_sequence(flight::Array<double> codepoints,
                             flight::Array<BidiClass> original,
                             flight::Array<BidiClass> working,
                             flight::Array<double> level_array,
                             flight::Array<double> kept,
                             flight::Array<double> sequence,
                             double kept_start,
                             double kept_end,
                             flight::Int32Array matching_pdi,
                             double paragraph_level) {
  const double sequence_level = level_array.element(sequence.element(0.0));
  const double previous_level = kept_start > 0.0
                                    ? level_array.element(kept.element(kept_start - 1.0))
                                    : paragraph_level;
  const BidiClass sos = std::fmod(flight::maximum(sequence_level, previous_level), 2.0) == 1.0
                            ? flight::String("R")
                            : flight::String("L");
  const double last_index = sequence.element(static_cast<double>(sequence.size()) - 1.0);
  const auto last_type = original.element(last_index);
  const bool ends_unmatched_isolate =
      (last_type == flight::String("LRI") || last_type == flight::String("RLI") ||
       last_type == flight::String("FSI")) &&
      matching_pdi.get_index(last_index) >= static_cast<double>(original.size());
  const double next_level = ends_unmatched_isolate
                                ? paragraph_level
                                : kept_end < static_cast<double>(kept.size())
                                      ? level_array.element(kept.element(kept_end))
                                      : paragraph_level;
  const BidiClass eos = std::fmod(flight::maximum(sequence_level, next_level), 2.0) == 1.0
                            ? flight::String("R")
                            : flight::String("L");

  const double length = static_cast<double>(sequence.size());
  flight::Array<BidiClass> types(length);
  for (double index = 0.0; index < length; index += 1.0) {
    types.element(index) = working.element(sequence.element(index));
  }

  BidiClass previous = sos;
  for (double index = 0.0; index < length; index += 1.0) {
    if (types.element(index) == flight::String("NSM")) {
      types.element(index) = previous == flight::String("LRI") ||
                                     previous == flight::String("RLI") ||
                                     previous == flight::String("FSI") ||
                                     previous == flight::String("PDI")
                                 ? flight::String("ON")
                                 : previous;
    }
    previous = types.element(index);
  }

  BidiClass strong = sos;
  for (double index = 0.0; index < length; index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("L") || type == flight::String("R") ||
        type == flight::String("AL")) {
      strong = type;
    } else if (type == flight::String("EN") && strong == flight::String("AL")) {
      types.element(index) = flight::String("AN");
    }
  }
  for (double index = 0.0; index < length; index += 1.0) {
    if (types.element(index) == flight::String("AL")) {
      types.element(index) = flight::String("R");
    }
  }

  for (double index = 1.0; index < length - 1.0; index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("ES") && types.element(index - 1.0) == flight::String("EN") &&
        types.element(index + 1.0) == flight::String("EN")) {
      types.element(index) = flight::String("EN");
    } else if (type == flight::String("CS")) {
      if (types.element(index - 1.0) == flight::String("EN") &&
          types.element(index + 1.0) == flight::String("EN")) {
        types.element(index) = flight::String("EN");
      } else if (types.element(index - 1.0) == flight::String("AN") &&
                 types.element(index + 1.0) == flight::String("AN")) {
        types.element(index) = flight::String("AN");
      }
    }
  }

  for (double index = 0.0; index < length;) {
    if (types.element(index) != flight::String("ET")) {
      index += 1.0;
      continue;
    }
    double end = index;
    while (end < length && types.element(end) == flight::String("ET")) end += 1.0;
    const auto before = index > 0.0 ? types.element(index - 1.0) : sos;
    const auto after = end < length ? types.element(end) : eos;
    if (before == flight::String("EN") || after == flight::String("EN")) {
      for (double member = index; member < end; member += 1.0) {
        types.element(member) = flight::String("EN");
      }
    }
    index = end;
  }

  for (double index = 0.0; index < length; index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("ES") || type == flight::String("ET") ||
        type == flight::String("CS")) {
      types.element(index) = flight::String("ON");
    }
  }

  strong = sos;
  for (double index = 0.0; index < length; index += 1.0) {
    const auto type = types.element(index);
    if (type == flight::String("L") || type == flight::String("R")) {
      strong = type;
    } else if (type == flight::String("EN") && strong == flight::String("L")) {
      types.element(index) = flight::String("L");
    }
  }

  const BidiClass embedding_direction = std::fmod(sequence_level, 2.0) == 1.0
                                            ? flight::String("R")
                                            : flight::String("L");
  resolve_paired_brackets(codepoints, sequence, types, embedding_direction, sos);

  for (double index = 0.0; index < length;) {
    if (!is_neutral_or_isolate(types.element(index))) {
      index += 1.0;
      continue;
    }
    double end = index;
    while (end < length && is_neutral_or_isolate(types.element(end))) end += 1.0;
    const BidiClass before = index > 0.0 ? neutral_direction(types.element(index - 1.0)) : sos;
    const BidiClass after = end < length ? neutral_direction(types.element(end)) : eos;
    const BidiClass resolved = before == after ? before : embedding_direction;
    for (double member = index; member < end; member += 1.0) {
      types.element(member) = resolved;
    }
    index = end;
  }

  const bool even = std::fmod(sequence_level, 2.0) == 0.0;
  for (double index = 0.0; index < length; index += 1.0) {
    const auto type = types.element(index);
    double level = sequence_level;
    if (even) {
      if (type == flight::String("R")) {
        level = sequence_level + 1.0;
      } else if (type == flight::String("AN") || type == flight::String("EN")) {
        level = sequence_level + 2.0;
      }
    } else if (type == flight::String("L") || type == flight::String("EN") ||
               type == flight::String("AN")) {
      level = sequence_level + 1.0;
    }
    level_array.element(sequence.element(index)) = level;
  }
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_INDICES_KEPT_START_KEPT_END_3EC40B0C934BDEF8
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_TEXTBIDI_INDICES_KEPT_START_KEPT_END_3EC40B0C934BDEF8
struct indices_kept_start_kept_end_3ec40b0c934bdef8 : public flight::ReferenceEnabled {
  flight::Array<double> indices;
  double kept_start;
  double kept_end;
};
#endif

inline void resolve_isolating_run_sequences(flight::Array<double> codepoints,
                                            flight::Array<BidiClass> original,
                                            flight::Array<BidiClass> working,
                                            flight::Array<double> level_array,
                                            flight::Int32Array matching_pdi,
                                            flight::Int32Array matching_initiator,
                                            double paragraph_level) {
  const double length = static_cast<double>(original.size());
  flight::Array<double> kept;
  for (double index = 0.0; index < length; index += 1.0) {
    if (working.element(index) != flight::String("BN")) kept.push(index);
  }
  if (kept.empty()) return;

  flight::Array<flight::Ref<indices_kept_start_kept_end_3ec40b0c934bdef8>> runs;
  double run_start = 0.0;
  for (double index = 1.0; index <= static_cast<double>(kept.size()); index += 1.0) {
    if (index != static_cast<double>(kept.size()) &&
        level_array.element(kept.element(index)) ==
            level_array.element(kept.element(run_start))) {
      continue;
    }
    flight::Array<double> indices;
    for (double member = run_start; member < index; member += 1.0) {
      indices.push(kept.element(member));
    }
    runs.push(flight::make_ref<indices_kept_start_kept_end_3ec40b0c934bdef8>(
        indices_kept_start_kept_end_3ec40b0c934bdef8{
            .indices = indices, .kept_start = run_start, .kept_end = index}));
    run_start = index;
  }

  flight::Map<double, double> run_by_first;
  for (double index = 0.0; index < static_cast<double>(runs.size()); index += 1.0) {
    run_by_first.set(runs.element(index)->indices.element(0.0), index);
  }

  for (double run_index = 0.0; run_index < static_cast<double>(runs.size());
       run_index += 1.0) {
    const double first_index = runs.element(run_index)->indices.element(0.0);
    if (original.element(first_index) == flight::String("PDI") &&
        matching_initiator.get_index(first_index) != -1.0) {
      continue;
    }

    flight::Array<double> sequence;
    const double kept_start = runs.element(run_index)->kept_start;
    double kept_end = runs.element(run_index)->kept_end;
    double current = run_index;
    for (;;) {
      const auto run = runs.element(current);
      for (const double member : run->indices) sequence.push(member);
      kept_end = run->kept_end;
      const double last_index = run->indices.element(static_cast<double>(run->indices.size()) - 1.0);
      const auto last_type = original.element(last_index);
      if ((last_type == flight::String("LRI") || last_type == flight::String("RLI") ||
           last_type == flight::String("FSI")) &&
          matching_pdi.get_index(last_index) < length) {
        const auto next = run_by_first.get(matching_pdi.get_index(last_index));
        if (!next.has_value()) break;
        current = next.value();
      } else {
        break;
      }
    }

    resolve_sequence(codepoints, original, working, level_array, kept, sequence, kept_start,
                     kept_end, matching_pdi, paragraph_level);
  }
}

// OVERRIDE: every slot in the source's length-constructed arrays is assigned before it is read.
// Dense flight::Array storage can therefore represent the operation without observable holes.
inline flight::Uint8Array resolve_bidi_levels(
    flight::StructuralRef<
        flight::RowReadonly<flight::RowOf<flight::Ref<BidiClassKernel>>>>
        bidi_class_kernel,
    flight::String text,
    BidiDirection base_direction) {
  const double length = static_cast<double>(text.length());
  flight::Uint8Array levels(length);
  if (length == 0.0) return levels;

  flight::Array<double> codepoints(length);
  flight::Array<BidiClass> original(length);
  const auto get_bidi_class =
      flight::row_get<flight::RowKey<"getBidiClass">>(bidi_class_kernel);
  for (double index = 0.0; index < length; index += 1.0) {
    const double codepoint = text.code_point_at(static_cast<std::ptrdiff_t>(index)).value();
    const BidiClass bidi_class = get_bidi_class(codepoint);
    codepoints.element(index) = codepoint;
    original.element(index) = bidi_class;
    if (codepoint > 65535.0) {
      codepoints.element(index + 1.0) = codepoint;
      original.element(index + 1.0) = bidi_class;
      index += 1.0;
    }
  }

  const double paragraph_level =
      base_direction == flight::String("ltr")
          ? 0.0
          : base_direction == flight::String("rtl")
                ? 1.0
                : compute_paragraph_level(original, 0.0, length);
  flight::Int32Array matching_pdi(length);
  matching_pdi.fill(static_cast<std::int32_t>(length));
  flight::Int32Array matching_initiator(length);
  matching_initiator.fill(-1);
  pair_isolates(original, matching_pdi, matching_initiator);

  const auto working = original.slice();
  flight::Array<double> level_array(length);
  apply_explicit_levels(original, working, level_array, matching_pdi, paragraph_level);
  resolve_isolating_run_sequences(codepoints, original, working, level_array, matching_pdi,
                                  matching_initiator, paragraph_level);
  apply_line_reset(original, level_array, paragraph_level);

  for (double index = 0.0; index < length; index += 1.0) {
    levels.set_index(index, level_array.element(index));
  }
  return levels;
}

}  // namespace flight::textbidi
