// Generated by @flighthq/tool-compiler from @flighthq/render-wgpu/packages/render-wgpu/src/wgpuScreenCapture.ts#WgpuScreenCapture at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function acquireWgpuScreenRenderTargetCaptureTexture -- source line 73
//   missing: function encodeWgpuScreenRenderTargetCapture -- source line 93
//   missing: function mapWgpuCaptureBuffer -- source line 132
//   missing: function createBitmapFromWgpuScreenRenderTarget -- source line 15
#include <cmath>
#include <coroutine>
#include <cstdint>
#include <flight/boolean.hpp>
#include <flight/host_sdl/wgpu.hpp>
#include <functional>
#include <optional>
#include <random>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/wgpu_render_target.hpp>

namespace flight::render_wgpu {

using flight::types::WgpuScreenRenderTarget;

inline flight::host_sdl::WgpuTexture acquire_wgpu_screen_render_target_capture_texture(
    flight::Ref<WgpuScreenRenderTarget>) {
  throw flight::Error(flight::String("render-wgpu: capture texture creation is unavailable in this profile"));
}

inline void encode_wgpu_screen_render_target_capture(
    flight::Ref<WgpuScreenRenderTarget>, flight::host_sdl::WgpuCommandEncoder) {
  throw flight::Error(flight::String("render-wgpu: capture encoding is unavailable in this profile"));
}


// NOT GENERATED: function acquireWgpuScreenRenderTargetCaptureTexture -- source line 73
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   function acquireWgpuScreenRenderTargetCaptureTexture(target: WgpuScreenRenderTarget): GPUTexture {
//     const scale = target.antialias ? 2 : 1;
//     const width = Math.max(1, Math.floor(target.width / scale));
//     const height = Math.max(1, Math.floor(target.height / scale));
//     const existing = target.captureTexture;
//     if (existing !== null && existing.width === width && existing.height === height) return existing;
//   
//     existing?.destroy();
//     const texture = target.device.createTexture({
//       size: [width, height, 1],
//       format: target.format,
//       usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_SRC,
//     });
//     target.captureTexture = texture;
//     return texture;
//   }
//   
//   // Encodes the capture-texture → capture-buffer copy into the frame's command encoder, sizing and
//   // reallocating the retained buffer to the surface on demand. No-op unless capture is enabled. Internal:
//   // called by submitWgpuFrame so the copy is queued in the render frame, not a later (dropped) task.
// cpp emission failed for @flighthq/render-wgpu/packages/render-wgpu/src/wgpuScreenCapture.ts: contextual
// optionalSingle construction requires expression type evidence


// NOT GENERATED: function encodeWgpuScreenRenderTargetCapture -- source line 93
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function encodeWgpuScreenRenderTargetCapture(target: WgpuScreenRenderTarget, encoder: GPUCommandEncoder): void {
//     const texture = target.captureTexture;
//     if (!target.captureEnabled || texture === null) return;
//     // The reader owns the buffer while it holds a map. One retained buffer serves both sides, and the
//     // queue may not touch a buffer that is mapped or has a map in flight — so a frame encoded during a
//     // readback both invalidates the copy and stacks more GPU work in front of the map it is waiting on.
//     // Skipping the frame is the handshake: the reader is already taking a snapshot, and the next frame
//     // resumes copying once it lets go.
//     //
//     // Deliberately written as "is it busy" rather than "is it not unmapped": an implementation without
//     // `mapState` reports undefined, and the inverted test would then skip every copy for the whole run
//     // and capture nothing. Unknown state falls through to the copy, which is the pre-existing behaviour.
//     const mapState = target.captureBuffer?.mapState;
//     if (mapState === 'pending' || mapState === 'mapped') return;
//   
//     const width = texture.width;
//     const height = texture.height;
//     // Wgpu requires copyTextureToBuffer rows to be 256-byte aligned; the buffer is padded per row.
//     const bytesPerRow = Math.ceil((width * 4) / 256) * 256;
//   
//     if (target.captureBuffer === null || target.captureWidth !== width || target.captureHeight !== height) {
//       target.captureBuffer?.destroy();
//       target.captureBuffer = target.device.createBuffer({
//         size: bytesPerRow * height,
//         usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
//       });
//       target.captureBytesPerRow = bytesPerRow;
//       target.captureWidth = width;
//       target.captureHeight = height;
//     }
//   
//     encoder.copyTextureToBuffer({ texture }, { buffer: target.captureBuffer, bytesPerRow }, [width, height, 1]);
//   }
//   
//   // Maps the retained capture buffer, giving up by name after `timeoutMs` (0 waits indefinitely).
//   // `mapAsync` carries no timeout and no reject path of its own: on the contended software adapters this
//   // capture path exists for, the promise can simply never settle, and an unbounded await is indistinguishable
//   // from a caller that stopped running. A late resolution after the deadline leaves the buffer mapped, which
//   // is why the timeout is a hard end for this capture and not something to retry against the same buffer.
// cpp emission failed for @flighthq/render-wgpu/packages/render-wgpu/src/wgpuScreenCapture.ts: contextual
// optionalSingle construction requires expression type evidence

inline void enable_wgpu_screen_render_target_capture(flight::Ref<WgpuScreenRenderTarget> target) {
  (target->capture_enabled = true);
  (target->acquire_capture_texture = acquire_wgpu_screen_render_target_capture_texture);
  (target->encode_capture = encode_wgpu_screen_render_target_capture);
}


// NOT GENERATED: function mapWgpuCaptureBuffer -- source line 132
// refusal: cpp-shared-mutable-capture-missing-initial-storage [compiler-restriction]
//
// The source it stood for:
//   async function mapWgpuCaptureBuffer(buffer: GPUBuffer, timeoutMs: number): Promise<void> {
//     const mapping = buffer.mapAsync(GPUMapMode.READ);
//     if (timeoutMs <= 0) return mapping;
//   
//     // The race abandons `mapping` on timeout; adopt its eventual rejection here so it is never unhandled.
//     mapping.catch(() => {});
//   
//     let timer: ReturnType<typeof setTimeout> | undefined;
//     const expiry = new Promise<never>((_resolve, reject) => {
//       timer = setTimeout(() => {
//         reject(new Error(`createBitmapFromWgpuScreenRenderTarget: capture buffer did not map within ${timeoutMs}ms`));
//       }, timeoutMs);
//     });
//   
//     try {
//       await Promise.race([mapping, expiry]);
//     } finally {
//       clearTimeout(timer);
//     }
//   }
//   
//   // Generous by design: this bounds a driver that has stopped answering, not a slow one. Callers working
//   // inside a tighter budget (the capture harness) pass their own.
// cpp emission failed for @flighthq/render-wgpu/packages/render-wgpu/src/wgpuScreenCapture.ts: shared mutable
// capture timer requires explicit initial storage

inline const double default_map_timeout_ms = 10000.0;


// NOT GENERATED: function createBitmapFromWgpuScreenRenderTarget -- source line 15
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export async function createBitmapFromWgpuScreenRenderTarget(
//     target: Readonly<WgpuScreenRenderTarget>,
//     timeoutMs = DEFAULT_MAP_TIMEOUT_MS,
//   ): Promise<Bitmap> {
//     const buffer = target.captureBuffer;
//     if (buffer === null) {
//       throw new Error(
//         'createBitmapFromWgpuScreenRenderTarget requires enableWgpuScreenRenderTargetCapture(target) before rendering, then a submitted frame.',
//       );
//     }
//   
//     const width = target.captureWidth;
//     const height = target.captureHeight;
//     const bytesPerRow = target.captureBytesPerRow;
//   
//     await mapWgpuCaptureBuffer(buffer, timeoutMs);
//     const mapped = new Uint8Array(buffer.getMappedRange());
//   
//     const bitmap = createBitmap(width, height);
//     const out = bitmap.data;
//     // The preferred canvas format is BGRA on most platforms and RGBA on software adapters; normalize to
//     // the Bitmap's RGBA byte order so coverage/fingerprint and saved pixels read correctly either way.
//     // Pixels are left premultiplied (the texture's stored form): functional content renders over an opaque
//     // background, so alpha is 255 and premultiplied == straight; do NOT un-premultiply here — dividing RGB
//     // by an 8-bit alpha amplifies quantization and clamps, blowing out exactly the semi-transparent pixels
//     // a colour comparison cares about. If straight-alpha output is ever needed, convert at the consumer in
//     // higher precision, or compare in premultiplied space on both sides.
//     const swizzleBGRA = target.format === 'bgra8unorm' || target.format === 'bgra8unorm-srgb';
//     for (let y = 0; y < height; y++) {
//       const srcRow = y * bytesPerRow;
//       const dstRow = y * width * 4;
//       for (let x = 0; x < width; x++) {
//         const s = srcRow + x * 4;
//         const d = dstRow + x * 4;
//         out[d] = swizzleBGRA ? mapped[s + 2] : mapped[s];
//         out[d + 1] = mapped[s + 1];
//         out[d + 2] = swizzleBGRA ? mapped[s] : mapped[s + 2];
//         out[d + 3] = mapped[s + 3];
//       }
//     }
//   
//     // Unmap (not destroy) so the next frame's submit can copy into the retained buffer again.
//     buffer.unmap();
//     return bitmap;
//   }
//   
//   // Enables opt-in capture on a screen target so createBitmapFromWgpuScreenRenderTarget can read it back.
//   // The frame is then drawn into an offscreen texture instead of the swap chain (the only reliably readable
//   // path on headless/software adapters); the canvas is not presented while capture is on. Leave it off for
//   // normal on-screen rendering. The capture texture and buffer are allocated lazily.
// cpp emission failed for @flighthq/render-wgpu/packages/render-wgpu/src/wgpuScreenCapture.ts: contextual
// optionalSingle construction requires expression type evidence

} // namespace flight::render_wgpu
