// Generated by @flighthq/tool-compiler from @flighthq/render-wgpu/packages/render-wgpu/src/wgpuTextureUpload.ts#WgpuTextureUpload at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/host_sdl/image.hpp>
#include <flight/host_sdl/wgpu.hpp>
#include <flight/structural_ref.hpp>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct ImageResource; }

#include <flight/types/alpha_type.hpp>
#include <flight/types/host_image_source.hpp>
#include <flight/types/image_resource.hpp>
#include <flight/types/texture_source_kind.hpp>
#include <flight/render_wgpu/wgpu_external_image_source.hpp>

namespace flight::render_wgpu {

inline void upload_wgpu_texture_data(flight::host_sdl::WgpuDevice device, flight::host_sdl::WgpuTexture texture, flight::host_sdl::WgpuOrigin3D origin, double width, double height, flight::Uint8ClampedArray data) {
  throw flight::Error(flight::String("render-wgpu: texture queue upload is unavailable in this profile"));
}

inline void upload_wgpu_texture_element(flight::host_sdl::WgpuDevice device, flight::host_sdl::WgpuTexture texture, flight::host_sdl::WgpuOrigin3D origin, double width, double height, flight::host_sdl::ImageSource source) {
  throw flight::Error(flight::String("render-wgpu: external image upload is unavailable in this profile"));
}

inline void upload_wgpu_texture_image_resource(flight::host_sdl::WgpuDevice device, flight::host_sdl::WgpuTexture texture, flight::host_sdl::WgpuOrigin3D origin, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::ImageResource>>>> image) {
  upload_wgpu_texture_element(device, texture, origin, flight::row_get<flight::RowKey<"width">>(image), flight::row_get<flight::RowKey<"height">>(image), flight::row_get<flight::RowKey<"source">>(image));
}

} // namespace flight::render_wgpu
