// Generated by @flighthq/tool-compiler from @flighthq/easing/packages/easing/src/createEasingSamples.ts#CreateEasingSamples at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function createEasingSamples -- source line 17
#include <cmath>
#include <cstdint>
#include <flight/number.hpp>
#include <limits>
#include <optional>
#include <random>
#include <flight/runtime.hpp>
#include <flight/types/easing_function.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::easing {

// OVERRIDE: the one function the emitter refused in @flighthq/easing, hand-written from the TypeScript
// quoted below it. With this in place the package is 23/23 modules and 23/23 headers.
//
// The refusal is about the SIGNATURE, not the body: `out?: Float32Array` returning `Float32Array` gives
// the compiler a union whose two domains -- the supplied array and the freshly allocated one -- land on
// one carrier, `flight::Float32Array`, with no discriminator. It is right to refuse that in general,
// because it cannot know the two are meant to be the same object. Here they are, and the TypeScript says
// so explicitly: "Returns the output array (always the same object as `out` when one is supplied)."
//
// So this is a faithful transcription, and the three things worth checking are the three the source
// comments call out:
//
//   * count=1 samples the MIDPOINT, ease(0.5), not ease(0).
//   * the endpoints are reassigned after the loop, deliberately, to clamp away floating-point drift in
//     `i * step` -- so result[0] is exactly ease(0) and result[n-1] exactly ease(1).
//   * `t` is read into a local before the write, which the source marks as alias safety: `out` may be a
//     view over memory the easing function also reads.
//
// `Number.isFinite` lowers to std::isfinite, which is how the emitter writes it everywhere else in the
// tree -- the same spelling the surrounding package already uses.
//
// Absence is the one thing not transcribed but TRANSLATED, and it is translated the way this runtime
// already represents it: `out?` is std::optional, and `out ?? new Float32Array(n)` is "use the supplied
// array if present, otherwise allocate". The returned value is the same Float32Array object in the
// supplied case, because flight::Float32Array is a handle onto shared storage -- which is what makes the
// TypeScript guarantee hold rather than merely appear to.
inline flight::Float32Array create_easing_samples(flight::types::EasingFunction ease, double count,
                                                 std::optional<flight::Float32Array> out = std::nullopt) {
  if ((!std::isfinite(count) || (count < 1.0))) {
    throw flight::Error(flight::String("createEasingSamples: count must be a finite integer >= 1"));
  }
  const double n = std::floor(count);
  flight::Float32Array result =
      out.has_value() ? out.value() : flight::Float32Array(static_cast<std::size_t>(n));
  if ((n == 1.0)) {
    result.set_index(0.0, ease(0.5));
    return result;
  }
  const double step = (1.0 / (n - 1.0));
  for (double i = 0.0; (i < n); i += 1.0) {
    // Read t into a local before writing to result, preserving alias safety.
    const double t = (i * step);
    result.set_index(i, ease((t < 0.0) ? 0.0 : ((t > 1.0) ? 1.0 : t)));
  }
  // Clamp the endpoints exactly to avoid floating-point drift.
  result.set_index(0.0, ease(0.0));
  result.set_index((n - 1.0), ease(1.0));
  return result;
}


// NOT GENERATED: function createEasingSamples -- source line 17
// refusal: cpp-union-runtime-domains-erased [target-runtime]
//
// The source it stood for:
//   export function createEasingSamples(ease: EasingFunction, count: number, out?: Float32Array): Float32Array {
//     if (!Number.isFinite(count) || count < 1) {
//       throw new Error('createEasingSamples: count must be a finite integer >= 1');
//     }
//     const n = Math.floor(count);
//     const result = out ?? new Float32Array(n);
//     if (n === 1) {
//       result[0] = ease(0.5);
//       return result;
//     }
//     const step = 1 / (n - 1);
//     for (let i = 0; i < n; i++) {
//       // Read t into a local before writing to result, preserving alias safety.
//       const t = i * step;
//       result[i] = ease(t < 0 ? 0 : t > 1 ? 1 : t);
//     }
//     // Clamp the endpoints exactly to avoid floating-point drift.
//     result[0] = ease(0);
//     result[n - 1] = ease(1);
//     return result;
//   }
//   
// cpp emission failed for @flighthq/easing/packages/easing/src/createEasingSamples.ts: C++ runtime contract maps
// distinct union domains to one carrier without a discriminator or checked projection (Float32Array |
// Float32Array -> flight::Float32Array); give the domains distinguishable key, element, or member types so each
// reaches a carrier of its own -- a union of two declarations that differ only in name is one carrier whatever
// the emitter does -- or provide that runtime contract

} // namespace flight::easing