// Generated by @flighthq/tool-compiler from @flighthq/preferences/packages/preferences/src/storage.ts#Storage at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <cmath>
#include <flight/any.hpp>
#include <flight/error.hpp>
#include <flight/json.hpp>
#include <flight/number.hpp>
#include <flight/object.hpp>
#include <flight/record.hpp>
#include <flight/weak_map.hpp>
#include <functional>
#include <limits>
#include <optional>
#include <type_traits>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/signals/slot.hpp>

#include <flight/signals/emitter.hpp>

#include <flight/signals/signal.hpp>

#include <flight/entity/entity.hpp>

#include <flight/types/storage.hpp>

#include <flight/types/entity.hpp>

namespace flight::preferences {

using flight::signals::clear_signal;
using flight::signals::emit_signal;
using flight::signals::has_signal_slots;

using flight::signals::create_signal;

using flight::entity::allocate_entity;
using flight::entity::finish_entity;

using flight::types::EntityConstruction;
using flight::types::HostPreferencesCapability;
using flight::types::HostPreferencesChangeCapability;
using flight::types::StorageBooleanOrResult;
using flight::types::StorageBooleanResult;
using flight::types::StorageByteSizeResult;
using flight::types::StorageChange;
using flight::types::StorageClearNamespaceResult;
using flight::types::StorageClearResult;
using flight::types::StorageEntriesResult;
using flight::types::StorageGetItemResult;
using flight::types::StorageItemCountResult;
using flight::types::StorageItemOrResult;
using flight::types::StorageItemsResult;
using flight::types::StorageJsonOrResult;
using flight::types::StorageJsonResult;
using flight::types::StorageJsonWriteResult;
using flight::types::StorageKeysResult;
using flight::types::StorageMigration;
using flight::types::StorageMigrationResult;
using flight::types::StorageNamespace;
using flight::types::StorageNumberOrResult;
using flight::types::StorageNumberResult;
using flight::types::StoragePresenceResult;
using flight::types::StorageRemoveItemResult;
using flight::types::StorageRemoveItemsResult;
using flight::types::StorageSetItemResult;
using flight::types::StorageSetItemsResult;
using flight::types::StorageSignals;

template <typename Outcome>
inline flight::String storage_outcome_reason(const Outcome& outcome) {
  return std::visit([](const auto& value) { return flight::String(value->reason); }, outcome);
}

template <typename Outcome, typename Value>
inline Outcome storage_value_success(Value value) {
  using Record = typename std::variant_alternative_t<1, Outcome>::element_type;
  return Outcome(std::in_place_index<1>,
                 flight::make_ref<Record>(Record{.reason = flight::String("ok"),
                                                  .value = std::move(value)}));
}

template <typename Outcome>
inline Outcome storage_value_failure(flight::String reason) {
  using Record = typename std::variant_alternative_t<0, Outcome>::element_type;
  return Outcome(std::in_place_index<0>,
                 flight::make_ref<Record>(Record{.reason = std::move(reason), .value = nullptr}));
}

template <typename Outcome, typename Value>
inline Outcome storage_fallback_value(flight::String reason, Value value) {
  using Record = typename std::variant_alternative_t<1, Outcome>::element_type;
  return Outcome(std::in_place_index<1>,
                 flight::make_ref<Record>(Record{.reason = std::move(reason),
                                                  .value = std::move(value)}));
}

template <typename Outcome, typename Value>
inline Outcome storage_query_success(Value value) {
  using Record = typename std::variant_alternative_t<0, Outcome>::element_type;
  return Outcome(std::in_place_index<0>,
                 flight::make_ref<Record>(Record{.failed_key = nullptr,
                                                  .reason = flight::String("ok"),
                                                  .value = std::move(value)}));
}

template <typename Outcome>
inline Outcome storage_query_failure(std::optional<flight::String> failed_key,
                                     flight::String reason) {
  using Record = typename std::variant_alternative_t<1, Outcome>::element_type;
  return Outcome(std::in_place_index<1>,
                 flight::make_ref<Record>(Record{.failed_key = std::move(failed_key),
                                                  .reason = std::move(reason),
                                                  .value = nullptr}));
}

template <typename Outcome>
inline Outcome storage_batch_success(double completed) {
  using Record = typename std::variant_alternative_t<0, Outcome>::element_type;
  return Outcome(std::in_place_index<0>,
                 flight::make_ref<Record>(Record{.completed = completed,
                                                  .failed_key = nullptr,
                                                  .reason = flight::String("ok")}));
}

template <typename Outcome>
inline Outcome storage_batch_failure(double completed, std::optional<flight::String> failed_key,
                                     flight::String reason) {
  using Record = typename std::variant_alternative_t<1, Outcome>::element_type;
  return Outcome(std::in_place_index<1>,
                 flight::make_ref<Record>(Record{.completed = completed,
                                                  .failed_key = std::move(failed_key),
                                                  .reason = std::move(reason)}));
}

template <typename Outcome>
inline Outcome storage_mutation(flight::String reason) {
  if (reason == flight::String("ok")) {
    using Record = typename std::variant_alternative_t<1, Outcome>::element_type;
    return Outcome(std::in_place_index<1>,
                   flight::make_ref<Record>(Record{.reason = std::move(reason)}));
  }
  using Record = typename std::variant_alternative_t<0, Outcome>::element_type;
  return Outcome(std::in_place_index<0>,
                 flight::make_ref<Record>(Record{.reason = std::move(reason)}));
}

template <typename Outcome>
inline const auto& storage_value(const Outcome& outcome) {
  return std::get<1>(outcome)->value;
}

template <typename Outcome>
inline const auto& storage_query_value(const Outcome& outcome) {
  return std::get<0>(outcome)->value;
}

template <typename Value>
inline Value storage_json_cast(flight::JsonValue value) {
  if constexpr (std::same_as<Value, flight::JsonValue>) return value;
  else if constexpr (std::same_as<Value, bool>) return value.as_boolean();
  else if constexpr (std::same_as<Value, double>) return value.as_number();
  else if constexpr (std::same_as<Value, flight::String>) return value.as_string();
  else if constexpr (std::same_as<Value, flight::JsonArray>) return value.as_array();
  else if constexpr (std::same_as<Value, flight::JsonObject>) return value.as_object();
  else throw flight::BadJsonValueAccess();
}

inline StorageMigrationResult storage_migration_success(double version) {
  using Record = typename std::variant_alternative_t<0, StorageMigrationResult>::element_type;
  return StorageMigrationResult(std::in_place_index<0>, flight::make_ref<Record>(Record{
      .failed_version = nullptr, .reason = flight::String("ok"), .stage = nullptr,
      .version = version}));
}

inline StorageMigrationResult storage_migration_read_failure(flight::String reason) {
  using Record = typename std::variant_alternative_t<1, StorageMigrationResult>::element_type;
  return StorageMigrationResult(std::in_place_index<1>, flight::make_ref<Record>(Record{
      .failed_version = nullptr, .reason = std::move(reason), .stage = flight::String("read-version"),
      .version = nullptr}));
}

inline StorageMigrationResult storage_migration_checkpoint_failure(
    double failed_version, flight::String reason, double version) {
  using Record = typename std::variant_alternative_t<2, StorageMigrationResult>::element_type;
  return StorageMigrationResult(std::in_place_index<2>, flight::make_ref<Record>(Record{
      .failed_version = failed_version, .reason = std::move(reason),
      .stage = flight::String("checkpoint"), .version = version}));
}

inline void destroy_storage(flight::Ref<HostPreferencesChangeCapability> host_preferences_change) {
  host_preferences_change->destroy();
}

inline flight::Ref<StorageKeysResult> get_namespaced_storage_keys(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_) {
  const flight::String prefix = namespace_->prefix + flight::String(".");
  flight::Ref<StorageKeysResult> result = host_preferences->keys();
  if (storage_outcome_reason(result) != flight::String("ok")) {
    return result;
  }
  return storage_value_success<StorageKeysResult>(storage_value(result).filter([=](flight::String key) { return key.starts_with(prefix); }).map([=](flight::String key) { return key.slice(static_cast<double>(prefix.length())); }));
}

inline flight::Ref<StorageBooleanResult> get_storage_boolean(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageBooleanResult>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_value_success<StorageBooleanResult>(std::optional<bool>{});
  }
  if (storage_value(raw).value() == flight::String("true")) {
    return storage_value_success<StorageBooleanResult>(std::optional<bool>{true});
  }
  if (storage_value(raw).value() == flight::String("false")) {
    return storage_value_success<StorageBooleanResult>(std::optional<bool>{false});
  }
  return storage_value_failure<StorageBooleanResult>(flight::String("parse-failed"));
}

inline flight::Ref<StorageBooleanOrResult> get_storage_boolean_or(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, bool fallback) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageBooleanOrResult>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_fallback_value<StorageBooleanOrResult>(flight::String("ok"), fallback);
  }
  if (storage_value(raw).value() == flight::String("true")) {
    return storage_fallback_value<StorageBooleanOrResult>(flight::String("ok"), true);
  }
  if (storage_value(raw).value() == flight::String("false")) {
    return storage_fallback_value<StorageBooleanOrResult>(flight::String("ok"), false);
  }
  return storage_fallback_value<StorageBooleanOrResult>(flight::String("parse-failed"), fallback);
}

inline flight::Ref<StorageGetItemResult> get_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key) {
  return host_preferences->get_item(key);
}

inline flight::Ref<StorageItemCountResult> get_storage_item_count(flight::Ref<HostPreferencesCapability> host_preferences) {
  flight::Ref<StorageKeysResult> result = host_preferences->keys();
  if (storage_outcome_reason(result) != flight::String("ok")) {
    return storage_value_failure<StorageItemCountResult>(storage_outcome_reason(result));
  }
  return storage_value_success<StorageItemCountResult>(static_cast<double>(storage_value(result).size()));
}

inline flight::Ref<StorageItemOrResult> get_storage_item_or(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, flight::String fallback) {
  flight::Ref<StorageGetItemResult> result = host_preferences->get_item(key);
  if (storage_outcome_reason(result) != flight::String("ok")) {
    return storage_value_failure<StorageItemOrResult>(storage_outcome_reason(result));
  }
  return storage_value_success<StorageItemOrResult>(storage_value(result).value_or(fallback));
}

inline flight::Ref<StoragePresenceResult> get_storage_item_presence(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key) {
  flight::Ref<StorageGetItemResult> result = host_preferences->get_item(key);
  if (storage_outcome_reason(result) != flight::String("ok")) {
    return storage_value_failure<StoragePresenceResult>(storage_outcome_reason(result));
  }
  return storage_value_success<StoragePresenceResult>(storage_value(result).has_value());
}

inline flight::Ref<StorageItemsResult> get_storage_items(flight::Ref<HostPreferencesCapability> host_preferences, flight::Array<flight::String> keys) {
  flight::Array<std::optional<flight::String>> out = flight::Array<std::optional<flight::String>>{};
  for (auto key : keys) {
    flight::Ref<StorageGetItemResult> result = host_preferences->get_item(key);
    if (storage_outcome_reason(result) != flight::String("ok")) {
      return storage_query_failure<StorageItemsResult>(key, storage_outcome_reason(result));
    }
    out.push(storage_value(result));
  }
  return storage_query_success<StorageItemsResult>(out);
}

template <typename Value>
inline flight::Ref<StorageJsonResult<Value>> get_storage_json(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageJsonResult<Value>>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_value_success<StorageJsonResult<Value>>(std::optional<Value>{});
  }
  try {
    return storage_value_success<StorageJsonResult<Value>>(
        std::optional<Value>{storage_json_cast<Value>(flight::Json::parse(storage_value(raw).value()))});
  }
  catch (...) {
    return storage_value_failure<StorageJsonResult<Value>>(flight::String("parse-failed"));
  }
}

template <typename Value>
inline flight::Ref<StorageJsonOrResult<Value>> get_storage_jsonor(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, Value fallback) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageJsonOrResult<Value>>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_fallback_value<StorageJsonOrResult<Value>>(flight::String("ok"), std::optional<Value>{fallback});
  }
  try {
    return storage_fallback_value<StorageJsonOrResult<Value>>(
        flight::String("ok"),
        std::optional<Value>{storage_json_cast<Value>(flight::Json::parse(storage_value(raw).value()))});
  }
  catch (...) {
    return storage_fallback_value<StorageJsonOrResult<Value>>(flight::String("parse-failed"), std::optional<Value>{fallback});
  }
}

inline flight::Ref<StorageKeysResult> get_storage_keys(flight::Ref<HostPreferencesCapability> host_preferences) {
  return host_preferences->keys();
}

inline flight::Ref<StorageNumberResult> get_storage_number(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageNumberResult>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_value_success<StorageNumberResult>(std::optional<double>{});
  }
  const double value = flight::to_number(storage_value(raw).value());
  return std::isfinite(value)
             ? storage_value_success<StorageNumberResult>(std::optional<double>{value})
             : storage_value_failure<StorageNumberResult>(flight::String("parse-failed"));
}

inline flight::Ref<StorageNumberOrResult> get_storage_number_or(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, double fallback) {
  flight::Ref<StorageGetItemResult> raw = host_preferences->get_item(key);
  if (storage_outcome_reason(raw) != flight::String("ok")) {
    return storage_value_failure<StorageNumberOrResult>(storage_outcome_reason(raw));
  }
  if (!storage_value(raw).has_value()) {
    return storage_fallback_value<StorageNumberOrResult>(flight::String("ok"), fallback);
  }
  const double value = flight::to_number(storage_value(raw).value());
  return storage_fallback_value<StorageNumberOrResult>(
      std::isfinite(value) ? flight::String("ok") : flight::String("parse-failed"),
      std::isfinite(value) ? value : fallback);
}

inline void initialize_storage_signals(flight::Ref<EntityConstruction<flight::Ref<StorageSignals>>> out) {
  (out->on_change = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_change)>::element_type>>());
}

inline flight::Ref<StorageSignals> create_storage_signals() {
  flight::Ref<EntityConstruction<flight::Ref<StorageSignals>>> out = allocate_entity<flight::Ref<StorageSignals>>();
  initialize_storage_signals(out);
  return finish_entity(out);
}

inline flight::Ref<StorageByteSizeResult> get_storage_byte_size_for_prefix(flight::Ref<HostPreferencesCapability> host_preferences, std::optional<flight::String> prefix) {
  flight::Ref<StorageKeysResult> keys = host_preferences->keys();
  if (storage_outcome_reason(keys) != flight::String("ok")) {
    return storage_query_failure<StorageByteSizeResult>(std::nullopt, storage_outcome_reason(keys));
  }
  double value = 0.0;
  for (auto key : storage_value(keys)) {
    if ((prefix.has_value() && !key.starts_with(prefix.value()))) {
      continue;
    }
    flight::Ref<StorageGetItemResult> item = host_preferences->get_item(key);
    if (storage_outcome_reason(item) != flight::String("ok")) {
      return storage_query_failure<StorageByteSizeResult>(key, storage_outcome_reason(item));
    }
    if (storage_value(item).has_value()) {
      value += (static_cast<double>(key.length()) +
                static_cast<double>(storage_value(item).value().length())) * 2.0;
    }
  }
  return storage_query_success<StorageByteSizeResult>(value);
}

inline flight::Ref<StorageByteSizeResult> get_namespaced_storage_byte_size(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_) {
  return get_storage_byte_size_for_prefix(host_preferences, std::optional<flight::String>{namespace_->prefix + flight::String(".")});
}

inline flight::Ref<StorageByteSizeResult> get_storage_byte_size(flight::Ref<HostPreferencesCapability> host_preferences) {
  return get_storage_byte_size_for_prefix(host_preferences, std::nullopt);
}

inline flight::Ref<StorageEntriesResult> get_storage_entries_for_prefix(flight::Ref<HostPreferencesCapability> host_preferences, std::optional<flight::String> prefix) {
  flight::Ref<StorageKeysResult> keys = host_preferences->keys();
  if (storage_outcome_reason(keys) != flight::String("ok")) {
    return storage_query_failure<StorageEntriesResult>(std::nullopt, storage_outcome_reason(keys));
  }
  flight::Array<flight::Array<flight::String>> value = flight::Array<flight::Array<flight::String>>{};
  for (auto key : storage_value(keys)) {
    if ((prefix.has_value() && !key.starts_with(prefix.value()))) {
      continue;
    }
    flight::Ref<StorageGetItemResult> item = host_preferences->get_item(key);
    if (storage_outcome_reason(item) != flight::String("ok")) {
      return storage_query_failure<StorageEntriesResult>(key, storage_outcome_reason(item));
    }
    if (storage_value(item).has_value()) {
      value.push(flight::Array<flight::String>{key, storage_value(item).value()});
    }
  }
  return storage_query_success<StorageEntriesResult>(value);
}

inline flight::Ref<StorageEntriesResult> get_namespaced_storage_entries(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_) {
  const flight::String prefix = namespace_->prefix + flight::String(".");
  flight::Ref<StorageEntriesResult> result = get_storage_entries_for_prefix(host_preferences, std::optional<flight::String>{prefix});
  if (storage_outcome_reason(result) != flight::String("ok")) {
    return result;
  }
  return storage_query_success<StorageEntriesResult>(storage_query_value(result).map([=](flight::Array<flight::String> parameter_pattern_value) {
  flight::String key;
  flight::String value;
  flight::Array<flight::String> array_pattern_value = parameter_pattern_value;
  (key = array_pattern_value.element(0.0));
  (value = array_pattern_value.element(1.0));
  return flight::Array<flight::String>{key.slice(static_cast<double>(prefix.length())), value};
}));
}

inline flight::Ref<StorageEntriesResult> get_storage_entries(flight::Ref<HostPreferencesCapability> host_preferences) {
  return get_storage_entries_for_prefix(host_preferences, std::nullopt);
}

inline flight::String namespaced_key(flight::Ref<StorageNamespace> namespace_, flight::String key) {
  return namespace_->prefix + flight::String(".") + key;
}

inline flight::Ref<StorageGetItemResult> get_namespaced_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_, flight::String key) {
  return host_preferences->get_item(namespaced_key(namespace_, key));
}

inline flight::Ref<StoragePresenceResult> get_namespaced_storage_item_presence(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_, flight::String key) {
  return get_storage_item_presence(host_preferences, namespaced_key(namespace_, key));
}

inline bool storage_signals_active(std::optional<flight::Ref<StorageSignals>> signals) {
  return signals.has_value() && signals.value()->on_change->data.has_value() &&
         !signals.value()->on_change->data.value()->slots.empty();
}

inline flight::Ref<StorageClearResult> clear_storage(flight::Ref<HostPreferencesCapability> host_preferences, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  flight::Ref<StorageClearResult> result = host_preferences->clear();
  if (storage_outcome_reason(result) == flight::String("ok") && storage_signals_active(signals.value())) {
    emit_signal(signals.value().value()->on_change,
                flight::make_ref<StorageChange>(StorageChange{
                    .key = std::nullopt, .new_value = std::nullopt,
                    .old_value = std::nullopt}));
  }
  return result;
}

inline flight::Ref<StorageRemoveItemResult> remove_storage_item_from_backend(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, std::optional<flight::Ref<StorageSignals>> signals) {
  const bool active = storage_signals_active(signals);
  std::optional<StorageGetItemResult> old_value =
      active ? std::optional<StorageGetItemResult>{host_preferences->get_item(key)} : std::nullopt;
  flight::Ref<StorageRemoveItemResult> result = host_preferences->remove_item(key);
  if (storage_outcome_reason(result) == flight::String("ok") && active && old_value.has_value() &&
      storage_outcome_reason(old_value.value()) == flight::String("ok") &&
      storage_value(old_value.value()).has_value()) {
    emit_signal(signals.value()->on_change,
                flight::make_ref<StorageChange>(StorageChange{
                    .key = key, .new_value = std::nullopt,
                    .old_value = storage_value(old_value.value()).value()}));
  }
  return result;
}

inline flight::Ref<StorageClearNamespaceResult> clear_storage_namespace(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  const flight::String prefix = namespace_->prefix + flight::String(".");
  flight::Ref<HostPreferencesCapability> backend = host_preferences;
  flight::Ref<StorageKeysResult> keys = backend->keys();
  if (storage_outcome_reason(keys) != flight::String("ok")) {
    return storage_batch_failure<StorageClearNamespaceResult>(0.0, std::nullopt,
                                                               storage_outcome_reason(keys));
  }
  double completed = 0.0;
  for (auto key : storage_value(keys)) {
    if (!key.starts_with(prefix)) {
      continue;
    }
    flight::Ref<StorageRemoveItemResult> result = remove_storage_item_from_backend(backend, key, signals.value());
    if (storage_outcome_reason(result) != flight::String("ok")) {
      return storage_batch_failure<StorageClearNamespaceResult>(completed, key, storage_outcome_reason(result));
    }
    completed++;
  }
  return storage_batch_success<StorageClearNamespaceResult>(completed);
}

inline flight::Ref<StorageRemoveItemResult> remove_namespaced_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_, flight::String key, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  return remove_storage_item_from_backend(host_preferences, namespaced_key(namespace_, key), signals.value());
}

inline flight::Ref<StorageRemoveItemResult> remove_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  return remove_storage_item_from_backend(host_preferences, key, signals.value());
}

inline flight::Ref<StorageRemoveItemsResult> remove_storage_items(flight::Ref<HostPreferencesCapability> host_preferences, flight::Array<flight::String> keys, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  double completed = 0.0;
  for (auto key : keys) {
    flight::Ref<StorageRemoveItemResult> result = remove_storage_item_from_backend(host_preferences, key, signals.value());
    if (storage_outcome_reason(result) != flight::String("ok")) {
      return storage_batch_failure<StorageRemoveItemsResult>(completed, key, storage_outcome_reason(result));
    }
    completed++;
  }
  return storage_batch_success<StorageRemoveItemsResult>(completed);
}

inline flight::Ref<StorageSetItemResult> set_storage_item_on_backend(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, flight::String value, std::optional<flight::Ref<StorageSignals>> signals) {
  const bool active = storage_signals_active(signals);
  std::optional<StorageGetItemResult> old_value =
      active ? std::optional<StorageGetItemResult>{host_preferences->get_item(key)} : std::nullopt;
  flight::Ref<StorageSetItemResult> result = host_preferences->set_item(key, value);
  if (storage_outcome_reason(result) == flight::String("ok") && active && old_value.has_value() &&
      storage_outcome_reason(old_value.value()) == flight::String("ok") &&
      storage_value(old_value.value()) != std::optional<flight::String>{value}) {
    emit_signal(signals.value()->on_change,
                flight::make_ref<StorageChange>(StorageChange{
                    .key = key, .new_value = value, .old_value = storage_value(old_value.value())}));
  }
  return result;
}

inline flight::Ref<StorageSetItemResult> set_namespaced_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::Ref<StorageNamespace> namespace_, flight::String key, flight::String value, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  return set_storage_item_on_backend(host_preferences, namespaced_key(namespace_, key), value, signals.value());
}

inline flight::Ref<StorageSetItemResult> set_storage_boolean(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, bool value, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  return set_storage_item_on_backend(host_preferences, key, (value ? flight::String("true") : flight::String("false")), signals.value());
}

inline flight::Ref<StorageSetItemResult> set_storage_item(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, flight::String value, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  return set_storage_item_on_backend(host_preferences, key, value, signals.value());
}

inline flight::Ref<StorageSetItemsResult> set_storage_items(flight::Ref<HostPreferencesCapability> host_preferences, flight::Record<flight::String, flight::String> record, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  double completed = 0.0;
  for (auto key : flight::object_keys(record)) {
    flight::Ref<StorageSetItemResult> result = set_storage_item_on_backend(host_preferences, key, record.get(key).value(), signals.value());
    if (storage_outcome_reason(result) != flight::String("ok")) {
      return storage_batch_failure<StorageSetItemsResult>(completed, key, storage_outcome_reason(result));
    }
    completed++;
  }
  return storage_batch_success<StorageSetItemsResult>(completed);
}

template <typename Value>
inline flight::Ref<StorageJsonWriteResult> set_storage_json(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, Value value, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  std::optional<flight::String> raw;
  try {
    (raw = std::optional<flight::String>{flight::Json::stringify(value, std::nullopt, std::nullopt)});
  }
  catch (...) {
    return storage_mutation<StorageJsonWriteResult>(flight::String("serialization-failed"));
  }
  return set_storage_item_on_backend(host_preferences, key, raw.value(), signals.value());
}

inline flight::Ref<StorageSetItemResult> set_storage_number(flight::Ref<HostPreferencesCapability> host_preferences, flight::String key, double value, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  if (!std::isfinite(value)) {
    throw flight::RangeError(flight::String("setStorageNumber value must be finite"));
  }
  return set_storage_item_on_backend(host_preferences, key, flight::to_string(value), signals.value());
}

inline flight::Array<flight::Ref<StorageMigration>> validate_storage_migrations(flight::Array<flight::Ref<StorageMigration>> migrations) {
  auto versions = flight::Set<double>();
  for (auto migration : migrations) {
    if ((!flight::is_integer(migration->version) || (migration->version <= 0.0))) {
      throw flight::RangeError(flight::String("Storage migration versions must be positive integers"));
    }
    if (versions.has(migration->version)) {
      throw flight::RangeError(flight::String("Storage migration version ") + flight::to_string(migration->version) + flight::String(" is duplicated"));
    }
    versions.add(migration->version);
  }
  return ([&]() { flight::Array<flight::Ref<StorageMigration>> array_spread_result; for (const auto& array_spread_item : migrations) { array_spread_result.push(array_spread_item); } return array_spread_result; }()).sort([=](flight::Ref<StorageMigration> a, flight::Ref<StorageMigration> b) { return (a->version - b->version); });
}

inline flight::Ref<StorageMigrationResult> migrate_storage(flight::Ref<HostPreferencesCapability> host_preferences, std::optional<flight::Ref<StorageNamespace>> namespace_, flight::Array<flight::Ref<StorageMigration>> migrations, std::optional<std::optional<flight::Ref<StorageSignals>>> signals = std::nullopt) {
  signals = signals.value_or(std::nullopt);
  flight::Array<flight::Ref<StorageMigration>> sorted = validate_storage_migrations(migrations);
  const flight::String version_key = (!namespace_.has_value() ? flight::String("__flight_storage_version") : namespaced_key(namespace_.value(), flight::String("__flight_storage_version")));
  flight::Ref<StorageGetItemResult> stored_version = host_preferences->get_item(version_key);
  if (storage_outcome_reason(stored_version) != flight::String("ok")) {
    return storage_migration_read_failure(storage_outcome_reason(stored_version));
  }
  double checkpoint = 0.0;
  if (storage_value(stored_version).has_value()) {
    const double parsed = flight::to_number(storage_value(stored_version).value());
    if ((!flight::is_integer(parsed) || (parsed < 0.0))) {
      return storage_migration_read_failure(flight::String("version-parse-failed"));
    }
    (checkpoint = parsed);
  }
  const double initial_checkpoint = checkpoint;
  for (auto migration : sorted) {
    if ((migration->version <= initial_checkpoint)) {
      continue;
    }
    migration->migrate(namespace_.has_value()
                           ? std::optional<flight::String>{namespace_.value()->prefix}
                           : std::nullopt);
    flight::Ref<StorageSetItemResult> stored = set_storage_item_on_backend(host_preferences, version_key, flight::to_string(migration->version), signals.value());
    if (storage_outcome_reason(stored) != flight::String("ok")) {
      return storage_migration_checkpoint_failure(
          migration->version, storage_outcome_reason(stored), checkpoint);
    }
    (checkpoint = migration->version);
  }
  return storage_migration_success(checkpoint);
}

inline flight::WeakMap<flight::Ref<StorageSignals>, std::function<void()>> subscriptions = flight::WeakMap<flight::Ref<StorageSignals>, std::function<void()>>();

inline void detach_storage(flight::Ref<StorageSignals> signals) {
  std::optional<std::function<void()>> unsubscribe = subscriptions.get(signals);
  if (!unsubscribe.has_value()) {
    return;
  }
  subscriptions.erase(signals);
  unsubscribe.value()();
}

inline bool attach_storage(flight::Ref<HostPreferencesChangeCapability> host_preferences_change, flight::Ref<StorageSignals> signals) {
  detach_storage(signals);
  std::optional<std::function<void()>> unsubscribe = host_preferences_change->subscribe(
      [=](flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<StorageChange>>>> change) {
        emit_signal(signals->on_change, change);
      });
  if (!unsubscribe.has_value()) {
    return false;
  }
  subscriptions.set(signals, unsubscribe.value());
  return true;
}

inline void dispose_storage(flight::Ref<StorageSignals> signals) {
  detach_storage(signals);
  clear_signal(signals->on_change);
}

} // namespace flight::preferences
