// Generated by @flighthq/tool-compiler from @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts#ValidateParticleEmitterConfig at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function normalizeParticleEmitterConfig -- source line 83
//   missing: function reportCurve -- source line 190
//   missing: function reportInvertedRange -- source line 216
//   missing: function reportUnitRange -- source line 233
//   missing: function validateParticleEmitterConfig -- source line 128
#include <algorithm>
#include <cmath>
#include <flight/number.hpp>
#include <limits>
#include <optional>
#include <flight/runtime.hpp>
#include <flight/types/particle_config_issue.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/particles/particle_emitter_config.hpp>

namespace flight::particles {

inline flight::Array<flight::String> numeric_fields = flight::Array<flight::String>{flight::String("alphaEnd"), flight::String("alphaStart"), flight::String("burstCount"), flight::String("burstInterval"), flight::String("duration"), flight::String("colorEndB"), flight::String("colorEndG"), flight::String("colorEndR"), flight::String("colorEndVarianceB"), flight::String("colorEndVarianceG"), flight::String("colorEndVarianceR"), flight::String("colorStartB"), flight::String("colorStartG"), flight::String("colorStartR"), flight::String("colorStartVarianceB"), flight::String("colorStartVarianceG"), flight::String("colorStartVarianceR"), flight::String("directionX"), flight::String("directionY"), flight::String("directionZ"), flight::String("emitterConeAngle"), flight::String("emitterDepth"), flight::String("emitterHeight"), flight::String("emitterRadius"), flight::String("emitterWidth"), flight::String("frameCount"), flight::String("frameRate"), flight::String("gravityX"), flight::String("gravityY"), flight::String("gravityZ"), flight::String("lifetimeMax"), flight::String("lifetimeMin"), flight::String("maxParticles"), flight::String("regionIdMax"), flight::String("regionIdMin"), flight::String("rotationSpeedMax"), flight::String("rotationSpeedMin"), flight::String("scaleEnd"), flight::String("scaleMax"), flight::String("scaleMin"), flight::String("speedMax"), flight::String("speedMin"), flight::String("spawnRate"), flight::String("spread"), flight::String("velocityInheritance")};

inline flight::Array<flight::String> non_negative_fields = flight::Array<flight::String>{flight::String("burstCount"), flight::String("burstInterval"), flight::String("duration"), flight::String("emitterConeAngle"), flight::String("emitterDepth"), flight::String("emitterHeight"), flight::String("emitterRadius"), flight::String("emitterWidth"), flight::String("frameRate"), flight::String("lifetimeMin"), flight::String("lifetimeMax"), flight::String("maxParticles"), flight::String("scaleMax"), flight::String("scaleMin"), flight::String("speedMax"), flight::String("speedMin"), flight::String("spawnRate")};

inline bool is_finite_curve(std::optional<flight::Array<double>> curve) {
  if ((!curve.has_value() || (static_cast<double>(curve.value().size()) == 0.0))) {
    return false;
  }
  {
    double i = 0.0;
    while ((i < static_cast<double>(curve.value().size()))) {
      {
        if (!std::isfinite(curve.value().element(i))) {
          return false;
        }
      }
      (i += 1.0);
    }
  }
  return true;
}

// OVERRIDE: all five functions refused in @flighthq/particles are hand-written from the TypeScript
// quoted below. The refusals concern Partial<T>, intersection-key shapes, and closed-key access;
// the function bodies themselves use concrete ParticleEmitterConfig storage and ordinary control
// flow. With these definitions the package is 13/13 modules and 13/13 headers.
//
// normalize_particle_emitter_config deliberately creates `out`, repairs its non-finite numeric
// members from a separately created defaults object, and then returns a NEW ParticleEmitterConfig
// object. That is the TypeScript `{ ...out, overrides }` identity boundary. Array-valued curves keep
// their handles when retained, just as object spread retains the original JavaScript arrays.
namespace validate_particle_emitter_config_detail {

using PartialParticleEmitterConfig =
    entity_runtime_key_alpha_end_alpha_start_blend_mode_color_end_b_color_end_g_color_end_r_color_end_variance_b_color_end_variance_g_color_end_variance_r_color_start_b_color_start_g_color_start_r_color_start_variance_b_color_start_variance_g_color_start_variance_r_direction_x_direction_y_direction_z_gravity_x_gravity_y_gravity_z_emitter_cone_angle_emitter_depth_emitter_height_emitter_radius_emitter_shape_emitter_width_burst_count_burst_interval_duration_loop_frame_count_frame_rate_lifetime_max_lifetime_min_max_particles_region_id_max_region_id_min_scale_end_scale_max_scale_min_speed_max_speed_min_spawn_rate_spread_rotation_speed_max_rotation_speed_min_velocity_inheritance_alpha_curve_color_curve_scale_curve_world_space_a3d8bd7aab2f28f6;

inline double& numeric_field(const flight::Ref<flight::types::ParticleEmitterConfig>& config,
                             const flight::String& field) {
  if (field == flight::String("alphaEnd")) return config->alpha_end;
  if (field == flight::String("alphaStart")) return config->alpha_start;
  if (field == flight::String("burstCount")) return config->burst_count;
  if (field == flight::String("burstInterval")) return config->burst_interval;
  if (field == flight::String("duration")) return config->duration;
  if (field == flight::String("colorEndB")) return config->color_end_b;
  if (field == flight::String("colorEndG")) return config->color_end_g;
  if (field == flight::String("colorEndR")) return config->color_end_r;
  if (field == flight::String("colorEndVarianceB")) return config->color_end_variance_b;
  if (field == flight::String("colorEndVarianceG")) return config->color_end_variance_g;
  if (field == flight::String("colorEndVarianceR")) return config->color_end_variance_r;
  if (field == flight::String("colorStartB")) return config->color_start_b;
  if (field == flight::String("colorStartG")) return config->color_start_g;
  if (field == flight::String("colorStartR")) return config->color_start_r;
  if (field == flight::String("colorStartVarianceB")) return config->color_start_variance_b;
  if (field == flight::String("colorStartVarianceG")) return config->color_start_variance_g;
  if (field == flight::String("colorStartVarianceR")) return config->color_start_variance_r;
  if (field == flight::String("directionX")) return config->direction_x;
  if (field == flight::String("directionY")) return config->direction_y;
  if (field == flight::String("directionZ")) return config->direction_z;
  if (field == flight::String("emitterConeAngle")) return config->emitter_cone_angle;
  if (field == flight::String("emitterDepth")) return config->emitter_depth;
  if (field == flight::String("emitterHeight")) return config->emitter_height;
  if (field == flight::String("emitterRadius")) return config->emitter_radius;
  if (field == flight::String("emitterWidth")) return config->emitter_width;
  if (field == flight::String("frameCount")) return config->frame_count;
  if (field == flight::String("frameRate")) return config->frame_rate;
  if (field == flight::String("gravityX")) return config->gravity_x;
  if (field == flight::String("gravityY")) return config->gravity_y;
  if (field == flight::String("gravityZ")) return config->gravity_z;
  if (field == flight::String("lifetimeMax")) return config->lifetime_max;
  if (field == flight::String("lifetimeMin")) return config->lifetime_min;
  if (field == flight::String("maxParticles")) return config->max_particles;
  if (field == flight::String("regionIdMax")) return config->region_id_max;
  if (field == flight::String("regionIdMin")) return config->region_id_min;
  if (field == flight::String("rotationSpeedMax")) return config->rotation_speed_max;
  if (field == flight::String("rotationSpeedMin")) return config->rotation_speed_min;
  if (field == flight::String("scaleEnd")) return config->scale_end;
  if (field == flight::String("scaleMax")) return config->scale_max;
  if (field == flight::String("scaleMin")) return config->scale_min;
  if (field == flight::String("speedMax")) return config->speed_max;
  if (field == flight::String("speedMin")) return config->speed_min;
  if (field == flight::String("spawnRate")) return config->spawn_rate;
  if (field == flight::String("spread")) return config->spread;
  if (field == flight::String("velocityInheritance")) return config->velocity_inheritance;
  throw flight::Error(flight::String("validateParticleEmitterConfig: unknown numeric field ") + field);
}

inline void append_issue(flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> issues,
                         const flight::String& field, const flight::String& message,
                         const flight::String& severity) {
  issues.push(flight::make_ref<flight::types::ParticleConfigIssue>(
      flight::types::ParticleConfigIssue{
          .field = std::variant<flight::String, flight::Symbol>{std::in_place_type<flight::String>, field},
          .message = message,
          .severity = severity,
      }));
}

} // namespace validate_particle_emitter_config_detail

inline flight::Ref<flight::types::ParticleEmitterConfig> normalize_particle_emitter_config(
    std::optional<flight::Ref<validate_particle_emitter_config_detail::PartialParticleEmitterConfig>> config =
        std::nullopt) {
  const auto out = create_particle_emitter_config(config);
  const auto defaults = create_particle_emitter_config();

  // Replace any non-finite numeric field with its canonical default.
  for (double i = 0.0; i < static_cast<double>(numeric_fields.size()); i += 1.0) {
    const auto field = numeric_fields.element(i);
    auto& value = validate_particle_emitter_config_detail::numeric_field(out, field);
    if (!std::isfinite(value)) {
      value = validate_particle_emitter_config_detail::numeric_field(defaults, field);
    }
  }

  // Object spread creates a new object while retaining reference-valued members.
  auto normalized = flight::make_ref<flight::types::ParticleEmitterConfig>(*out);
  // Drop any curve that is empty or contains a non-finite sample so it can never
  // inject NaN — the simulation falls back to its linear interpolation path.
  normalized->alpha_curve = is_finite_curve(out->alpha_curve) ? out->alpha_curve : std::nullopt;
  normalized->color_curve = is_finite_curve(out->color_curve) ? out->color_curve : std::nullopt;
  normalized->scale_curve = is_finite_curve(out->scale_curve) ? out->scale_curve : std::nullopt;
  normalized->max_particles = std::max(0.0, std::floor(out->max_particles));
  normalized->burst_count = std::max(0.0, std::floor(out->burst_count));
  normalized->burst_interval = std::max(0.0, out->burst_interval);
  normalized->duration = std::max(0.0, out->duration);
  normalized->frame_count = std::max(1.0, std::floor(out->frame_count));
  normalized->frame_rate = std::max(0.0, out->frame_rate);
  normalized->region_id_min = std::max(0.0, std::floor(out->region_id_min));
  normalized->region_id_max =
      std::max(std::max(0.0, std::floor(out->region_id_min)), std::floor(out->region_id_max));
  normalized->spawn_rate = std::max(0.0, out->spawn_rate);
  normalized->lifetime_min = std::max(0.0, out->lifetime_min);
  normalized->lifetime_max = std::max(0.0, out->lifetime_max);
  normalized->speed_min = std::max(0.0, out->speed_min);
  normalized->speed_max = std::max(0.0, out->speed_max);
  normalized->scale_min = std::max(0.0, out->scale_min);
  normalized->scale_max = std::max(0.0, out->scale_max);
  normalized->emitter_cone_angle = std::max(0.0, out->emitter_cone_angle);
  normalized->emitter_depth = std::max(0.0, out->emitter_depth);
  normalized->emitter_radius = std::max(0.0, out->emitter_radius);
  normalized->emitter_width = std::max(0.0, out->emitter_width);
  normalized->emitter_height = std::max(0.0, out->emitter_height);
  return normalized;
}

inline void report_curve(flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> issues,
                         std::optional<flight::Array<double>> curve, flight::String field,
                         double stride) {
  if (!curve.has_value()) return;
  if (curve->empty()) {
    validate_particle_emitter_config_detail::append_issue(
        issues, field, field + flight::String(" is empty and will be ignored"), flight::String("warning"));
    return;
  }
  if (std::fmod(static_cast<double>(curve->size()), stride) != 0.0) {
    validate_particle_emitter_config_detail::append_issue(
        issues, field,
        field + flight::String(" length (") + flight::to_string(static_cast<double>(curve->size())) +
            flight::String(") is not a multiple of ") + flight::to_string(stride),
        flight::String("warning"));
  }
  for (double i = 0.0; i < static_cast<double>(curve->size()); i += 1.0) {
    if (!std::isfinite(curve->element(i))) {
      validate_particle_emitter_config_detail::append_issue(
          issues, field,
          field + flight::String(" contains a non-finite sample at index ") + flight::to_string(i),
          flight::String("error"));
      break;
    }
  }
}

inline void report_inverted_range(
    flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> issues,
    flight::Ref<flight::types::ParticleEmitterConfig> config, flight::String min_field,
    flight::String max_field) {
  const double min = validate_particle_emitter_config_detail::numeric_field(config, min_field);
  const double max = validate_particle_emitter_config_detail::numeric_field(config, max_field);
  if (std::isfinite(min) && std::isfinite(max) && min > max) {
    validate_particle_emitter_config_detail::append_issue(
        issues, min_field,
        min_field + flight::String(" (") + flight::to_string(min) + flight::String(") is greater than ") +
            max_field + flight::String(" (") + flight::to_string(max) + flight::String(")"),
        flight::String("warning"));
  }
}

inline void report_unit_range(flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> issues,
                              flight::Ref<flight::types::ParticleEmitterConfig> config,
                              flight::String field) {
  const double value = validate_particle_emitter_config_detail::numeric_field(config, field);
  if (std::isfinite(value) && (value < 0.0 || value > 1.0)) {
    validate_particle_emitter_config_detail::append_issue(
        issues, field,
        field + flight::String(" (") + flight::to_string(value) +
            flight::String(") is outside the expected 0–1 range"),
        flight::String("warning"));
  }
}

inline flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> validate_particle_emitter_config(
    flight::Ref<flight::types::ParticleEmitterConfig> config) {
  flight::Array<flight::Ref<flight::types::ParticleConfigIssue>> issues;

  for (double i = 0.0; i < static_cast<double>(numeric_fields.size()); i += 1.0) {
    const auto field = numeric_fields.element(i);
    const double value = validate_particle_emitter_config_detail::numeric_field(config, field);
    if (!std::isfinite(value)) {
      validate_particle_emitter_config_detail::append_issue(
          issues, field,
          field + flight::String(" must be a finite number (got ") + flight::to_string(value) +
              flight::String(")"),
          flight::String("error"));
    }
  }

  for (double i = 0.0; i < static_cast<double>(non_negative_fields.size()); i += 1.0) {
    const auto field = non_negative_fields.element(i);
    const double value = validate_particle_emitter_config_detail::numeric_field(config, field);
    if (std::isfinite(value) && value < 0.0) {
      validate_particle_emitter_config_detail::append_issue(
          issues, field,
          field + flight::String(" must not be negative (got ") + flight::to_string(value) +
              flight::String(")"),
          flight::String("warning"));
    }
  }

  // A non-positive maximum lifetime means particles die the frame they spawn.
  if (std::isfinite(config->lifetime_max) && config->lifetime_max <= 0.0) {
    validate_particle_emitter_config_detail::append_issue(
        issues, flight::String("lifetimeMax"),
        flight::String("lifetimeMax must be > 0 or particles die instantly"), flight::String("warning"));
  }
  // A non-positive cap means the emitter can never hold a particle.
  if (std::isfinite(config->max_particles) && config->max_particles <= 0.0) {
    validate_particle_emitter_config_detail::append_issue(
        issues, flight::String("maxParticles"),
        flight::String("maxParticles must be >= 1 or nothing ever spawns"), flight::String("warning"));
  }
  if (std::isfinite(config->frame_count) && config->frame_count < 1.0) {
    validate_particle_emitter_config_detail::append_issue(
        issues, flight::String("frameCount"), flight::String("frameCount must be >= 1"),
        flight::String("warning"));
  }

  // Inverted min/max ranges still simulate (the spawn interpolation handles a > b)
  // but almost always indicate an authoring mistake.
  report_inverted_range(issues, config, flight::String("lifetimeMin"), flight::String("lifetimeMax"));
  report_inverted_range(issues, config, flight::String("speedMin"), flight::String("speedMax"));
  report_inverted_range(issues, config, flight::String("scaleMin"), flight::String("scaleMax"));
  report_inverted_range(issues, config, flight::String("rotationSpeedMin"),
                        flight::String("rotationSpeedMax"));

  report_unit_range(issues, config, flight::String("alphaStart"));
  report_unit_range(issues, config, flight::String("alphaEnd"));

  report_curve(issues, config->alpha_curve, flight::String("alphaCurve"), 1.0);
  report_curve(issues, config->color_curve, flight::String("colorCurve"), 3.0);
  report_curve(issues, config->scale_curve, flight::String("scaleCurve"), 1.0);

  return issues;
}


// NOT GENERATED: function normalizeParticleEmitterConfig -- source line 83
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   export function normalizeParticleEmitterConfig(config?: Partial<ParticleEmitterConfig>): ParticleEmitterConfig {
//     const out = createParticleEmitterConfig(config);
//     const defaults = createParticleEmitterConfig();
//
//     // Replace any non-finite numeric field with its canonical default.
//     const mutable = out as unknown as Record<string, number>;
//     const defaultsRec = defaults as unknown as Record<string, number>;
//     for (const field of NUMERIC_FIELDS) {
//       if (!Number.isFinite(mutable[field])) mutable[field] = defaultsRec[field];
//     }
//
//     return {
//       ...out,
//       // Drop any curve that is empty or contains a non-finite sample so it can never
//       // inject NaN — the simulation falls back to its linear interpolation path.
//       alphaCurve: isFiniteCurve(out.alphaCurve) ? out.alphaCurve : null,
//       colorCurve: isFiniteCurve(out.colorCurve) ? out.colorCurve : null,
//       scaleCurve: isFiniteCurve(out.scaleCurve) ? out.scaleCurve : null,
//       maxParticles: Math.max(0, Math.floor(out.maxParticles)),
//       burstCount: Math.max(0, Math.floor(out.burstCount)),
//       burstInterval: Math.max(0, out.burstInterval),
//       duration: Math.max(0, out.duration),
//       frameCount: Math.max(1, Math.floor(out.frameCount)),
//       frameRate: Math.max(0, out.frameRate),
//       regionIdMin: Math.max(0, Math.floor(out.regionIdMin)),
//       regionIdMax: Math.max(Math.max(0, Math.floor(out.regionIdMin)), Math.floor(out.regionIdMax)),
//       spawnRate: Math.max(0, out.spawnRate),
//       lifetimeMin: Math.max(0, out.lifetimeMin),
//       lifetimeMax: Math.max(0, out.lifetimeMax),
//       speedMin: Math.max(0, out.speedMin),
//       speedMax: Math.max(0, out.speedMax),
//       scaleMin: Math.max(0, out.scaleMin),
//       scaleMax: Math.max(0, out.scaleMax),
//       emitterConeAngle: Math.max(0, out.emitterConeAngle),
//       emitterDepth: Math.max(0, out.emitterDepth),
//       emitterRadius: Math.max(0, out.emitterRadius),
//       emitterWidth: Math.max(0, out.emitterWidth),
//       emitterHeight: Math.max(0, out.emitterHeight),
//     };
//   }
//
//   /** Report problems in a particle config without modifying it — for asset-import
//    *  validation, editor inspectors, or CI checks on authored effects. Returns an
//    *  empty array for a clean config. Use {@link normalizeParticleEmitterConfig} to
//    *  get a corrected config for safe runtime use. */
// cpp emission failed for @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts:
// Partial<T> requires a statically resolvable C++ object shape; T is named


// NOT GENERATED: function reportCurve -- source line 190
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function reportCurve(
//     issues: ParticleConfigIssue[],
//     curve: ReadonlyArray<number> | null,
//     field: string & keyof ParticleEmitterConfig,
//     stride: number,
//   ): void {
//     if (curve == null) return;
//     if (curve.length === 0) {
//       issues.push({ field, message: `${field} is empty and will be ignored`, severity: 'warning' });
//       return;
//     }
//     if (curve.length % stride !== 0) {
//       issues.push({
//         field,
//         message: `${field} length (${curve.length}) is not a multiple of ${stride}`,
//         severity: 'warning',
//       });
//     }
//     for (let i = 0; i < curve.length; i++) {
//       if (!Number.isFinite(curve[i])) {
//         issues.push({ field, message: `${field} contains a non-finite sample at index ${i}`, severity: 'error' });
//         break;
//       }
//     }
//   }
//
// cpp emission failed for @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts:
// intersection types require C++ multiple-inheritance lowering: no shape for primitive, keyof. Declare the
// object shape the code reads rather than intersecting a conjunct that has none


// NOT GENERATED: function reportInvertedRange -- source line 216
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function reportInvertedRange(
//     issues: ParticleConfigIssue[],
//     config: Readonly<ParticleEmitterConfig>,
//     minField: string & keyof ParticleEmitterConfig,
//     maxField: string & keyof ParticleEmitterConfig,
//   ): void {
//     const min = config[minField];
//     const max = config[maxField];
//     if (Number.isFinite(min) && Number.isFinite(max) && (min as number) > (max as number)) {
//       issues.push({
//         field: minField,
//         message: `${minField} (${min}) is greater than ${maxField} (${max})`,
//         severity: 'warning',
//       });
//     }
//   }
//
// cpp emission failed for @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts:
// intersection types require C++ multiple-inheritance lowering: no shape for primitive, keyof. Declare the
// object shape the code reads rather than intersecting a conjunct that has none


// NOT GENERATED: function reportUnitRange -- source line 233
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function reportUnitRange(
//     issues: ParticleConfigIssue[],
//     config: Readonly<ParticleEmitterConfig>,
//     field: string & keyof ParticleEmitterConfig,
//   ): void {
//     const value = config[field];
//     if (Number.isFinite(value) && ((value as number) < 0 || (value as number) > 1)) {
//       issues.push({ field, message: `${field} (${value}) is outside the expected 0–1 range`, severity: 'warning' });
//     }
//   }
//
// cpp emission failed for @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts:
// intersection types require C++ multiple-inheritance lowering: no shape for primitive, keyof. Declare the
// object shape the code reads rather than intersecting a conjunct that has none


// NOT GENERATED: function validateParticleEmitterConfig -- source line 128
// refusal: cpp-closed-key-access-without-object-storage [compiler-restriction]
//
// The source it stood for:
//   export function validateParticleEmitterConfig(config: Readonly<ParticleEmitterConfig>): ParticleConfigIssue[] {
//     const issues: ParticleConfigIssue[] = [];
//
//     for (const field of NUMERIC_FIELDS) {
//       const value = config[field];
//       if (!Number.isFinite(value)) {
//         issues.push({ field, message: `${field} must be a finite number (got ${String(value)})`, severity: 'error' });
//       }
//     }
//
//     for (const field of NON_NEGATIVE_FIELDS) {
//       const value = config[field];
//       if (Number.isFinite(value) && value < 0) {
//         issues.push({ field, message: `${field} must not be negative (got ${value})`, severity: 'warning' });
//       }
//     }
//
//     // A non-positive maximum lifetime means particles die the frame they spawn.
//     if (Number.isFinite(config.lifetimeMax) && config.lifetimeMax <= 0) {
//       issues.push({
//         field: 'lifetimeMax',
//         message: 'lifetimeMax must be > 0 or particles die instantly',
//         severity: 'warning',
//       });
//     }
//     // A non-positive cap means the emitter can never hold a particle.
//     if (Number.isFinite(config.maxParticles) && config.maxParticles <= 0) {
//       issues.push({
//         field: 'maxParticles',
//         message: 'maxParticles must be >= 1 or nothing ever spawns',
//         severity: 'warning',
//       });
//     }
//     if (Number.isFinite(config.frameCount) && config.frameCount < 1) {
//       issues.push({ field: 'frameCount', message: 'frameCount must be >= 1', severity: 'warning' });
//     }
//
//     // Inverted min/max ranges still simulate (the spawn interpolation handles a > b)
//     // but almost always indicate an authoring mistake.
//     reportInvertedRange(issues, config, 'lifetimeMin', 'lifetimeMax');
//     reportInvertedRange(issues, config, 'speedMin', 'speedMax');
//     reportInvertedRange(issues, config, 'scaleMin', 'scaleMax');
//     reportInvertedRange(issues, config, 'rotationSpeedMin', 'rotationSpeedMax');
//
//     reportUnitRange(issues, config, 'alphaStart');
//     reportUnitRange(issues, config, 'alphaEnd');
//
//     reportCurve(issues, config.alphaCurve, 'alphaCurve', 1);
//     reportCurve(issues, config.colorCurve, 'colorCurve', 3);
//     reportCurve(issues, config.scaleCurve, 'scaleCurve', 1);
//
//     return issues;
//   }
//
// cpp emission failed for @flighthq/particles/packages/particles/src/validateParticleEmitterConfig.ts:
// closed-key element access over Readonly<ParticleEmitterConfig> requires represented object storage: the finite
// key set proves which members may be selected, but the receiver does not retain one exact flight::Ref owner
// whose shape defines those members. Accept a concrete declared object type at this boundary (or a Record when
// keyed storage is intended); the compiler will not cast, copy, or materialize an owner to make the access
// possible

} // namespace flight::particles
