// Generated by @flighthq/tool-compiler from @flighthq/camera/packages/camera/src/frustumCorners.ts#FrustumCorners at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct Camera3D; }
namespace flight::types { struct Entity; }
namespace flight::types { struct Matrix4; }
namespace flight::types { struct Vector3; }

#include <flight/geometry/matrix4.hpp>
#include <flight/types/camera3_d.hpp>
#include <flight/types/entity.hpp>
#include <flight/types/matrix4.hpp>
#include <flight/types/vector3.hpp>
#include <flight/camera/camera.hpp>

namespace flight::camera {

inline flight::Ref<flight::types::Matrix4> scratch_view_projection_flight_value_variable__u00005f__u00005f_scratch_u000056_iew_u000050_rojection_flight_private_cc5695174ab66e2b = flight::geometry::create_matrix4(std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt);

inline flight::Ref<flight::types::Matrix4> scratch_inverse_vp_flight_value_variable__u00005f__u00005f_scratch_u000049_nverse_u000056__u000050__flight_private_cc5695174ab66e2b = flight::geometry::create_matrix4(std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt);

inline bool get_camera3_dfrustum_corners(flight::Array<flight::types::Vector3Like> out, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Camera3D>>>> camera, double aspect) {
  flight::camera::get_camera3_dview_projection_matrix4(scratch_view_projection_flight_value_variable__u00005f__u00005f_scratch_u000056_iew_u000050_rojection_flight_private_cc5695174ab66e2b, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Camera3D>>>>>(camera), aspect);
  if (!flight::geometry::inverse_matrix4(scratch_inverse_vp_flight_value_variable__u00005f__u00005f_scratch_u000049_nverse_u000056__u000050__flight_private_cc5695174ab66e2b, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::types::Matrix4Like>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<flight::types::Matrix4>>>>(scratch_view_projection_flight_value_variable__u00005f__u00005f_scratch_u000056_iew_u000050_rojection_flight_private_cc5695174ab66e2b)))) {
    return false;
  }
  flight::Float32Array m = scratch_inverse_vp_flight_value_variable__u00005f__u00005f_scratch_u000049_nverse_u000056__u000050__flight_private_cc5695174ab66e2b->m;
  flight::Array<flight::Array<double>> ndc_corners = flight::Array<flight::Array<double>>{flight::Array<double>{-1.0, -1.0, -1.0}, flight::Array<double>{1.0, -1.0, -1.0}, flight::Array<double>{-1.0, 1.0, -1.0}, flight::Array<double>{1.0, 1.0, -1.0}, flight::Array<double>{-1.0, -1.0, 1.0}, flight::Array<double>{1.0, -1.0, 1.0}, flight::Array<double>{-1.0, 1.0, 1.0}, flight::Array<double>{1.0, 1.0, 1.0}};
  flight::Array<flight::Array<double>> results = flight::Array<flight::Array<double>>{};
  {
    double i = 0.0;
    while ((i < 8.0)) {
      {
        flight::Array<double> array_pattern_value = ndc_corners.element(i);
        const double nx = array_pattern_value.element(0.0);
        const double ny = array_pattern_value.element(1.0);
        const double nz = array_pattern_value.element(2.0);
        double wx = ((((m.get_index(0.0) * nx) + (m.get_index(4.0) * ny)) + (m.get_index(8.0) * nz)) + m.get_index(12.0));
        double wy = ((((m.get_index(1.0) * nx) + (m.get_index(5.0) * ny)) + (m.get_index(9.0) * nz)) + m.get_index(13.0));
        double wz = ((((m.get_index(2.0) * nx) + (m.get_index(6.0) * ny)) + (m.get_index(10.0) * nz)) + m.get_index(14.0));
        const double ww = ((((m.get_index(3.0) * nx) + (m.get_index(7.0) * ny)) + (m.get_index(11.0) * nz)) + m.get_index(15.0));
        if ((ww != 0.0)) {
          const double inv_w = (1.0 / ww);
          (wx *= inv_w);
          (wy *= inv_w);
          (wz *= inv_w);
        }
        results.push(flight::Array<double>{wx, wy, wz});
      }
      (i += 1.0);
    }
  }
  {
    double i_2 = 0.0;
    while ((i_2 < 8.0)) {
      {
        // OVERRIDE: `->` for `.`, three times, and that is the whole modification.
        //
        // `out` is flight::Array<flight::types::Vector3Like>, and Vector3Like is
        // `flight::Ref<Vector3>` -- a std::shared_ptr<Vector3>. The TypeScript is
        // `out[i].x = results[i][0]`, a member assignment THROUGH a reference, and the emitter wrote it
        // as a direct member access on the element: `out.element(i_2).x`, which is
        // "'std::shared_ptr<flight::types::Vector3>' has no member named 'x'".
        //
        // Array::element returns a reference to the stored shared_ptr, so `->x = v` assigns through to
        // the pointee -- the same object the caller handed in, mutated in place, which is exactly what
        // the TypeScript does to the array it was passed. Nothing else in the function changes.
        (out.element(i_2)->x = results.element(i_2).element(0.0));
        (out.element(i_2)->y = results.element(i_2).element(1.0));
        (out.element(i_2)->z = results.element(i_2).element(2.0));
      }
      (i_2 += 1.0);
    }
  }
  return true;
}

} // namespace flight::camera
