// Generated by @flighthq/tool-compiler from @flighthq/notification/packages/notification/src/notification.ts#Notification at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function createNotificationSubscription -- source line 346
//   missing: function attachNotificationSubscription -- source line 362
//   missing: function disposeNotificationSubscription -- source line 433
#include <coroutine>
#include <flight/weak_map.hpp>
#include <flight/weak_set.hpp>
#include <functional>
#include <optional>
#include <tuple>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/signal.hpp>

#include <flight/types/entity.hpp>

#include <flight/signals/emitter.hpp>

#include <flight/signals/signal.hpp>

#include <flight/types/notification.hpp>

#include <flight/entity/entity.hpp>

namespace flight::notification {

using flight::types::NotificationEventReleaseOutcome;

using flight::types::Entity;
using flight::types::EntityConstruction;
using flight::types::HostNotificationActionCapability;
using flight::types::HostNotificationActiveListCapability;
using flight::types::HostNotificationClickCapability;
using flight::types::HostNotificationCloseCapability;
using flight::types::HostNotificationDeliveryCapability;
using flight::types::HostNotificationDismissCapability;
using flight::types::HostNotificationLifecycleCapability;
using flight::types::HostNotificationPermissionCapability;
using flight::types::HostNotificationReceivedCapability;
using flight::types::HostNotificationReplyCapability;
using flight::types::HostNotificationSchedulingCapability;
using flight::types::Notification;
using flight::types::NotificationActionSubscription;
using flight::types::NotificationActiveListOutcome;
using flight::types::NotificationCancelOutcome;
using flight::types::NotificationClickSubscription;
using flight::types::NotificationCloseOutcome;
using flight::types::NotificationDeliveryOutcome;
using flight::types::NotificationDismissSubscription;
using flight::types::NotificationEventAttachment;
using flight::types::NotificationEventBackendAttachOutcome;
using flight::types::NotificationPendingListOutcome;
using flight::types::NotificationPermissionQueryOutcome;
using flight::types::NotificationPermissionRequestOutcome;
using flight::types::NotificationReceivedSubscription;
using flight::types::NotificationReplySubscription;
using flight::types::NotificationRequest;
using flight::types::NotificationSchedule;
using flight::types::NotificationScheduleOutcome;
using flight::types::NotificationSubscriptionAttachOutcome;
using flight::types::NotificationSubscriptionDetachOutcome;
using flight::types::NotificationSubscriptionDisposeOutcome;
using flight::types::ScheduledNotification;
using flight::types::Signal;

using flight::signals::emit_signal;

using flight::signals::create_signal;

using flight::types::NotificationLifecycleOutcome;

using flight::entity::allocate_entity;
using flight::entity::finish_entity;

struct NotificationSubscriptionRuntime;

inline flight::Task<flight::Ref<NotificationLifecycleOutcome>> close_all_notifications(flight::Ref<HostNotificationCloseCapability> host_notification_close) {
  return host_notification_close->close_all_notifications();
}

inline flight::Task<flight::Ref<NotificationLifecycleOutcome>> destroy_notification_capabilities(flight::Ref<HostNotificationLifecycleCapability> host_notification_lifecycle) {
  return host_notification_lifecycle->destroy();
}

inline flight::Task<flight::Ref<NotificationActiveListOutcome>> get_active_notifications(flight::Ref<HostNotificationActiveListCapability> host_notification_active_list) {
  return host_notification_active_list->get_active_notifications();
}

inline flight::Task<flight::Ref<NotificationPermissionQueryOutcome>> get_notification_permission(flight::Ref<HostNotificationPermissionCapability> host_notification_permission) {
  return host_notification_permission->get_permission();
}

inline flight::Task<flight::Ref<NotificationPendingListOutcome>> get_pending_notifications(flight::Ref<HostNotificationSchedulingCapability> host_notification_scheduling) {
  return host_notification_scheduling->get_pending_notifications();
}

inline void initialize_notification_resource(flight::Ref<EntityConstruction<flight::Ref<Notification>>> out, flight::String id, flight::String title, std::optional<flight::String> tag = std::nullopt) {
  tag = tag.value_or(flight::String(""));
  (out->id = id);
  (out->tag = tag.value());
  (out->title = title);
}

inline flight::Ref<Notification> create_notification_resource(flight::String id, flight::String title, std::optional<flight::String> tag = std::nullopt) {
  tag = tag.value_or(flight::String(""));
  flight::Ref<EntityConstruction<flight::Ref<Notification>>> out = allocate_entity<flight::Ref<Notification>>();
  initialize_notification_resource(out, id, title, tag.value());
  return finish_entity(out);
}

inline void initialize_scheduled_notification_resource(flight::Ref<EntityConstruction<flight::Ref<ScheduledNotification>>> out, flight::String id, flight::Ref<NotificationRequest> request, flight::Ref<NotificationSchedule> schedule) {
  (out->id = id);
  (out->request = request);
  (out->schedule = schedule);
}

inline flight::Ref<ScheduledNotification> create_scheduled_notification_resource(flight::String id, flight::Ref<NotificationRequest> request, flight::Ref<NotificationSchedule> schedule) {
  flight::Ref<EntityConstruction<flight::Ref<ScheduledNotification>>> out = allocate_entity<flight::Ref<ScheduledNotification>>();
  initialize_scheduled_notification_resource(out, id, request, schedule);
  return finish_entity(out);
}

inline flight::Task<flight::Ref<NotificationPermissionRequestOutcome>> request_notification_permission(flight::Ref<HostNotificationPermissionCapability> host_notification_permission) {
  return host_notification_permission->request_permission();
}

inline flight::Task<flight::Ref<NotificationScheduleOutcome>> schedule_notification(flight::Ref<HostNotificationSchedulingCapability> host_notification_scheduling, flight::Ref<NotificationRequest> request, flight::Ref<NotificationSchedule> schedule) {
  return host_notification_scheduling->schedule_notification(request, schedule);
}

inline flight::Task<flight::Ref<NotificationDeliveryOutcome>> show_notification(flight::Ref<HostNotificationDeliveryCapability> host_notification_delivery, flight::Ref<NotificationRequest> request) {
  return host_notification_delivery->notify(request);
}

template <typename TArgs>
using NotificationAttach = std::function<flight::Task<flight::Ref<NotificationEventBackendAttachOutcome>>(std::function<void(TArgs)>)>;

struct NotificationSubscriptionRuntime : public flight::ReferenceEnabled {
  std::optional<flight::Ref<NotificationEventAttachment>> attachment;
  bool dispose_completed;
  bool disposed;
  double generation;
  std::optional<flight::Task<flight::Ref<NotificationEventBackendAttachOutcome>>> pending;
};

inline flight::Task<flight::Ref<NotificationEventReleaseOutcome>> release_notification_attachment(flight::Ref<NotificationEventAttachment> attachment) {
  try {
    co_return co_await attachment->release();
  }
  catch (...) {
    co_return flight::make_ref<NotificationEventReleaseOutcome>(NotificationEventReleaseOutcome{.reason = flight::String("operation-failed")});
  }
}

inline flight::WeakMap<flight::Ref<Notification>, std::function<flight::Task<flight::Ref<NotificationCloseOutcome>>()>> notification_close = flight::WeakMap<flight::Ref<Notification>, std::function<flight::Task<flight::Ref<NotificationCloseOutcome>>()>>();

inline void bind_notification_close(flight::Ref<Notification> notification, std::function<flight::Task<flight::Ref<NotificationCloseOutcome>>()> close) {
  notification_close.set(notification, close);
}

inline flight::WeakSet<flight::Ref<Notification>> closed_notifications = flight::WeakSet<flight::Ref<Notification>>();

inline flight::Task<flight::Ref<NotificationCloseOutcome>> close_notification(flight::Ref<Notification> notification) {
  if (closed_notifications.has(notification)) {
    co_return flight::make_ref<NotificationCloseOutcome>(NotificationCloseOutcome{.reason = flight::String("already-closed")});
  }
  std::optional<std::function<flight::Task<flight::Ref<NotificationCloseOutcome>>()>> close = notification_close.get(notification);
  if (!close.has_value()) {
    co_return flight::make_ref<NotificationCloseOutcome>(NotificationCloseOutcome{.reason = flight::String("operation-failed")});
  }
  flight::Ref<NotificationCloseOutcome> outcome;
  try {
    (outcome = co_await close.value()());
  }
  catch (...) {
    (outcome = flight::make_ref<NotificationCloseOutcome>(NotificationCloseOutcome{.reason = flight::String("operation-failed")}));
  }
  if (((outcome->reason == flight::String("ok")) || (outcome->reason == flight::String("already-closed")))) {
    notification_close.erase(notification);
    closed_notifications.add(notification);
  }
  co_return outcome;
}

inline flight::WeakMap<flight::Ref<ScheduledNotification>, std::function<flight::Task<flight::Ref<NotificationCancelOutcome>>()>> scheduled_notification_cancel = flight::WeakMap<flight::Ref<ScheduledNotification>, std::function<flight::Task<flight::Ref<NotificationCancelOutcome>>()>>();

inline void bind_scheduled_notification_cancel(flight::Ref<ScheduledNotification> scheduled, std::function<flight::Task<flight::Ref<NotificationCancelOutcome>>()> cancel) {
  scheduled_notification_cancel.set(scheduled, cancel);
}

inline flight::WeakSet<flight::Ref<ScheduledNotification>> cancelled_scheduled_notifications = flight::WeakSet<flight::Ref<ScheduledNotification>>();

inline flight::Task<flight::Ref<NotificationCancelOutcome>> cancel_scheduled_notification(flight::Ref<ScheduledNotification> scheduled) {
  if (cancelled_scheduled_notifications.has(scheduled)) {
    co_return flight::make_ref<NotificationCancelOutcome>(NotificationCancelOutcome{.reason = flight::String("already-cancelled")});
  }
  std::optional<std::function<flight::Task<flight::Ref<NotificationCancelOutcome>>()>> cancel = scheduled_notification_cancel.get(scheduled);
  if (!cancel.has_value()) {
    co_return flight::make_ref<NotificationCancelOutcome>(NotificationCancelOutcome{.reason = flight::String("operation-failed")});
  }
  flight::Ref<NotificationCancelOutcome> outcome;
  try {
    (outcome = co_await cancel.value()());
  }
  catch (...) {
    (outcome = flight::make_ref<NotificationCancelOutcome>(NotificationCancelOutcome{.reason = flight::String("operation-failed")}));
  }
  if (((outcome->reason == flight::String("ok")) || (outcome->reason == flight::String("already-cancelled")))) {
    scheduled_notification_cancel.erase(scheduled);
    cancelled_scheduled_notifications.add(scheduled);
  }
  co_return outcome;
}

inline flight::WeakMap<flight::Ref<Entity>, flight::Ref<NotificationSubscriptionRuntime>> notification_subscriptions = flight::WeakMap<flight::Ref<Entity>, flight::Ref<NotificationSubscriptionRuntime>>();


// NOT GENERATED: function createNotificationSubscription -- source line 346
//
// The source it stood for:
//   function createNotificationSubscription<TSubscription extends Entity>(
//     fields: Omit<TSubscription, keyof Entity>,
//   ): TSubscription {
//     const subscription = allocateEntity<TSubscription>();
//     Object.assign(subscription, fields);
//     finishEntity(subscription);
//     _notificationSubscriptions.set(subscription, {
//       attachment: null,
//       disposeCompleted: false,
//       disposed: false,
//       generation: 0,
//       pending: null,
//     });
//     return subscription;
//   }
//   
// cpp emission failed for @flighthq/notification/packages/notification/src/notification.ts: Omit<T, K> requires
// a proven reference-preserving flight-cpp representation

inline flight::Ref<NotificationActionSubscription> create_notification_action_subscription() {
  auto out = allocate_entity<flight::Ref<NotificationActionSubscription>>();
  out->on_notification_action = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_notification_action)>::element_type>>();
  return finish_entity<flight::Ref<NotificationActionSubscription>>(out);
}

inline flight::Ref<NotificationClickSubscription> create_notification_click_subscription() {
  auto out = allocate_entity<flight::Ref<NotificationClickSubscription>>();
  out->on_notification_click = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_notification_click)>::element_type>>();
  return finish_entity<flight::Ref<NotificationClickSubscription>>(out);
}

inline flight::Ref<NotificationDismissSubscription> create_notification_dismiss_subscription() {
  auto out = allocate_entity<flight::Ref<NotificationDismissSubscription>>();
  out->on_notification_dismiss = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_notification_dismiss)>::element_type>>();
  return finish_entity<flight::Ref<NotificationDismissSubscription>>(out);
}

inline flight::Ref<NotificationReceivedSubscription> create_notification_received_subscription() {
  auto out = allocate_entity<flight::Ref<NotificationReceivedSubscription>>();
  out->on_notification_received = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_notification_received)>::element_type>>();
  return finish_entity<flight::Ref<NotificationReceivedSubscription>>(out);
}

inline flight::Ref<NotificationReplySubscription> create_notification_reply_subscription() {
  auto out = allocate_entity<flight::Ref<NotificationReplySubscription>>();
  out->on_notification_reply = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_notification_reply)>::element_type>>();
  return finish_entity<flight::Ref<NotificationReplySubscription>>(out);
}

template <typename Subscription>
inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_subscription(
    std::shared_ptr<Subscription>) {
  co_return NotificationSubscriptionDetachOutcome{
      std::in_place_index<1>,
      flight::make_ref<flight::types::reason_43a745d20647bfb6>(
          flight::types::reason_43a745d20647bfb6{.reason = flight::String("not-attached")})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_action_subscription(flight::Ref<NotificationActionSubscription> subscription) {
  return detach_notification_subscription(subscription);
}

inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_click_subscription(flight::Ref<NotificationClickSubscription> subscription) {
  return detach_notification_subscription(subscription);
}

inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_dismiss_subscription(flight::Ref<NotificationDismissSubscription> subscription) {
  return detach_notification_subscription(subscription);
}

inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_received_subscription(flight::Ref<NotificationReceivedSubscription> subscription) {
  return detach_notification_subscription(subscription);
}

inline flight::Task<flight::Ref<NotificationSubscriptionDetachOutcome>> detach_notification_reply_subscription(flight::Ref<NotificationReplySubscription> subscription) {
  return detach_notification_subscription(subscription);
}


// NOT GENERATED: function attachNotificationSubscription -- source line 362
//
// The source it stood for:
//   async function attachNotificationSubscription<TSubscription extends Entity, TArgs extends unknown[]>(
//     subscription: TSubscription,
//     attach: NotificationAttach<TArgs>,
//     listener: (...args: TArgs) => void,
//   ): Promise<NotificationSubscriptionAttachOutcome> {
//     const runtime = _notificationSubscriptions.get(subscription);
//     if (runtime === undefined || runtime.disposed) {
//       return {
//         attachFailed: true,
//         reason: 'operation-failed',
//         releaseFailed: false,
//       };
//     }
//     const detached = await detachNotificationSubscription(subscription);
//     if (detached.reason === 'operation-failed') {
//       return {
//         attachFailed: false,
//         reason: 'operation-failed',
//         releaseFailed: true,
//       };
//     }
//     const generation = ++runtime.generation;
//     let pending: Promise<NotificationEventBackendAttachOutcome>;
//     try {
//       pending = attach(listener);
//     } catch {
//       return {
//         attachFailed: true,
//         reason: 'operation-failed',
//         releaseFailed: false,
//       };
//     }
//     runtime.pending = pending;
//     let outcome: NotificationEventBackendAttachOutcome;
//     try {
//       outcome = await pending;
//     } catch {
//       outcome = { reason: 'operation-failed', releaseFailed: false };
//     }
//     if (runtime.pending === pending) runtime.pending = null;
//     if (outcome.reason === 'operation-failed') {
//       return {
//         attachFailed: true,
//         reason: 'operation-failed',
//         releaseFailed: outcome.releaseFailed,
//       };
//     }
//     if (runtime.disposed || runtime.generation !== generation) {
//       const release = await releaseNotificationAttachment(outcome.attachment);
//       return release.reason === 'ok'
//         ? { reason: 'ok' }
//         : {
//             attachFailed: false,
//             reason: 'operation-failed',
//             releaseFailed: true,
//           };
//     }
//     runtime.attachment = outcome.attachment;
//     return { reason: 'ok' };
//   }
//   
// cpp emission failed for @flighthq/notification/packages/notification/src/notification.ts: union member test
// requires a C++ variant binding

inline flight::Task<flight::Ref<NotificationSubscriptionAttachOutcome>> attach_notification_action_subscription(flight::Ref<HostNotificationActionCapability> host_notification_action, flight::Ref<NotificationActionSubscription> subscription) {
  (void)host_notification_action; (void)subscription;
  co_return NotificationSubscriptionAttachOutcome{std::in_place_index<0>, flight::make_ref<flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94>(flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94{.attach_failed = true, .reason = flight::String("operation-failed"), .release_failed = false})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionAttachOutcome>> attach_notification_click_subscription(flight::Ref<HostNotificationClickCapability> host_notification_click, flight::Ref<NotificationClickSubscription> subscription) {
  (void)host_notification_click; (void)subscription;
  co_return NotificationSubscriptionAttachOutcome{std::in_place_index<0>, flight::make_ref<flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94>(flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94{.attach_failed = true, .reason = flight::String("operation-failed"), .release_failed = false})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionAttachOutcome>> attach_notification_dismiss_subscription(flight::Ref<HostNotificationDismissCapability> host_notification_dismiss, flight::Ref<NotificationDismissSubscription> subscription) {
  (void)host_notification_dismiss; (void)subscription;
  co_return NotificationSubscriptionAttachOutcome{std::in_place_index<0>, flight::make_ref<flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94>(flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94{.attach_failed = true, .reason = flight::String("operation-failed"), .release_failed = false})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionAttachOutcome>> attach_notification_received_subscription(flight::Ref<HostNotificationReceivedCapability> host_notification_received, flight::Ref<NotificationReceivedSubscription> subscription) {
  (void)host_notification_received; (void)subscription;
  co_return NotificationSubscriptionAttachOutcome{std::in_place_index<0>, flight::make_ref<flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94>(flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94{.attach_failed = true, .reason = flight::String("operation-failed"), .release_failed = false})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionAttachOutcome>> attach_notification_reply_subscription(flight::Ref<HostNotificationReplyCapability> host_notification_reply, flight::Ref<NotificationReplySubscription> subscription) {
  (void)host_notification_reply; (void)subscription;
  co_return NotificationSubscriptionAttachOutcome{std::in_place_index<0>, flight::make_ref<flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94>(flight::types::attach_failed_reason_release_failed_a670bac8ba62ef94{.attach_failed = true, .reason = flight::String("operation-failed"), .release_failed = false})};
}


// NOT GENERATED: function disposeNotificationSubscription -- source line 433
//
// The source it stood for:
//   async function disposeNotificationSubscription<TArgs extends unknown[]>(
//     subscription: Entity,
//     signal: Signal<(...args: TArgs) => void>,
//   ): Promise<NotificationSubscriptionDisposeOutcome> {
//     const runtime = _notificationSubscriptions.get(subscription);
//     if (runtime === undefined || runtime.disposeCompleted) return { reason: 'already-disposed' };
//     runtime.disposed = true;
//     runtime.generation++;
//     let attachFailed = false;
//     let releaseFailed = false;
//     if (runtime.pending !== null) {
//       let outcome: NotificationEventBackendAttachOutcome;
//       try {
//         outcome = await runtime.pending;
//       } catch {
//         outcome = { reason: 'operation-failed', releaseFailed: false };
//       }
//       if (outcome.reason === 'operation-failed') {
//         attachFailed = true;
//         releaseFailed = outcome.releaseFailed;
//       }
//     }
//     const detached = await detachNotificationSubscription(subscription);
//     if (detached.reason === 'operation-failed') releaseFailed = true;
//     clearSignal(signal);
//     if (attachFailed || releaseFailed) return { attachFailed, reason: 'operation-failed', releaseFailed };
//     runtime.disposeCompleted = true;
//     return { reason: 'ok' };
//   }
//   
// cpp emission failed for @flighthq/notification/packages/notification/src/notification.ts: union member test
// requires a C++ variant binding

inline flight::Task<flight::Ref<NotificationSubscriptionDisposeOutcome>> dispose_notification_action_subscription(flight::Ref<NotificationActionSubscription> subscription) {
  (void)subscription;
  co_return NotificationSubscriptionDisposeOutcome{std::in_place_index<1>, flight::make_ref<flight::types::reason_43a745d20647bfb6>(flight::types::reason_43a745d20647bfb6{.reason = flight::String("already-disposed")})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionDisposeOutcome>> dispose_notification_click_subscription(flight::Ref<NotificationClickSubscription> subscription) {
  (void)subscription;
  co_return NotificationSubscriptionDisposeOutcome{std::in_place_index<1>, flight::make_ref<flight::types::reason_43a745d20647bfb6>(flight::types::reason_43a745d20647bfb6{.reason = flight::String("already-disposed")})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionDisposeOutcome>> dispose_notification_dismiss_subscription(flight::Ref<NotificationDismissSubscription> subscription) {
  (void)subscription;
  co_return NotificationSubscriptionDisposeOutcome{std::in_place_index<1>, flight::make_ref<flight::types::reason_43a745d20647bfb6>(flight::types::reason_43a745d20647bfb6{.reason = flight::String("already-disposed")})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionDisposeOutcome>> dispose_notification_received_subscription(flight::Ref<NotificationReceivedSubscription> subscription) {
  (void)subscription;
  co_return NotificationSubscriptionDisposeOutcome{std::in_place_index<1>, flight::make_ref<flight::types::reason_43a745d20647bfb6>(flight::types::reason_43a745d20647bfb6{.reason = flight::String("already-disposed")})};
}

inline flight::Task<flight::Ref<NotificationSubscriptionDisposeOutcome>> dispose_notification_reply_subscription(flight::Ref<NotificationReplySubscription> subscription) {
  (void)subscription;
  co_return NotificationSubscriptionDisposeOutcome{std::in_place_index<1>, flight::make_ref<flight::types::reason_43a745d20647bfb6>(flight::types::reason_43a745d20647bfb6{.reason = flight::String("already-disposed")})};
}

} // namespace flight::notification
