// Generated by @flighthq/tool-compiler from @flighthq/mesh/packages/mesh/src/meshGeometry.ts#MeshGeometry at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function getMeshGeometryMorphBindPose -- source line 134
//   missing: function getMeshGeometrySkinBindPose -- source line 142
//   missing: function createMeshGeometryRuntime -- source line 205
//   missing: function cloneMeshGeometry -- source line 18
//   missing: function createMeshGeometry -- source line 82
#include <cmath>
#include <cstdint>
#include <flight/boolean.hpp>
#include <functional>
#include <optional>
#include <random>
#include <type_traits>
#include <variant>
#include <flight/weak_map.hpp>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/geometry/aabb.hpp>

#include <flight/types/mesh_skin_bind_pose.hpp>

#include <flight/types/mesh_morph_bind_pose.hpp>

#include <flight/types/mesh_geometry_options.hpp>

#include <flight/types/mesh_geometry.hpp>

#include <flight/types/entity.hpp>

#include <flight/types/aabb.hpp>

namespace flight::mesh {

using flight::geometry::create_aabb;

using flight::types::Aabb;
using flight::types::EntityConstruction;
using flight::types::MeshGeometry;
using flight::types::MeshGeometryOptions;
using flight::types::MeshGeometryRuntime;
using flight::types::MeshMorphBindPose;
using flight::types::MeshSkinBindPose;
using flight::types::MeshSubset;
using flight::types::VertexAttribute;
using flight::types::VertexAttributeLayout;
using flight::types::entity_runtime_key;

inline flight::WeakMap<flight::Ref<MeshGeometry>, flight::Ref<MeshGeometryRuntime>> mesh_geometry_runtimes;

inline std::optional<flight::Ref<MeshGeometryRuntime>> get_mesh_geometry_runtime_if_present(
    const flight::Ref<MeshGeometry>& geometry) {
  auto runtime = mesh_geometry_runtimes.get(geometry);
  if (runtime.has_value() || !geometry->entity_runtime_key.has_value()) return runtime;
  throw flight::Error(flight::String("mesh: the generated EntityRuntime carrier cannot recover MeshGeometryRuntime"));
}

inline void destroy_mesh_geometry_gl_data(flight::Ref<MeshGeometry> geometry) {
  std::optional<flight::Ref<MeshGeometryRuntime>> runtime = get_mesh_geometry_runtime_if_present(geometry);
  if (flight::to_boolean(runtime)) {
    (runtime.value()->webgl_data = nullptr);
  }
}

inline void destroy_mesh_geometry_wgpu_data(flight::Ref<MeshGeometry> geometry) {
  std::optional<flight::Ref<MeshGeometryRuntime>> runtime = get_mesh_geometry_runtime_if_present(geometry);
  if (flight::to_boolean(runtime)) {
    (runtime.value()->webgpu_data = nullptr);
  }
}

inline double get_mesh_geometry_index_count(flight::Ref<MeshGeometry> geometry) {
  return (flight::to_boolean(geometry->indices) ? std::visit([](const auto& value) { return value.size(); }, geometry->indices.value()) : 0.0);
}


// NOT GENERATED: function getMeshGeometryMorphBindPose -- source line 134
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function getMeshGeometryMorphBindPose(geometry: Readonly<MeshGeometry>): MeshMorphBindPose | null {
//     const runtime = geometry[EntityRuntimeKey] as MeshGeometryRuntime | undefined;
//     return runtime ? runtime.morphBindPose : null;
//   }
//   
//   // Returns the CPU-skinning bind pose cached on the geometry's runtime, or null before the first
//   // skin capture. The deform subsystem (skeleton3d/scene) owns this slot; a rigid geometry never
//   // fills it, so plain meshes pay nothing.
// cpp emission failed for @flighthq/mesh/packages/mesh/src/meshGeometry.ts: contextual optionalSingle
// construction requires expression type evidence


// NOT GENERATED: function getMeshGeometrySkinBindPose -- source line 142
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function getMeshGeometrySkinBindPose(geometry: Readonly<MeshGeometry>): MeshSkinBindPose | null {
//     const runtime = geometry[EntityRuntimeKey] as MeshGeometryRuntime | undefined;
//     return runtime ? runtime.skinBindPose : null;
//   }
//   
//   // Returns the number of vertices, derived from the interleaved vertex stream and the layout
//   // stride (stride is in bytes; a Float32 is 4 bytes).
// cpp emission failed for @flighthq/mesh/packages/mesh/src/meshGeometry.ts: contextual optionalSingle
// construction requires expression type evidence

inline bool has_mesh_geometry_skin(flight::Ref<MeshGeometry> geometry) {
  flight::Array<flight::Ref<VertexAttribute>> attributes = geometry->layout->attributes;
  {
    double i = 0.0;
    while ((i < static_cast<double>(attributes.size()))) {
      {
        if ((attributes.element(i)->semantic == flight::String("joints0"))) {
          return true;
        }
      }
      (i += 1.0);
    }
  }
  return false;
}

inline void initialize_mesh_geometry(flight::Ref<EntityConstruction<flight::Ref<MeshGeometry>>> out, flight::Ref<MeshGeometry> fields) {
  (out->bounds = fields->bounds);
  (out->indices = fields->indices);
  (out->layout = fields->layout);
  (out->subsets = fields->subsets);
  (out->topology = fields->topology);
  (out->version = fields->version);
  (out->vertices = fields->vertices);
}

inline void invalidate_mesh_geometry(flight::Ref<MeshGeometry> geometry) {
  (geometry->version = flight::unsigned_right_shift((geometry->version + 1.0), 0.0));
}

inline void set_mesh_geometry_morph_bind_pose(flight::Ref<MeshGeometry> geometry, std::optional<flight::Ref<MeshMorphBindPose>> bind_pose) {
  std::optional<flight::Ref<MeshGeometryRuntime>> runtime = get_mesh_geometry_runtime_if_present(geometry);
  if (flight::to_boolean(runtime)) {
    (runtime.value()->morph_bind_pose = bind_pose);
  }
}

inline void set_mesh_geometry_skin_bind_pose(flight::Ref<MeshGeometry> geometry, std::optional<flight::Ref<MeshSkinBindPose>> bind_pose) {
  std::optional<flight::Ref<MeshGeometryRuntime>> runtime = get_mesh_geometry_runtime_if_present(geometry);
  if (flight::to_boolean(runtime)) {
    (runtime.value()->skin_bind_pose = bind_pose);
  }
}


// NOT GENERATED: function createMeshGeometryRuntime -- source line 205
// refusal: cpp-presence-test-without-absence-storage [compiler-restriction]
//
// The source it stood for:
//   function createMeshGeometryRuntime(fields: Readonly<Omit<MeshGeometry, typeof EntityRuntimeKey>>): MeshGeometry {
//     const geometry = allocateEntity<MeshGeometry>();
//     initializeMeshGeometry(geometry, fields);
//     const runtime: MeshGeometryRuntime = {
//       attributeDataView: null,
//       binding: null,
//       // -1 unless the caller supplied bounds up front: authored bounds are trusted at the version they
//       // were computed for, so ensureMeshGeometryBounds does not re-sweep a geometry that arrived with a
//       // correct box. Anything else recomputes on the first bounds query.
//       boundsVersion: fields.bounds !== null ? fields.version : -1,
//       morphBindPose: null,
//       morphBlendedWeights: null,
//       skinBindPose: null,
//       webglData: null,
//       webgpuData: null,
//     };
//     geometry[EntityRuntimeKey] = runtime;
//     return finishEntity(geometry);
//   }
//   
// cpp emission failed for @flighthq/mesh/packages/mesh/src/meshGeometry.ts: a presence test against null has no
// absence channel in the emitted C++ storage for property


// NOT GENERATED: function cloneMeshGeometry -- source line 18
// refusal: cpp-member-projection-without-present-storage [compiler-restriction]
//
// The source it stood for:
//   export function cloneMeshGeometry(source: Readonly<MeshGeometry>): MeshGeometry {
//     const vertices = new Float32Array(source.vertices.length);
//     vertices.set(source.vertices);
//   
//     let indices: Uint16Array<ArrayBuffer> | Uint32Array<ArrayBuffer> | null = null;
//     if (source.indices) {
//       if (source.indices instanceof Uint32Array) {
//         indices = new Uint32Array(source.indices.length);
//       } else {
//         indices = new Uint16Array(source.indices.length);
//       }
//       indices.set(source.indices);
//     }
//   
//     const subsets: MeshSubset[] = [];
//     for (let i = 0; i < source.subsets.length; i++) {
//       subsets.push({ indexCount: source.subsets[i].indexCount, indexOffset: source.subsets[i].indexOffset });
//     }
//   
//     let bounds = null;
//     if (source.bounds) {
//       const b = source.bounds;
//       bounds = createAabb(b.min.x, b.min.y, b.min.z, b.max.x, b.max.y, b.max.z);
//     }
//   
//     return createMeshGeometryRuntime({
//       bounds: bounds,
//       indices: indices,
//       layout: source.layout,
//       subsets: subsets,
//       topology: source.topology,
//       version: 0,
//       vertices: vertices,
//     });
//   }
//   
// cpp emission failed for @flighthq/mesh/packages/mesh/src/meshGeometry.ts: member set on optional C++ storage
// requires proven present payload: nothing proved the payload present, so the read would unpack storage that may
// be holding absence. Guard the receiver, read it through an optional chain, or narrow it into a present local
// first; the compiler will not call value() without that proof. Where the storage carries BOTH null and
// undefined, a strict test reaches only one of them -- `x !== null` leaves undefined and `x !== undefined`
// leaves null -- so the guard that proves presence is the loose `x != null`, or a local bound from the storage
// and tested the same way

inline flight::Ref<MeshGeometry> clone_mesh_geometry_metadata(flight::Ref<MeshGeometry> source) {
  throw flight::Error(flight::String("mesh: runtime-backed geometry construction is unavailable in this profile"));
}

inline double get_vertex_count_from_layout(flight::Float32Array vertices, flight::Ref<VertexAttributeLayout> layout) {
  const double floats_per_vertex = (layout->stride / 4.0);
  if ((floats_per_vertex <= 0.0)) {
    return 0.0;
  }
  return std::floor((static_cast<double>(vertices.size()) / floats_per_vertex));
}

inline double get_mesh_geometry_vertex_count(flight::Ref<MeshGeometry> geometry) {
  return get_vertex_count_from_layout(geometry->vertices, geometry->layout);
}

inline const double uint16_index_ceiling = 65535.0;

inline std::variant<flight::Uint16Array, flight::Uint32Array> promote_indices(std::variant<flight::Uint16Array, flight::Uint32Array> source, double vertex_count) {
  const auto size = std::visit([](const auto& value) { return value.size(); }, source);
  if (((vertex_count > uint16_index_ceiling) || source.index() == 1)) {
    flight::Uint32Array out = flight::Uint32Array(static_cast<double>(size));
    std::visit([&](const auto& value) {
      for (std::size_t i = 0; i < value.size(); ++i) out.set_index(static_cast<double>(i), value.get_index(static_cast<double>(i)));
    }, source);
    return std::variant<flight::Uint16Array, flight::Uint32Array>{std::in_place_type<flight::Uint32Array>, out};
  }
  flight::Uint16Array out = flight::Uint16Array(static_cast<double>(size));
  std::visit([&](const auto& value) {
    for (std::size_t i = 0; i < value.size(); ++i) out.set_index(static_cast<double>(i), value.get_index(static_cast<double>(i)));
  }, source);
  return std::variant<flight::Uint16Array, flight::Uint32Array>{std::in_place_type<flight::Uint16Array>, out};
}


// NOT GENERATED: function createMeshGeometry -- source line 82
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function createMeshGeometry(options: Readonly<MeshGeometryOptions>): MeshGeometry {
//     const vertices = options.vertices;
//     const vertexCount = getVertexCountFromLayout(vertices, options.layout);
//   
//     let indices: Uint16Array<ArrayBuffer> | Uint32Array<ArrayBuffer> | null = null;
//     if (options.indices) {
//       indices = promoteIndices(options.indices, vertexCount);
//     }
//   
//     let subsets = options.subsets;
//     if (!subsets) {
//       const count = indices ? indices.length : vertexCount;
//       subsets = [{ indexCount: count, indexOffset: 0 }];
//     }
//   
//     return createMeshGeometryRuntime({
//       bounds: null,
//       indices: indices,
//       layout: options.layout,
//       subsets: subsets,
//       topology: options.topology ?? 'triangle-list',
//       version: 0,
//       vertices: vertices,
//     });
//   }
//   
//   // Releases the Gl2 GPU upload slot on a geometry's runtime back to null. The actual GL
//   // objects (VAO/buffers) are owned and freed by scene-gl through the branded concrete shape;
//   // this clears the named slot so the next draw re-uploads. Frees a non-GC GPU resource, hence
//   // destroy*, not dispose*.
// cpp emission failed for @flighthq/mesh/packages/mesh/src/meshGeometry.ts: contextual optionalSingle
// construction requires expression type evidence

} // namespace flight::mesh
