// Generated by @flighthq/tool-compiler from @flighthq/shading/packages/shading/src/registerBuiltInModifiers.ts#RegisterBuiltInModifiers at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the emitter refused five ModifierDefinition bindings after lowering structural source
// assertions as unsupported native reference casts. This override keeps the original row owner and
// reads each asserted interface through a checked readonly partial projection.

#include <functional>
#include <optional>
#include <string_view>

#include <flight/runtime.hpp>
#include <flight/structural_ref.hpp>
#include <flight/types/contract.hpp>
#include <flight/shading/modifier_registry.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2",
              "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::shading {

using ModifierView = flight::StructuralRef<flight::RowReadonly<
    flight::RowOf<flight::Ref<flight::types::Modifier>>>>;
using SignatureFunction = std::function<flight::String(ModifierView)>;

template <typename Specific>
using ModifierPartialView = flight::StructuralRef<flight::RowReadonly<
    flight::RowPartial<flight::RowOf<flight::Ref<Specific>>>>>;

template <typename Specific>
ModifierPartialView<Specific> modifier_partial_view(const ModifierView& modifier) {
  return flight::structural_ref_cast<ModifierPartialView<Specific>>(modifier);
}

inline bool has_defined_property(const ModifierView& modifier, std::string_view name) {
  const auto& owner = modifier.shared_owner();
  if (!owner) return false;
  const auto cell = owner->named_cell(name);
  if (!cell) return false;
  const auto erased = cell->as_any();
  // A value the Any carrier cannot represent is still a present, defined value. In particular,
  // Texture is a variant: an engaged optional<Texture> has no erased reading, while an empty one
  // does erase to undefined.
  return !erased.has_value() || !erased->is_undefined();
}

inline flight::Ref<flight::types::ModifierDefinition> animated_normal_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::animated_normal_modifier_kind,
        .slot = flight::types::modifier_slot->normal,
        .get_define_signature = SignatureFunction{[](ModifierView modifier) {
          const auto animated = modifier_partial_view<flight::types::AnimatedNormalModifier>(modifier);
          const auto map = flight::row_get<flight::RowKey<"map">>(animated);
          // AnimatedNormal.map is required but nullable. A bound, disengaged cell is source null;
          // an entirely absent cell is source undefined and therefore follows the single-layer arm.
          if (animated.shared_owner()->has_named_cell("map") && !map.has_value()) {
            return flight::String("0");
          }
          return flight::row_get<flight::RowKey<"secondaryMap">>(animated).has_value()
                     ? flight::String("2")
                     : flight::String("1");
        }},
    });

inline flight::Ref<flight::types::ModifierDefinition> dissolve_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::dissolve_modifier_kind,
        .slot = flight::types::modifier_slot->effect,
        .get_define_signature = SignatureFunction{[](ModifierView modifier) {
          return has_defined_property(modifier, "map") ? flight::String("m")
                                                        : flight::String("");
        }},
    });

inline flight::Ref<flight::types::ModifierDefinition> emissive_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::emissive_modifier_kind,
        .slot = flight::types::modifier_slot->emissive,
        .get_define_signature = SignatureFunction{[](ModifierView modifier) {
          const auto emissive = modifier_partial_view<flight::types::EmissiveModifier>(modifier);
          flight::String signature;
          if (flight::row_get<flight::RowKey<"mask">>(emissive).has_value()) {
            signature += flight::String("m");
          }
          const auto facing = flight::row_get<flight::RowKey<"facing">>(emissive);
          if (facing.has_value() &&
              facing.value() != flight::types::emissive_modifier_facing->ignore) {
            signature += flight::String("g");
          }
          return signature;
        }},
    });

inline flight::Ref<flight::types::ModifierDefinition> env_reflect_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::env_reflect_modifier_kind,
        .slot = flight::types::modifier_slot->effect,
        .get_define_signature = std::nullopt,
    });

inline flight::Ref<flight::types::ModifierDefinition> fog_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::fog_modifier_kind,
        .slot = flight::types::modifier_slot->effect,
        .get_define_signature = SignatureFunction{[](ModifierView modifier) {
          const auto fog = modifier_partial_view<flight::types::FogModifier>(modifier);
          const auto mode = flight::row_get<flight::RowKey<"mode">>(fog);
          if (mode == flight::types::fog_modifier_mode->exponential) return flight::String("e");
          if (mode == flight::types::fog_modifier_mode->exponential2) return flight::String("x");
          return flight::String("l");
        }},
    });

inline flight::Ref<flight::types::ModifierDefinition> rim_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::rim_modifier_kind,
        .slot = flight::types::modifier_slot->effect,
        .get_define_signature = std::nullopt,
    });

inline flight::Ref<flight::types::ModifierDefinition> toon_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::toon_modifier_kind,
        .slot = flight::types::modifier_slot->effect,
        .get_define_signature = std::nullopt,
    });

inline flight::Ref<flight::types::ModifierDefinition> vertex_displace_modifier_definition =
    flight::make_ref<flight::types::ModifierDefinition>(flight::types::ModifierDefinition{
        .kind = flight::types::vertex_displace_modifier_kind,
        .slot = flight::types::modifier_slot->vertex,
        .get_define_signature = SignatureFunction{[](ModifierView modifier) {
          const auto displace = modifier_partial_view<flight::types::VertexDisplaceModifier>(modifier);
          const auto source = flight::row_get<flight::RowKey<"source">>(displace);
          flight::String signature =
              source == flight::types::vertex_displace_modifier_source->height_map
                  ? flight::String("h")
                  : flight::String("s");
          if (flight::row_get<flight::RowKey<"axis">>(displace).has_value()) {
            signature += flight::String("a");
          }
          return signature;
        }},
    });

inline void register_built_in_modifiers(flight::Ref<flight::types::ModifierRegistry> registry) {
  register_modifier(registry, animated_normal_modifier_definition);
  register_modifier(registry, dissolve_modifier_definition);
  register_modifier(registry, emissive_modifier_definition);
  register_modifier(registry, env_reflect_modifier_definition);
  register_modifier(registry, fog_modifier_definition);
  register_modifier(registry, rim_modifier_definition);
  register_modifier(registry, toon_modifier_definition);
  register_modifier(registry, vertex_displace_modifier_definition);
}

}  // namespace flight::shading
