// Generated by @flighthq/tool-compiler from @flighthq/font-formats/packages/font-formats/src/cffCharstring.ts#CffCharstring at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused runCffCharstring because its readonly structural subroutine
// arrays could not preserve the nominal CffIndexEntry array identity. This override supplies that
// function with the nominal array type already used by every generated caller.

#include <cmath>
#include <cstddef>
#include <functional>
#include <optional>

#include <flight/data_view.hpp>
#include <flight/runtime.hpp>
#include <flight/structural_ref.hpp>
#include <flight/types/cff_table.hpp>
#include <flight/types/path.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2",
              "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::font_formats {

inline const double max_call_depth = 10.0;

inline double cff_subroutine_bias(double count) {
  if (count < 1240.0) return 107.0;
  if (count < 33900.0) return 1131.0;
  return 32768.0;
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_CURSOR_VALUE_154F29F92AB1835D
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_CURSOR_VALUE_154F29F92AB1835D
struct cursor_value_154f29f92ab1835d : public flight::ReferenceEnabled {
  double cursor;
  double value;
};
#endif

inline std::optional<flight::Ref<cursor_value_154f29f92ab1835d>> read_cff_charstring_operand(
    flight::DataView view, double b0, double cursor, double end) {
  if (b0 == 28.0) {
    if (cursor + 2.0 > end) return std::nullopt;
    return flight::make_ref<cursor_value_154f29f92ab1835d>(
        cursor_value_154f29f92ab1835d{.cursor = cursor + 2.0,
                                      .value = view.get_int16(cursor)});
  }
  if (b0 <= 246.0) {
    return flight::make_ref<cursor_value_154f29f92ab1835d>(
        cursor_value_154f29f92ab1835d{.cursor = cursor, .value = b0 - 139.0});
  }
  if (b0 <= 250.0) {
    if (cursor + 1.0 > end) return std::nullopt;
    return flight::make_ref<cursor_value_154f29f92ab1835d>(cursor_value_154f29f92ab1835d{
        .cursor = cursor + 1.0,
        .value = (b0 - 247.0) * 256.0 + view.get_uint8(cursor) + 108.0});
  }
  if (b0 <= 254.0) {
    if (cursor + 1.0 > end) return std::nullopt;
    return flight::make_ref<cursor_value_154f29f92ab1835d>(cursor_value_154f29f92ab1835d{
        .cursor = cursor + 1.0,
        .value = -(b0 - 251.0) * 256.0 - view.get_uint8(cursor) - 108.0});
  }
  if (cursor + 4.0 > end) return std::nullopt;
  return flight::make_ref<cursor_value_154f29f92ab1835d>(
      cursor_value_154f29f92ab1835d{.cursor = cursor + 4.0,
                                    .value = view.get_int32(cursor) / 65536.0});
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_END_START_5A7F0229CF226E65
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_END_START_5A7F0229CF226E65
struct end_start_5a7f0229cf226e65 : public flight::ReferenceEnabled {
  double end;
  double start;
};
#endif

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_OPEN_STEM_COUNT_WIDTH_PARSED_X_Y_0375DBBFD7689F6B
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_FONT_FORMATS_OPEN_STEM_COUNT_WIDTH_PARSED_X_Y_0375DBBFD7689F6B
struct open_stem_count_width_parsed_x_y_0375dbbfd7689f6b : public flight::ReferenceEnabled {
  bool open;
  double stem_count;
  bool width_parsed;
  double x;
  double y;
};
#endif

// OVERRIDE: the source accepts readonly structural entry arrays. Generated consumers already own
// Array<Ref<CffIndexEntry>>, so retain that exact nominal identity here and otherwise transcribe the
// Type 2 stack machine without changing its path, width, hint-mask, or subroutine behavior.
inline bool run_cff_charstring(
    flight::Ref<flight::types::Path> out,
    flight::Uint8Array bytes,
    flight::StructuralRef<
        flight::RowReadonly<flight::RowOf<flight::Ref<end_start_5a7f0229cf226e65>>>>
        charstring,
    flight::Array<flight::Ref<flight::types::CffIndexEntry>> local_subrs,
    flight::Array<flight::Ref<flight::types::CffIndexEntry>> global_subrs) {
  out->commands.clear();
  out->data.clear();
  out->winding = flight::String("nonZero");

  flight::DataView view(bytes.buffer, bytes.byte_offset, bytes.byte_length);
  flight::Array<double> stack;
  auto state = flight::make_ref<open_stem_count_width_parsed_x_y_0375dbbfd7689f6b>(
      open_stem_count_width_parsed_x_y_0375dbbfd7689f6b{
          .open = false, .stem_count = 0.0, .width_parsed = false, .x = 0.0, .y = 0.0});

  const auto move_to = [&](double x, double y) {
    if (state->open) out->commands.push(flight::types::path_command->close);
    out->commands.push(flight::types::path_command->move_to);
    out->data.push(x, -y);
    state->open = true;
  };
  const auto line_to = [&](double x, double y) {
    out->commands.push(flight::types::path_command->line_to);
    out->data.push(x, -y);
  };
  const auto curve_to =
      [&](double x1, double y1, double x2, double y2, double x, double y) {
        out->commands.push(flight::types::path_command->cubic_curve_to);
        out->data.push(x1, -y1, x2, -y2, x, -y);
      };

  const auto take_width = [&](double expected) {
    if (state->width_parsed) return;
    state->width_parsed = true;
    if (static_cast<double>(stack.size()) > expected) static_cast<void>(stack.shift());
  };
  const auto take_width_by_parity = [&](double multiple) {
    if (state->width_parsed) return;
    state->width_parsed = true;
    if (std::fmod(static_cast<double>(stack.size()), multiple) != 0.0) {
      static_cast<void>(stack.shift());
    }
  };

  const auto emit_relative_curve = [&](double index, double /* stride */) {
    const double x1 = state->x + stack.element(index);
    const double y1 = state->y + stack.element(index + 1.0);
    const double x2 = x1 + stack.element(index + 2.0);
    const double y2 = y1 + stack.element(index + 3.0);
    state->x = x2 + stack.element(index + 4.0);
    state->y = y2 + stack.element(index + 5.0);
    curve_to(x1, y1, x2, y2, state->x, state->y);
  };

  std::function<bool(double, double, double)> execute;
  execute = [&](double start, double end, double depth) -> bool {
    if (depth > max_call_depth) return false;
    double cursor = start;

    while (cursor < end) {
      const double b0 = view.get_uint8(cursor);
      cursor += 1.0;

      if (b0 >= 32.0 || b0 == 28.0) {
        const auto operand = read_cff_charstring_operand(view, b0, cursor, end);
        if (!operand.has_value()) return false;
        stack.push(operand.value()->value);
        cursor = operand.value()->cursor;
        continue;
      }

      switch (static_cast<int>(b0)) {
        case 1:
        case 3:
        case 18:
        case 23:
          take_width_by_parity(2.0);
          state->stem_count +=
              flight::signed_right_shift(static_cast<double>(stack.size()), 1.0);
          stack.clear();
          break;

        case 19:
        case 20:
          take_width_by_parity(2.0);
          state->stem_count +=
              flight::signed_right_shift(static_cast<double>(stack.size()), 1.0);
          stack.clear();
          cursor += flight::signed_right_shift(state->stem_count + 7.0, 3.0);
          if (cursor > end) return false;
          break;

        case 21:
          take_width(2.0);
          state->x += stack.get(0.0).value_or(0.0);
          state->y += stack.get(1.0).value_or(0.0);
          move_to(state->x, state->y);
          stack.clear();
          break;

        case 22:
          take_width(1.0);
          state->x += stack.get(0.0).value_or(0.0);
          move_to(state->x, state->y);
          stack.clear();
          break;

        case 4:
          take_width(1.0);
          state->y += stack.get(0.0).value_or(0.0);
          move_to(state->x, state->y);
          stack.clear();
          break;

        case 5:
          for (double index = 0.0; index + 1.0 < static_cast<double>(stack.size());
               index += 2.0) {
            state->x += stack.element(index);
            state->y += stack.element(index + 1.0);
            line_to(state->x, state->y);
          }
          stack.clear();
          break;

        case 6:
        case 7: {
          bool horizontal = b0 == 6.0;
          for (const double delta : stack) {
            if (horizontal) {
              state->x += delta;
            } else {
              state->y += delta;
            }
            line_to(state->x, state->y);
            horizontal = !horizontal;
          }
          stack.clear();
          break;
        }

        case 8:
          for (double index = 0.0; index + 5.0 < static_cast<double>(stack.size());
               index += 6.0) {
            emit_relative_curve(index, 6.0);
          }
          stack.clear();
          break;

        case 24: {
          double index = 0.0;
          for (; index + 5.0 < static_cast<double>(stack.size()) - 2.0; index += 6.0) {
            emit_relative_curve(index, 6.0);
          }
          state->x += stack.get(index).value_or(0.0);
          state->y += stack.get(index + 1.0).value_or(0.0);
          line_to(state->x, state->y);
          stack.clear();
          break;
        }

        case 25: {
          double index = 0.0;
          for (; index + 1.0 < static_cast<double>(stack.size()) - 6.0; index += 2.0) {
            state->x += stack.element(index);
            state->y += stack.element(index + 1.0);
            line_to(state->x, state->y);
          }
          emit_relative_curve(index, 6.0);
          stack.clear();
          break;
        }

        case 26:
        case 27: {
          const bool vertical = b0 == 26.0;
          double index = 0.0;
          double lead = 0.0;
          if (stack.size() % 4 == 1) {
            lead = stack.element(0.0);
            index = 1.0;
          }
          for (; index + 3.0 < static_cast<double>(stack.size()); index += 4.0) {
            const double x1 = state->x + (vertical ? lead : stack.element(index));
            const double y1 = state->y + (vertical ? stack.element(index) : lead);
            const double x2 = x1 + stack.element(index + 1.0);
            const double y2 = y1 + stack.element(index + 2.0);
            state->x = x2 + (vertical ? 0.0 : stack.element(index + 3.0));
            state->y = y2 + (vertical ? stack.element(index + 3.0) : 0.0);
            curve_to(x1, y1, x2, y2, state->x, state->y);
            lead = 0.0;
          }
          stack.clear();
          break;
        }

        case 30:
        case 31: {
          bool horizontal = b0 == 31.0;
          double index = 0.0;
          while (index + 3.0 < static_cast<double>(stack.size())) {
            const bool last = index + 8.0 > static_cast<double>(stack.size());
            const double extra =
                last && static_cast<double>(stack.size()) - index == 5.0
                    ? stack.element(index + 4.0)
                    : 0.0;
            double x1;
            double y1;
            if (horizontal) {
              x1 = state->x + stack.element(index);
              y1 = state->y;
            } else {
              x1 = state->x;
              y1 = state->y + stack.element(index);
            }
            const double x2 = x1 + stack.element(index + 1.0);
            const double y2 = y1 + stack.element(index + 2.0);
            if (horizontal) {
              state->y = y2 + stack.element(index + 3.0);
              state->x = x2 + extra;
            } else {
              state->x = x2 + stack.element(index + 3.0);
              state->y = y2 + extra;
            }
            curve_to(x1, y1, x2, y2, state->x, state->y);
            horizontal = !horizontal;
            index += 4.0;
          }
          stack.clear();
          break;
        }

        case 10:
        case 29: {
          const auto subrs = b0 == 10.0 ? local_subrs : global_subrs;
          const double index = stack.pop().value_or(0.0) +
                               cff_subroutine_bias(static_cast<double>(subrs.size()));
          const auto subr = subrs.get(index);
          if (!subr.has_value()) return false;
          if (!execute(subr.value()->start, subr.value()->end, depth + 1.0)) return false;
          break;
        }

        case 11:
          return true;

        case 14:
          take_width(0.0);
          if (state->open) out->commands.push(flight::types::path_command->close);
          state->open = false;
          return true;

        case 12:
          if (cursor >= end) return false;
          cursor += 1.0;
          stack.clear();
          break;

        default:
          return false;
      }
    }
    return true;
  };

  if (!execute(flight::row_get<flight::RowKey<"start">>(charstring),
               flight::row_get<flight::RowKey<"end">>(charstring), 0.0)) {
    return false;
  }
  if (state->open) out->commands.push(flight::types::path_command->close);
  return true;
}

}  // namespace flight::font_formats
