#pragma once

// Generated by @flighthq/tool-compiler. BEST-EFFORT PLACEHOLDER -- replaced by this override.
// @flighthq/filesystem/packages/filesystem/src/filesystem.ts was refused as one unit because the
// AbortSignal event-map callback reaches an indexed-access type the C++ emitter cannot lower.

#include <concepts>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <flight/abort.hpp>
#include <flight/regexp.hpp>
#include <flight/runtime.hpp>
#include <flight/stream.hpp>
#include <flight/structural_ref.hpp>
#include <flight/types/dialog.hpp>
#include <flight/types/file_system.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2",
              "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::filesystem {

// OVERRIDE: this file faithfully supplies the forty declarations whose source can be represented
// by the current runtime. The four pathless dialog-handle operations remain deliberately absent:
// their TypeScript calls getFileDialogHandleOperations(handle), but that function was itself
// refused in flight/dialog/file_dialog.hpp and FileDialogHandle's generated EntityRuntime carrier
// does not expose FileDialogHandleRuntime::operations. Returning null/false for a PRESENT operation
// would turn a runtime-representation gap into different public behavior, so this override does not.

namespace detail {

using HostFileSystem = flight::StructuralRef<
    flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::HostFileSystemCapability>>>>;
using FileWalkOptions = flight::StructuralRef<
    flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::FileWalkOptions>>>>;
using FilePermissions = flight::StructuralRef<
    flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::FilePermissions>>>>;
using FileWatchEvent = flight::StructuralRef<
    flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::FileWatchEvent>>>>;

// This module's refusal also prevented its property names from entering sdk/structural_members.hpp.
// Read the concrete generated carrier when the row wraps one, and retain the ordinary named-cell
// path for a row built dynamically. This is the same two-domain lookup StructuralRef performs when
// generated member metadata exists; the knowledge is local here because these are precisely the
// names whose metadata could not be generated.
template <typename Schema, typename Object, typename Value>
[[nodiscard]] const Value& member(
    const flight::StructuralRef<Schema>& source, Value Object::*native_member,
    std::string_view name) {
  static_assert(std::same_as<typename flight::StructuralRef<Schema>::object_type, Object>);
  if (const auto object = source.shared_object()) return object.get()->*native_member;
  if (source.shared_owner()) {
    if (auto* value = source.shared_owner()->template named_value_if<Value>(name)) return *value;
  }
  throw std::out_of_range("required filesystem structural-row property is absent");
}

template <typename Value>
[[nodiscard]] flight::Task<Value> reject_aborted(const flight::AbortSignal& signal) {
  return flight::Task<Value>::reject(signal.reason.snapshot());
}

[[nodiscard]] inline flight::RegExp glob_to_reg_exp(flight::String pattern);
[[nodiscard]] inline flight::Array<flight::String> split_path(flight::String path);
[[nodiscard]] inline flight::String format_resolved_path(
    flight::Array<flight::String> segments, bool absolute);
[[nodiscard]] inline flight::Array<flight::String> resolve_path_segments(
    flight::String path, bool absolute);

} // namespace detail

inline flight::Task<bool> append_text_file(
    detail::HostFileSystem host_file_system, flight::String path, flight::String data,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<bool>(*signal);
  const auto append = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::append_text_file,
      "appendTextFile");
  if (!append.has_value()) return flight::Task<bool>::resolve(false);
  return signal.has_value() ? append.value()(path, data, signal)
                            : append.value()(path, data, std::nullopt);
}

inline flight::Task<bool> can_access_file(
    detail::HostFileSystem host_file_system, flight::String path, flight::String mode) {
  const auto access = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::can_access_file,
      "canAccessFile");
  return access.has_value() ? access.value()(path, mode) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> copy_file(
    detail::HostFileSystem host_file_system, flight::String from, flight::String to) {
  const auto copy = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::copy, "copy");
  return copy.has_value() ? copy.value()(from, to) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> create_file_symlink(flight::String, flight::String) {
  return flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> directory_exists(
    detail::HostFileSystem host_file_system, flight::String path) {
  const auto exists = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::directory_exists,
      "directoryExists");
  return exists.has_value() ? exists.value()(path) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> file_exists(
    detail::HostFileSystem host_file_system, flight::String path) {
  const auto exists = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::file_exists, "fileExists");
  return exists.has_value() ? exists.value()(path) : flight::Task<bool>::resolve(false);
}

inline flight::Task<flight::Array<flight::Ref<flight::types::FileEntry>>> read_directory_recursive(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<detail::FileWalkOptions> options = std::nullopt);

inline flight::Task<flight::Array<flight::Ref<flight::types::FileEntry>>> find_files(
    detail::HostFileSystem host_file_system, flight::String root_path, flight::String pattern,
    std::optional<detail::FileWalkOptions> options = std::nullopt) {
  auto all = co_await read_directory_recursive(host_file_system, root_path, options);
  if (all.empty()) co_return flight::Array<flight::Ref<flight::types::FileEntry>>{};
  const auto expression = detail::glob_to_reg_exp(pattern);
  co_return all.filter([expression](const flight::Ref<flight::types::FileEntry>& entry) {
    return expression.test(entry->name) || expression.test(entry->path);
  });
}

inline flight::String get_file_base_name(flight::String path) {
  const auto segments = detail::split_path(path);
  return segments.empty() ? flight::String() : segments.element(static_cast<double>(segments.size() - 1));
}

inline flight::String get_file_directory_name(flight::String path) {
  const auto segments = detail::split_path(path);
  return segments.size() <= 1 ? flight::String() : segments.slice(0, -1).join(flight::String("/"));
}

inline flight::String get_file_extension_name(flight::String path) {
  const auto base = get_file_base_name(path);
  const auto dot = base.last_index_of(flight::String("."));
  return dot > 0 ? base.slice(dot) : flight::String();
}

inline flight::Task<std::optional<flight::Ref<flight::types::FilePermissions>>>
get_file_permissions(flight::String) {
  return flight::Task<std::optional<flight::Ref<flight::types::FilePermissions>>>::resolve(std::nullopt);
}

inline flight::Task<std::optional<flight::String>> get_file_real_path(flight::String) {
  return flight::Task<std::optional<flight::String>>::resolve(std::nullopt);
}

inline flight::String get_file_system_path(flight::types::FileSystemPathKind) {
  return flight::String();
}

inline flight::Task<std::optional<flight::Ref<flight::types::FileSystemUsage>>> get_file_system_usage(
    detail::HostFileSystem host_file_system) {
  const auto usage = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::get_file_system_usage,
      "getFileSystemUsage");
  return usage.has_value()
             ? usage.value()()
             : flight::Task<std::optional<flight::Ref<flight::types::FileSystemUsage>>>::resolve(
                   std::nullopt);
}

inline bool is_absolute_file_path(flight::String path) {
  if (path.empty()) return false;
  if (path.char_at(0.0) == flight::String("/")) return true;
  return path.length() >= 2 && flight::RegExp(flight::String("^[A-Za-z]:")).test(path);
}

inline flight::String join_file_path(flight::Array<flight::String> segments) {
  const bool absolute = !segments.empty() && segments.element(0.0).starts_with(flight::String("/"));
  return detail::format_resolved_path(
      detail::resolve_path_segments(segments.join(flight::String("/")), absolute), absolute);
}

inline flight::Task<bool> make_directory(
    detail::HostFileSystem host_file_system, flight::String path) {
  const auto make = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::make_directory,
      "makeDirectory");
  return make.has_value() ? make.value()(path) : flight::Task<bool>::resolve(false);
}

inline flight::String normalize_file_path(flight::String path) {
  const bool absolute = path.starts_with(flight::String("/"));
  return detail::format_resolved_path(detail::resolve_path_segments(path, absolute), absolute);
}

inline flight::Task<std::optional<flight::ReadableStream<flight::Uint8Array>>>
open_file_read_stream(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = std::optional<flight::ReadableStream<flight::Uint8Array>>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto open = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::open_file_read_stream,
      "openFileReadStream");
  if (!open.has_value()) return flight::Task<Result>::resolve(std::nullopt);
  return signal.has_value() ? open.value()(path, signal) : open.value()(path, std::nullopt);
}

inline flight::Task<std::optional<flight::WritableStream<flight::Uint8Array>>>
open_file_write_stream(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = std::optional<flight::WritableStream<flight::Uint8Array>>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto open = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::open_file_write_stream,
      "openFileWriteStream");
  if (!open.has_value()) return flight::Task<Result>::resolve(std::nullopt);
  return signal.has_value() ? open.value()(path, signal) : open.value()(path, std::nullopt);
}

inline flight::Task<std::optional<flight::Uint8Array>> read_binary_file(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = std::optional<flight::Uint8Array>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto read = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::read_binary_file,
      "readBinaryFile");
  if (!read.has_value()) return flight::Task<Result>::resolve(std::nullopt);
  return signal.has_value() ? read.value()(path, signal) : read.value()(path, std::nullopt);
}

inline flight::Task<std::optional<flight::Uint8Array>> read_binary_file_range(
    detail::HostFileSystem host_file_system, flight::String path, double offset, double length,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = std::optional<flight::Uint8Array>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto read = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::read_binary_file_range,
      "readBinaryFileRange");
  if (!read.has_value()) return flight::Task<Result>::resolve(std::nullopt);
  return signal.has_value() ? read.value()(path, offset, length, signal)
                            : read.value()(path, offset, length, std::nullopt);
}

inline flight::Task<flight::Array<flight::Ref<flight::types::FileEntry>>> read_directory(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = flight::Array<flight::Ref<flight::types::FileEntry>>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto read = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::read_directory,
      "readDirectory");
  if (!read.has_value()) return flight::Task<Result>::resolve(Result{});
  return signal.has_value() ? read.value()(path, signal) : read.value()(path, std::nullopt);
}

inline flight::Task<flight::Array<flight::Ref<flight::types::FileEntry>>> read_directory_recursive(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<detail::FileWalkOptions> options) {
  using Result = flight::Array<flight::Ref<flight::types::FileEntry>>;
  if (options.has_value()) {
    const auto signal = detail::member(
        options.value(), &flight::types::FileWalkOptions::signal, "signal");
    if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  }
  const auto read = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::read_directory_recursive,
      "readDirectoryRecursive");
  if (!read.has_value()) return flight::Task<Result>::resolve(Result{});
  return options.has_value() ? read.value()(path, options)
                             : read.value()(path, std::nullopt);
}

inline flight::Task<std::optional<flight::String>> read_file_symlink(flight::String) {
  return flight::Task<std::optional<flight::String>>::resolve(std::nullopt);
}

inline flight::Task<std::optional<flight::String>> read_text_file(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  using Result = std::optional<flight::String>;
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<Result>(*signal);
  const auto read = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::read_text_file,
      "readTextFile");
  if (!read.has_value()) return flight::Task<Result>::resolve(std::nullopt);
  return signal.has_value() ? read.value()(path, signal) : read.value()(path, std::nullopt);
}

inline flight::Task<bool> remove_directory(
    detail::HostFileSystem host_file_system, flight::String path,
    std::optional<bool> recursive = std::nullopt) {
  const auto remove = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::remove_directory,
      "removeDirectory");
  return remove.has_value() ? remove.value()(path, recursive) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> remove_file(
    detail::HostFileSystem host_file_system, flight::String path) {
  const auto remove = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::remove_file, "removeFile");
  return remove.has_value() ? remove.value()(path) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> rename_file(
    detail::HostFileSystem host_file_system, flight::String from, flight::String to) {
  const auto rename = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::rename, "rename");
  return rename.has_value() ? rename.value()(from, to) : flight::Task<bool>::resolve(false);
}

inline flight::Task<bool> set_file_permissions(
    flight::String, detail::FilePermissions) {
  return flight::Task<bool>::resolve(false);
}

inline flight::Task<std::optional<flight::Ref<flight::types::FileStat>>> stat_file(
    detail::HostFileSystem host_file_system, flight::String path) {
  using Result = std::optional<flight::Ref<flight::types::FileStat>>;
  const auto stat = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::stat_file, "statFile");
  return stat.has_value() ? stat.value()(path) : flight::Task<Result>::resolve(std::nullopt);
}

inline std::function<void()> watch_path(
    flight::String, std::function<void(detail::FileWatchEvent)>) {
  return [] {};
}

inline flight::Task<bool> write_binary_file(
    detail::HostFileSystem host_file_system, flight::String path, flight::Uint8Array data,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<bool>(*signal);
  const auto write = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::write_binary_file,
      "writeBinaryFile");
  if (!write.has_value()) return flight::Task<bool>::resolve(false);
  return signal.has_value() ? write.value()(path, data, signal)
                            : write.value()(path, data, std::nullopt);
}

inline flight::Task<bool> write_binary_file_chunks(
    detail::HostFileSystem host_file_system, flight::String path,
    flight::AsyncIterable<flight::Uint8Array> chunks,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  if (signal.has_value()) signal->throw_if_aborted();
  auto stream = co_await open_file_write_stream(host_file_system, path, signal);
  if (!stream.has_value()) co_return false;
  const auto writer = stream->get_writer();
  const auto ignore_rejection = [](const flight::Rejection&) {};
  if (signal.has_value() && signal->aborted) {
    co_await writer.abort(signal->reason.snapshot()).catch_error(ignore_rejection);
    signal->throw_if_aborted();
  }

  struct AbortState final {
    std::mutex mutex;
    bool aborted{false};
    std::optional<flight::Task<void>> abort_task;
  };
  const auto abort_state = std::make_shared<AbortState>();
  const flight::Function<void()> on_abort = [abort_state, writer, signal, ignore_rejection] {
    auto task = writer.abort(signal.has_value() ? signal->reason.snapshot() : flight::AbortReason{})
                    .catch_error(ignore_rejection);
    const std::scoped_lock lock(abort_state->mutex);
    abort_state->aborted = true;
    abort_state->abort_task = std::move(task);
  };
  if (signal.has_value()) {
    signal->add_event_listener(
        flight::String("abort"), on_abort, flight::AbortEventListenerOptions{.once = true});
  }

  bool succeeded = false;
  try {
    while (const auto chunk = co_await chunks.next()) {
      if (signal.has_value()) signal->throw_if_aborted();
      co_await writer.write(chunk->slice(0));
    }
    if (signal.has_value()) signal->throw_if_aborted();
    co_await writer.close();
    succeeded = true;
  } catch (...) {
    // The TypeScript catch deliberately converts non-abort stream failures to false.
  }

  bool aborted = false;
  std::optional<flight::Task<void>> abort_task;
  {
    const std::scoped_lock lock(abort_state->mutex);
    aborted = abort_state->aborted;
    abort_task = abort_state->abort_task;
  }
  if (!succeeded) {
    if (abort_task.has_value()) co_await abort_task.value();
    else co_await writer.abort().catch_error(ignore_rejection);
  }
  if (signal.has_value()) signal->remove_event_listener(flight::String("abort"), on_abort);
  if (succeeded) co_return true;
  if (aborted && signal.has_value()) signal->throw_if_aborted();
  co_return false;
}

inline flight::Task<bool> write_file_atomic(
    detail::HostFileSystem host_file_system, flight::String path,
    std::variant<flight::Uint8Array, flight::String> data,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<bool>(*signal);
  const auto write = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::write_file_atomic,
      "writeFileAtomic");
  if (!write.has_value()) return flight::Task<bool>::resolve(false);
  return signal.has_value() ? write.value()(path, data, signal)
                            : write.value()(path, data, std::nullopt);
}

inline flight::Task<bool> write_text_file(
    detail::HostFileSystem host_file_system, flight::String path, flight::String data,
    std::optional<flight::AbortSignal> signal = std::nullopt) {
  if (signal.has_value() && signal->aborted) return detail::reject_aborted<bool>(*signal);
  const auto write = detail::member(
      host_file_system, &flight::types::HostFileSystemCapability::write_text_file,
      "writeTextFile");
  if (!write.has_value()) return flight::Task<bool>::resolve(false);
  return signal.has_value() ? write.value()(path, data, signal)
                            : write.value()(path, data, std::nullopt);
}

namespace detail {

inline flight::RegExp glob_to_reg_exp(flight::String pattern) {
  flight::String expression("^");
  for (double index = 0.0; index < static_cast<double>(pattern.length()); index += 1.0) {
    const auto character = pattern.char_at(index);
    if (character == flight::String("*")) {
      if (pattern.char_at(index + 1.0) == flight::String("*")) {
        expression += flight::String(".*");
        index += 1.0;
        if (pattern.char_at(index + 1.0) == flight::String("/")) index += 1.0;
      } else {
        expression += flight::String("[^/]*");
      }
    } else if (character == flight::String("?")) {
      expression += flight::String("[^/]");
    } else if (flight::String(".+^${}()|[]\\").includes(character)) {
      expression += flight::String("\\") + character;
    } else {
      expression += character;
    }
  }
  return flight::RegExp(expression + flight::String("$"));
}

inline flight::Array<flight::String> split_path(flight::String path) {
  return path.split(flight::String("/")).filter([](const flight::String& segment) {
    return segment != flight::String() && segment != flight::String(".");
  });
}

inline flight::String format_resolved_path(
    flight::Array<flight::String> segments, bool absolute) {
  if (absolute) return flight::String("/") + segments.join(flight::String("/"));
  return segments.empty() ? flight::String(".") : segments.join(flight::String("/"));
}

inline flight::Array<flight::String> resolve_path_segments(flight::String path, bool absolute) {
  flight::Array<flight::String> output;
  for (const auto& segment : split_path(path)) {
    if (segment != flight::String("..")) {
      output.push(segment);
      continue;
    }
    const auto previous = output.empty()
                              ? std::optional<flight::String>{}
                              : output.get(static_cast<double>(output.size() - 1));
    if (previous.has_value() && previous.value() != flight::String("..")) {
      static_cast<void>(output.pop());
      continue;
    }
    if (!absolute) output.push(flight::String(".."));
  }
  return output;
}

} // namespace detail

} // namespace flight::filesystem
