// Generated by @flighthq/tool-compiler from @flighthq/physics2d/packages/physics2d/src/nodeSync.ts#NodeSync at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct Node2DTraits; }
namespace flight::types { struct Physics2DCollider; }
namespace flight::types { struct RigidBody2D; }
namespace flight::types { template <typename Traits> struct Node; }

#include <flight/math/constants.hpp>
#include <flight/node/revision.hpp>
#include <flight/types/collision.hpp>
#include <flight/types/node.hpp>
#include <flight/types/node2_d.hpp>
#include <flight/types/physics2_d.hpp>

namespace flight::physics2d {

using flight::types::Physics2DCollider;
using flight::types::RigidBody2D;

inline void sync_physics2_dbody_to_node2_d(flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::RigidBody2D>>>> body, flight::types::Node2D node) {
  flight::row_set<flight::RowKey<"x">>(node, flight::row_get<flight::RowKey<"x">>(body));
  flight::row_set<flight::RowKey<"y">>(node, flight::row_get<flight::RowKey<"y">>(body));
  flight::row_set<flight::RowKey<"rotation">>(node, (flight::row_get<flight::RowKey<"angle">>(body) * flight::math::rad_to_deg_flight_value_variable__u000052__u000041__u000044__u00005f__u000054__u00004f__u00005f__u000044__u000045__u000047__flight_source_ad5040a7d8c07bd3));
  using NodeOwner = flight::types::Node<flight::Ref<flight::types::Node2DTraits>>;
  auto node_row = flight::structural_ref_cast<
      flight::StructuralRef<flight::RowReadonly<flight::RowOf<std::shared_ptr<NodeOwner>>>>>(node);
  auto runtime = flight::structural_ref_cast<std::shared_ptr<NodeOwner>>(node_row)->entity_runtime_key;
  if (!runtime.has_value()) {
    throw flight::Error(flight::String("Cannot invalidate a Node2D without its runtime"));
  }
  runtime.value()->local_transform_id =
      flight::unsigned_right_shift(runtime.value()->local_transform_id + 1.0, 0.0);
}

} // namespace flight::physics2d
