// Generated by @flighthq/tool-compiler from @flighthq/physics2d/packages/physics2d/src/stepValidation.ts#StepValidation at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function isPhysics2DContactValid -- source line 26
//   missing: function isPhysics2DSolverConfigValid -- source line 89
//   missing: function isPhysics2DColliderStateValid -- source line 163
//   missing: function isPhysics2DJointValid -- source line 185
//   missing: function isRigidBody2DStateValid -- source line 216
#include <cmath>
#include <flight/number.hpp>
#include <limits>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/physics2_d.hpp>

#include <flight/types/collision.hpp>

namespace flight::physics2d {

using flight::types::CollisionBuiltInShape2D;
using flight::types::Physics2DCollider;
using flight::types::Physics2DContact;
using flight::types::Physics2DContactPoint;
using flight::types::Physics2DJoint;
using flight::types::Physics2DSolverConfig;
using flight::types::Physics2DWorld;
using flight::types::RigidBody2D;


// NOT GENERATED: function isPhysics2DContactValid -- source line 26
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   export function isPhysics2DContactValid(contact: Readonly<Physics2DContact>): boolean {
//     if (
//       !Number.isSafeInteger(contact.bodyA) ||
//       !Number.isSafeInteger(contact.bodyB) ||
//       !Number.isSafeInteger(contact.colliderA) ||
//       !Number.isSafeInteger(contact.colliderB) ||
//       !Number.isSafeInteger(contact.pointCount) ||
//       contact.pointCount < 0 ||
//       contact.pointCount > contact.points.length ||
//       !Number.isFinite(contact.normalX) ||
//       !Number.isFinite(contact.normalY) ||
//       !Number.isFinite(contact.friction) ||
//       contact.friction < 0 ||
//       !Number.isFinite(contact.restitution) ||
//       contact.restitution < 0 ||
//       typeof contact.enabled !== 'boolean' ||
//       typeof contact.sensor !== 'boolean' ||
//       typeof contact.touching !== 'boolean'
//     ) {
//       return false;
//     }
//     for (let i = 0; i < contact.pointCount; i++) {
//       const point = contact.points[i];
//       if (point === undefined) return false;
//       // Enumerated rather than walked with `for...in`: this runs over every point of every contact on
//       // every step, and the generic form allocates a key string per field. Adding a numeric field to
//       // `Physics2DContactPoint` means adding a line here.
//       if (
//         !Number.isFinite(point.x) ||
//         !Number.isFinite(point.y) ||
//         !Number.isFinite(point.depth) ||
//         !Number.isFinite(point.featureId) ||
//         !Number.isFinite(point.rAX) ||
//         !Number.isFinite(point.rAY) ||
//         !Number.isFinite(point.rBX) ||
//         !Number.isFinite(point.rBY) ||
//         !Number.isFinite(point.normalImpulse) ||
//         !Number.isFinite(point.tangentImpulse) ||
//         !Number.isFinite(point.normalMass) ||
//         !Number.isFinite(point.tangentMass) ||
//         !Number.isFinite(point.bias)
//       ) {
//         return false;
//       }
//     }
//     return true;
//   }
//   
// cpp emission failed for @flighthq/physics2d/packages/physics2d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics2_dcontact_valid(flight::Ref<Physics2DContact> contact) {
  if (!flight::is_safe_integer(contact->body_a) ||
      !flight::is_safe_integer(contact->body_b) ||
      !flight::is_safe_integer(contact->collider_a) ||
      !flight::is_safe_integer(contact->collider_b) ||
      !flight::is_safe_integer(contact->point_count) || contact->point_count < 0.0 ||
      contact->point_count > static_cast<double>(contact->points.size()) ||
      !std::isfinite(contact->normal_x) || !std::isfinite(contact->normal_y) ||
      !std::isfinite(contact->friction) || contact->friction < 0.0 ||
      !std::isfinite(contact->restitution) || contact->restitution < 0.0) {
    return false;
  }
  for (std::ptrdiff_t index = 0;
       index < static_cast<std::ptrdiff_t>(contact->point_count); ++index) {
    const auto& point = contact->points.element(index);
    if (!point || !std::isfinite(point->x) || !std::isfinite(point->y) ||
        !std::isfinite(point->depth) || !std::isfinite(point->feature_id) ||
        !std::isfinite(point->r_ax) || !std::isfinite(point->r_ay) ||
        !std::isfinite(point->r_bx) || !std::isfinite(point->r_by) ||
        !std::isfinite(point->normal_impulse) || !std::isfinite(point->tangent_impulse) ||
        !std::isfinite(point->normal_mass) || !std::isfinite(point->tangent_mass) ||
        !std::isfinite(point->bias)) {
      return false;
    }
  }
  return true;
}

inline bool is_physics2_dcontact_state_valid(flight::Ref<Physics2DWorld> world) {
  for (auto contact : world->contacts) {
    if (!is_physics2_dcontact_valid(contact)) {
      return false;
    }
  }
  return true;
}

inline bool is_physics2_dgravity_valid(flight::Ref<Physics2DWorld> world) {
  return (std::isfinite(world->gravity_x) && std::isfinite(world->gravity_y));
}

inline bool is_physics2_dprevious_timestep_valid(flight::Ref<Physics2DWorld> world) {
  return ((world->previous_timestep == 0.0) || (std::isfinite(world->previous_timestep) && (world->previous_timestep > 0.0)));
}


// NOT GENERATED: function isPhysics2DSolverConfigValid -- source line 89
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   export function isPhysics2DSolverConfigValid(config: Readonly<Physics2DSolverConfig>): boolean {
//     return (
//       typeof config.allowSleeping === 'boolean' &&
//       Number.isFinite(config.sleepLinearThreshold) &&
//       config.sleepLinearThreshold >= 0 &&
//       Number.isFinite(config.sleepAngularThreshold) &&
//       config.sleepAngularThreshold >= 0 &&
//       Number.isFinite(config.timeToSleep) &&
//       config.timeToSleep >= 0 &&
//       Number.isFinite(config.penetrationSlop) &&
//       config.penetrationSlop >= 0 &&
//       Number.isFinite(config.positionCorrection) &&
//       config.positionCorrection >= 0 &&
//       config.positionCorrection <= 1 &&
//       Number.isFinite(config.restitutionThreshold) &&
//       config.restitutionThreshold >= 0 &&
//       typeof config.warmStarting === 'boolean' &&
//       typeof config.continuousCollision === 'boolean' &&
//       Number.isSafeInteger(config.maxCcdSubsteps) &&
//       config.maxCcdSubsteps >= 0 &&
//       Number.isSafeInteger(config.maxCcdRotationSubsteps) &&
//       config.maxCcdRotationSubsteps >= 0
//     );
//   }
//   
// cpp emission failed for @flighthq/physics2d/packages/physics2d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_collision_shape_state_valid(flight::Ref<CollisionBuiltInShape2D> shape) {
  switch (shape.index()) {
    case 0: {
      const auto& value = std::get<0>(shape);
      return std::isfinite(value->x) && std::isfinite(value->y) &&
             std::isfinite(value->half_w) && value->half_w > 0.0 &&
             std::isfinite(value->half_h) && value->half_h > 0.0 &&
             std::isfinite(value->rotation);
    }
    case 1: {
      const auto& value = std::get<1>(shape);
      return std::isfinite(value->x0) && std::isfinite(value->y0) &&
             std::isfinite(value->x1) && std::isfinite(value->y1) &&
             std::isfinite(value->radius) && value->radius > 0.0;
    }
    case 2: {
      const auto& value = std::get<2>(shape);
      return std::isfinite(value->x) && std::isfinite(value->y) &&
             std::isfinite(value->radius) && value->radius > 0.0;
    }
    case 3: {
      const auto& value = std::get<3>(shape);
      return std::isfinite(value->x) && std::isfinite(value->y);
    }
    case 4: {
      const auto& points = std::get<4>(shape)->points;
      if (points.size() < 6 || points.size() % 2 != 0) return false;
      for (double coordinate : points) if (!std::isfinite(coordinate)) return false;
      return true;
    }
    case 5: {
      const auto& value = std::get<5>(shape);
      return std::isfinite(value->x0) && std::isfinite(value->y0) &&
             std::isfinite(value->x1) && std::isfinite(value->y1);
    }
    case 6: {
      const auto& value = std::get<6>(shape);
      return std::isfinite(value->min_x) && std::isfinite(value->min_y) &&
             std::isfinite(value->max_x) && std::isfinite(value->max_y) &&
             value->max_x > value->min_x && value->max_y > value->min_y;
    }
  }
  return false;
}

// NOT GENERATED: function isPhysics2DColliderStateValid -- source line 163
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isPhysics2DColliderStateValid(collider: Readonly<Physics2DCollider>): boolean {
//     const filter = collider.filter;
//     return (
//       isCollisionShapeStateValid(collider.local) &&
//       Number.isFinite(collider.material.density) &&
//       collider.material.density >= 0 &&
//       Number.isFinite(collider.material.friction) &&
//       collider.material.friction >= 0 &&
//       Number.isFinite(collider.material.restitution) &&
//       collider.material.restitution >= 0 &&
//       typeof collider.sensor === 'boolean' &&
//       (filter === undefined ||
//         (Number.isSafeInteger(filter.categoryBits) &&
//           Number.isSafeInteger(filter.maskBits) &&
//           Number.isSafeInteger(filter.groupIndex)))
//     );
//   }
//   
// cpp emission failed for @flighthq/physics2d/packages/physics2d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics2_dtimestep_valid(double dt) {
  return (std::isfinite(dt) && (dt > 0.0));
}

inline bool is_physics2_dbreak_threshold_valid(double threshold) {
  return (((flight::String("number") == flight::String("number")) && !std::isnan(threshold)) && (threshold >= 0.0));
}


// NOT GENERATED: function isPhysics2DJointValid -- source line 185
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isPhysics2DJointValid(joint: Readonly<Physics2DJoint>): boolean {
//     if (
//       typeof joint.kind !== 'string' ||
//       joint.kind.length === 0 ||
//       !Number.isSafeInteger(joint.bodyA) ||
//       !Number.isSafeInteger(joint.bodyB) ||
//       typeof joint.collideConnected !== 'boolean'
//     ) {
//       return false;
//     }
//     // The two break thresholds are the only fields on a joint allowed to be non-finite, because `Infinity`
//     // is how a joint says it does not break. Everything else non-finite is a fault: a NaN anchor or a NaN
//     // impulse spreads through the solver in one step and never comes back.
//     if (!isPhysics2DBreakThresholdValid(joint.breakForce) || !isPhysics2DBreakThresholdValid(joint.breakTorque)) {
//       return false;
//     }
//     for (const key in joint) {
//       if (key === 'breakForce' || key === 'breakTorque') continue;
//       const value = joint[key as keyof typeof joint];
//       if (typeof value === 'number' && !Number.isFinite(value)) return false;
//     }
//     return true;
//   }
//   
//   // A threshold is a non-negative magnitude or `Infinity`. NaN is rejected rather than treated as
//   // unbreakable: every comparison against NaN is false, so a NaN threshold would silently mean "never
//   // breaks" while looking like a number the author chose.
// cpp emission failed for @flighthq/physics2d/packages/physics2d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

[[noreturn]] inline bool is_physics2_djoint_valid(flight::Ref<Physics2DJoint>) {
  throw flight::Error(flight::String(
      "Physics2D joint validation is unavailable because runtime typeof evidence was not emitted"));
}

inline bool is_physics2_djoint_state_valid(flight::Ref<Physics2DWorld> world) {
  for (auto joint : world->joints) {
    if (!is_physics2_djoint_valid(joint)) {
      return false;
    }
  }
  return true;
}

inline flight::Array<flight::String> rigid_body_finite_keys = flight::Array<flight::String>{flight::String("x"), flight::String("y"), flight::String("angle"), flight::String("velocityX"), flight::String("velocityY"), flight::String("angularVelocity"), flight::String("forceX"), flight::String("forceY"), flight::String("torque"), flight::String("centerX"), flight::String("centerY")};


// NOT GENERATED: function isRigidBody2DStateValid -- source line 216
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isRigidBody2DStateValid(body: Readonly<RigidBody2D>): boolean {
//     if (
//       !Number.isSafeInteger(body.index) ||
//       body.index < 0 ||
//       (body.type !== 'dynamic' && body.type !== 'kinematic' && body.type !== 'static') ||
//       typeof body.fixedRotation !== 'boolean' ||
//       typeof body.bullet !== 'boolean' ||
//       typeof body.sleeping !== 'boolean' ||
//       typeof body.sleepEnabled !== 'boolean' ||
//       !Number.isFinite(body.sleepTimer) ||
//       body.sleepTimer < 0 ||
//       !Number.isFinite(body.linearDamping) ||
//       body.linearDamping < 0 ||
//       !Number.isFinite(body.angularDamping) ||
//       body.angularDamping < 0 ||
//       !Number.isFinite(body.gravityScale) ||
//       !Number.isFinite(body.mass) ||
//       body.mass < 0 ||
//       !Number.isFinite(body.inverseMass) ||
//       body.inverseMass < 0 ||
//       !Number.isFinite(body.inertia) ||
//       body.inertia < 0 ||
//       !Number.isFinite(body.inverseInertia) ||
//       body.inverseInertia < 0
//     ) {
//       return false;
//     }
//     for (const key of rigidBodyFiniteKeys) {
//       if (!Number.isFinite(body[key])) return false;
//     }
//     for (const collider of body.colliders) {
//       if (!isPhysics2DColliderStateValid(collider)) return false;
//     }
//     return true;
//   }
//   
// cpp emission failed for @flighthq/physics2d/packages/physics2d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

[[noreturn]] inline bool is_rigid_body2_dstate_valid(flight::Ref<RigidBody2D>) {
  throw flight::Error(flight::String(
      "RigidBody2D validation is unavailable because runtime typeof evidence was not emitted"));
}

inline bool is_physics2_dbody_state_valid(flight::Ref<Physics2DWorld> world) {
  if ((!flight::is_safe_integer(world->next_body_index) || (world->next_body_index < 0.0))) {
    return false;
  }
  for (auto body : world->bodies) {
    if ((!is_rigid_body2_dstate_valid(body) || (world->body_by_index.get(body->index) != body))) {
      return false;
    }
  }
  return true;
}

} // namespace flight::physics2d
