load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

cc_test(
    name = "tween",
    srcs = [
        "tween/generated/tween.hpp",
        "tween/tween_example.cpp",
    ],
    deps = ["//:cpp"],
)

cc_test(
    name = "sdk_math",
    srcs = ["sdk_math_example.cpp"],
    deps = ["//:sdk_preview"],
)

cc_binary(
    name = "sound_sdl",
    srcs = [
        "sound/generated/sound.hpp",
        "sound/sound_sdl_example.cpp",
    ],
    tags = ["manual"],
    deps = ["//:host_sdl"],
)

cc_binary(
    name = "tween_sdl_gl",
    srcs = [
        "tween/generated/tween.hpp",
        "tween/tween_sdl_gl_example.cpp",
    ],
    tags = ["manual"],
    deps = ["//:host_sdl_gl"],
)
