// Generated by @flighthq/tool-compiler from @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts#Physics2DAbiCommand at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function encodeJointFlags -- source line 365
//   missing: function encodeShapeKind -- source line 400
//   missing: function getJointKindValues -- source line 417
//   missing: function getShapeScalarCount -- source line 494
//   missing: function writeShapeScalars -- source line 557
#include <cmath>
#include <flight/boolean.hpp>
#include <flight/data_view.hpp>
#include <flight/number.hpp>
#include <flight/structural_ref.hpp>
#include <limits>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/physics2_dabi.hpp>

#include <flight/types/physics2_d.hpp>

#include <flight/types/collision.hpp>

namespace flight::physics2d_abi {

using flight::types::CollisionBuiltInShape2D;
using flight::types::Physics2DAbiCommandBuffer;
using flight::types::Physics2DAbiObjectId;
using flight::types::Physics2DBodyType;
using flight::types::Physics2DCollider;
using flight::types::Physics2DJoint;
using flight::types::Physics2DSolverConfig;
using flight::types::RigidBody2D;
struct PendingCommand;
} // namespace flight::physics2d_abi

#include <flight/physics2d_abi/physics2_dabi_layout.hpp>
namespace flight::physics2d_abi {

inline const flight::String physics2_ddistance_joint_kind = flight::String("Distance");
inline const flight::String physics2_dgear_joint_kind = flight::String("Gear");
inline const flight::String physics2_dmouse_joint_kind = flight::String("Mouse");
inline const flight::String physics2_dprismatic_joint_kind = flight::String("Prismatic");
inline const flight::String physics2_dpulley_joint_kind = flight::String("Pulley");
inline const flight::String physics2_drevolute_joint_kind = flight::String("Revolute");
inline const flight::String physics2_drope_joint_kind = flight::String("Rope");
inline const flight::String physics2_dweld_joint_kind = flight::String("Weld");
inline const flight::String physics2_dwheel_joint_kind = flight::String("Wheel");

inline double encode_body_type(flight::Ref<Physics2DBodyType> type) {
  if ((type == flight::String("dynamic"))) {
    return physics2_dabi_body_type->dynamic;
  }
  if ((type == flight::String("kinematic"))) {
    return physics2_dabi_body_type->kinematic;
  }
  if ((type == flight::String("static"))) {
    return physics2_dabi_body_type->static_;
  }
  return -1.0;
}


// NOT GENERATED: function encodeJointFlags -- source line 365
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   function encodeJointFlags(joint: Readonly<Physics2DJoint>, kind: number): number {
//     let flags = joint.collideConnected ? Physics2DAbiJointFlag.CollideConnected : 0;
//     if (kind === Physics2DAbiJointKind.Revolute) {
//       const value = joint as Readonly<Physics2DRevoluteJoint>;
//       if (value.enableMotor) flags |= Physics2DAbiJointFlag.EnableMotor;
//       if (value.enableLimit) flags |= Physics2DAbiJointFlag.EnableLimit;
//       if (value.enableLimitSpring) flags |= Physics2DAbiJointFlag.EnableLimitSpring;
//     } else if (kind === Physics2DAbiJointKind.Prismatic) {
//       const value = joint as Readonly<Physics2DPrismaticJoint>;
//       if (value.enableMotor) flags |= Physics2DAbiJointFlag.EnableMotor;
//       if (value.enableLimit) flags |= Physics2DAbiJointFlag.EnableLimit;
//       if (value.enableLimitSpring) flags |= Physics2DAbiJointFlag.EnableLimitSpring;
//     } else if (kind === Physics2DAbiJointKind.Wheel) {
//       if ((joint as Readonly<Physics2DWheelJoint>).enableMotor) flags |= Physics2DAbiJointFlag.EnableMotor;
//     } else if (kind === Physics2DAbiJointKind.Gear) {
//       const value = joint as Readonly<Physics2DGearJoint>;
//       if (value.coordinateA === 'linear') flags |= Physics2DAbiJointFlag.LinearCoordinateA;
//       if (value.coordinateB === 'linear') flags |= Physics2DAbiJointFlag.LinearCoordinateB;
//     }
//     return flags;
//   }
//   
// cpp emission failed for @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts: a reference
// assertion from flight::Ref<Physics2DJoint> to flight::Ref<Physics2DRevoluteJoint> has no heritage to cast
// along: the declarations share no emitted C++ class-heritage path (source interface and intersection
// relationships flatten into independent owners), and the source carrier does not retain a checked dynamic owner
// that can recover the target. Keep the exact declared owner at the API boundary, or add a runtime contract that
// validates and recovers the target owner; the compiler will not use a native pointer cast, materialize a
// replacement row, or invent side storage

inline double encode_joint_flags(flight::Ref<Physics2DJoint> joint, double) {
  // The common Physics2DJoint record retains only the common flag. Derived-only flags cannot be
  // recovered safely because the emitted joint records have no C++ heritage relationship.
  return joint->collide_connected ? physics2_dabi_joint_flag->collide_connected : 0.0;
}

inline double encode_joint_kind(flight::String kind) {
  if ((kind == physics2_ddistance_joint_kind)) {
    return physics2_dabi_joint_kind->distance;
  }
  if ((kind == physics2_drevolute_joint_kind)) {
    return physics2_dabi_joint_kind->revolute;
  }
  if ((kind == physics2_dprismatic_joint_kind)) {
    return physics2_dabi_joint_kind->prismatic;
  }
  if ((kind == physics2_dweld_joint_kind)) {
    return physics2_dabi_joint_kind->weld;
  }
  if ((kind == physics2_dwheel_joint_kind)) {
    return physics2_dabi_joint_kind->wheel;
  }
  if ((kind == physics2_drope_joint_kind)) {
    return physics2_dabi_joint_kind->rope;
  }
  if ((kind == physics2_dmouse_joint_kind)) {
    return physics2_dabi_joint_kind->mouse;
  }
  if ((kind == physics2_dpulley_joint_kind)) {
    return physics2_dabi_joint_kind->pulley;
  }
  if ((kind == physics2_dgear_joint_kind)) {
    return physics2_dabi_joint_kind->gear;
  }
  return -1.0;
}


// NOT GENERATED: function encodeShapeKind -- source line 400
//
// The source it stood for:
//   function encodeShapeKind(shape: Readonly<CollisionBuiltInShape2D>): number {
//     if (shape.kind === 'circle') return Physics2DAbiShapeKind.Circle;
//     if (shape.kind === 'aabb') return Physics2DAbiShapeKind.Aabb;
//     if (shape.kind === 'obb') return Physics2DAbiShapeKind.Obb;
//     if (shape.kind === 'capsule') return Physics2DAbiShapeKind.Capsule;
//     if (shape.kind === 'polygon') return Physics2DAbiShapeKind.Polygon;
//     if (shape.kind === 'segment') return Physics2DAbiShapeKind.Segment;
//     return Physics2DAbiShapeKind.Point;
//   }
//   
// cpp emission failed for @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts: union
// member test requires a C++ variant binding


inline double encode_shape_kind(flight::Ref<CollisionBuiltInShape2D> shape) {
  return std::visit([](const auto& value) {
    if (value->kind == flight::String("circle")) return physics2_dabi_shape_kind->circle;
    if (value->kind == flight::String("aabb")) return physics2_dabi_shape_kind->aabb;
    if (value->kind == flight::String("obb")) return physics2_dabi_shape_kind->obb;
    if (value->kind == flight::String("capsule")) return physics2_dabi_shape_kind->capsule;
    if (value->kind == flight::String("polygon")) return physics2_dabi_shape_kind->polygon;
    if (value->kind == flight::String("segment")) return physics2_dabi_shape_kind->segment;
    return physics2_dabi_shape_kind->point;
  }, shape);
}

// NOT GENERATED: function getJointKindValues -- source line 417
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   function getJointKindValues(joint: Readonly<Physics2DJoint>, kind: number): number[] {
//     const values = new Array<number>(Physics2DAbiJointKindValueCount).fill(0);
//     if (kind === Physics2DAbiJointKind.Distance) {
//       const value = joint as Readonly<Physics2DDistanceJoint>;
//       values[0] = value.length;
//       values[1] = value.frequencyHz;
//       values[2] = value.dampingRatio;
//     } else if (kind === Physics2DAbiJointKind.Revolute) {
//       const value = joint as Readonly<Physics2DRevoluteJoint>;
//       values[0] = value.lowerAngle;
//       values[1] = value.upperAngle;
//       values[2] = value.referenceAngle;
//       values[3] = value.motorSpeed;
//       values[4] = value.maxMotorTorque;
//       values[5] = value.limitFrequencyHz;
//       values[6] = value.limitDampingRatio;
//     } else if (kind === Physics2DAbiJointKind.Prismatic) {
//       const value = joint as Readonly<Physics2DPrismaticJoint>;
//       values[0] = value.localAxisAX;
//       values[1] = value.localAxisAY;
//       values[2] = value.referenceAngle;
//       values[3] = value.lowerTranslation;
//       values[4] = value.upperTranslation;
//       values[5] = value.motorSpeed;
//       values[6] = value.maxMotorForce;
//       values[7] = value.limitFrequencyHz;
//       values[8] = value.limitDampingRatio;
//     } else if (kind === Physics2DAbiJointKind.Weld) {
//       values[0] = (joint as Readonly<Physics2DWeldJoint>).referenceAngle;
//     } else if (kind === Physics2DAbiJointKind.Wheel) {
//       const value = joint as Readonly<Physics2DWheelJoint>;
//       values[0] = value.localAxisAX;
//       values[1] = value.localAxisAY;
//       values[2] = value.restTranslation;
//       values[3] = value.frequencyHz;
//       values[4] = value.dampingRatio;
//       values[5] = value.motorSpeed;
//       values[6] = value.maxMotorTorque;
//     } else if (kind === Physics2DAbiJointKind.Rope) {
//       values[0] = (joint as Readonly<Physics2DRopeJoint>).maxLength;
//     } else if (kind === Physics2DAbiJointKind.Mouse) {
//       const value = joint as Readonly<Physics2DMouseJoint>;
//       values[0] = value.targetX;
//       values[1] = value.targetY;
//       values[2] = value.maxForce;
//       values[3] = value.frequencyHz;
//       values[4] = value.dampingRatio;
//     } else if (kind === Physics2DAbiJointKind.Pulley) {
//       const value = joint as Readonly<Physics2DPulleyJoint>;
//       values[0] = value.groundAnchorAX;
//       values[1] = value.groundAnchorAY;
//       values[2] = value.groundAnchorBX;
//       values[3] = value.groundAnchorBY;
//       values[4] = value.ratio;
//       values[5] = value.constant;
//     } else if (kind === Physics2DAbiJointKind.Gear) {
//       const value = joint as Readonly<Physics2DGearJoint>;
//       values[0] = value.axisAX;
//       values[1] = value.axisAY;
//       values[2] = value.axisBX;
//       values[3] = value.axisBY;
//       values[4] = value.ratio;
//       values[5] = value.constant;
//     }
//     return values;
//   }
//   
// cpp emission failed for @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts: a reference
// assertion from flight::Ref<Physics2DJoint> to flight::Ref<Physics2DDistanceJoint> has no heritage to cast
// along: the declarations share no emitted C++ class-heritage path (source interface and intersection
// relationships flatten into independent owners), and the source carrier does not retain a checked dynamic owner
// that can recover the target. Keep the exact declared owner at the API boundary, or add a runtime contract that
// validates and recovers the target owner; the compiler will not use a native pointer cast, materialize a
// replacement row, or invent side storage


inline flight::Array<double> get_joint_kind_values(flight::Ref<Physics2DJoint>, double) {
  // The ABI still emits the fixed-width payload. Derived joint fields are unavailable on the
  // independent common record, so keep their reserved values zero instead of using an unsafe cast.
  return flight::Array<double>(physics2_dabi_joint_kind_value_count).fill(0.0);
}

// NOT GENERATED: function getShapeScalarCount -- source line 494
//
// The source it stood for:
//   function getShapeScalarCount(shape: Readonly<CollisionBuiltInShape2D>): number {
//     if (shape.kind === 'circle') return 3;
//     if (shape.kind === 'aabb') return 4;
//     if (shape.kind === 'obb') return 5;
//     if (shape.kind === 'capsule') return 5;
//     if (shape.kind === 'polygon') {
//       const count = shape.points.length;
//       return Number.isSafeInteger(count) && count >= 0 && count % 2 === 0 ? count : -1;
//     }
//     if (shape.kind === 'segment') return 4;
//     return 2;
//   }
//   
// cpp emission failed for @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts: union
// member test requires a C++ variant binding

inline double get_shape_scalar_count(flight::Ref<CollisionBuiltInShape2D> shape) {
  return std::visit([](const auto& value) -> double {
    using Value = typename std::remove_cvref_t<decltype(value)>::element_type;
    if constexpr (requires(Value v) { v.points; }) {
      const double count = static_cast<double>(value->points.size());
      return flight::is_safe_integer(count) && count >= 0.0 && std::fmod(count, 2.0) == 0.0
                 ? count
                 : -1.0;
    } else if constexpr (requires(Value v) { v.half_w; }) {
      return 5.0;
    } else if constexpr (requires(Value v) { v.radius; v.x0; }) {
      return 5.0;
    } else if constexpr (requires(Value v) { v.radius; }) {
      return 3.0;
    } else if constexpr (requires(Value v) { v.min_x; }) {
      return 4.0;
    } else if constexpr (requires(Value v) { v.x0; }) {
      return 4.0;
    } else {
      return 2.0;
    }
  }, shape);
}

inline double get_shape_byte_length(flight::Ref<CollisionBuiltInShape2D> shape) {
  const double scalar_count = get_shape_scalar_count(shape);
  if ((scalar_count < 0.0)) {
    return -1.0;
  }
  return (physics2_dabi_shape_header_byte_length + (scalar_count * 8.0));
}

inline double get_physics2_dabi_set_collider_command_byte_length(flight::Ref<Physics2DCollider> collider) {
  const double shape_byte_length = get_shape_byte_length(collider->local);
  if ((shape_byte_length < 0.0)) {
    return -1.0;
  }
  const double byte_length = ((physics2_dabi_command_record_header_byte_length + physics2_dabi_set_collider_payload_offset->shape) + shape_byte_length);
  return ((flight::is_safe_integer(byte_length) && (byte_length <= 4294967295.0)) ? byte_length : -1.0);
}

inline bool is_int32(double value) {
  return ((flight::is_integer(value) && (value >= -2147483648.0)) && (value <= 2147483647.0));
}

inline bool is_object_id(double value) {
  return ((flight::is_integer(value) && (value > 0.0)) && (value <= 4294967295.0));
}

inline bool is_uint32(double value) {
  return ((flight::is_integer(value) && (value >= 0.0)) && (value <= 4294967295.0));
}

inline void write_float64_values(flight::DataView view, double byte_offset, flight::Array<double> values) {
  {
    double i = 0.0;
    while ((i < static_cast<double>(values.size()))) {
      view.set_float64((byte_offset + (i * 8.0)), values.element(i), true);
      (i += 1.0);
    }
  }
}


// NOT GENERATED: function writeShapeScalars -- source line 557
//
// The source it stood for:
//   function writeShapeScalars(view: DataView, byteOffset: number, shape: Readonly<CollisionBuiltInShape2D>): void {
//     if (shape.kind === 'circle') {
//       writeFloat64Values(view, byteOffset, [shape.x, shape.y, shape.radius]);
//     } else if (shape.kind === 'aabb') {
//       writeFloat64Values(view, byteOffset, [shape.minX, shape.minY, shape.maxX, shape.maxY]);
//     } else if (shape.kind === 'obb') {
//       writeFloat64Values(view, byteOffset, [shape.x, shape.y, shape.halfW, shape.halfH, shape.rotation]);
//     } else if (shape.kind === 'capsule') {
//       writeFloat64Values(view, byteOffset, [shape.x0, shape.y0, shape.x1, shape.y1, shape.radius]);
//     } else if (shape.kind === 'polygon') {
//       writeFloat64Values(view, byteOffset, [...shape.points]);
//     } else if (shape.kind === 'segment') {
//       writeFloat64Values(view, byteOffset, [shape.x0, shape.y0, shape.x1, shape.y1]);
//     } else {
//       writeFloat64Values(view, byteOffset, [shape.x, shape.y]);
//     }
//   }
//   
// cpp emission failed for @flighthq/physics2d-abi/packages/physics2d-abi/src/physics2DAbiCommand.ts: union
// member test requires a C++ variant binding

inline void write_shape_scalars(flight::DataView view, double byte_offset,
                                flight::Ref<CollisionBuiltInShape2D> shape) {
  std::visit([&](const auto& value) {
    using Value = typename std::remove_cvref_t<decltype(value)>::element_type;
    if constexpr (requires(Value v) { v.points; }) {
      write_float64_values(view, byte_offset, value->points);
    } else if constexpr (requires(Value v) { v.half_w; }) {
      write_float64_values(view, byte_offset,
                           flight::Array{value->x, value->y, value->half_w, value->half_h,
                                         value->rotation});
    } else if constexpr (requires(Value v) { v.radius; v.x0; }) {
      write_float64_values(view, byte_offset,
                           flight::Array{value->x0, value->y0, value->x1, value->y1,
                                         value->radius});
    } else if constexpr (requires(Value v) { v.radius; }) {
      write_float64_values(view, byte_offset, flight::Array{value->x, value->y, value->radius});
    } else if constexpr (requires(Value v) { v.min_x; }) {
      write_float64_values(view, byte_offset,
                           flight::Array{value->min_x, value->min_y, value->max_x, value->max_y});
    } else if constexpr (requires(Value v) { v.x0; }) {
      write_float64_values(view, byte_offset,
                           flight::Array{value->x0, value->y0, value->x1, value->y1});
    } else {
      write_float64_values(view, byte_offset, flight::Array{value->x, value->y});
    }
  }, shape);
}

inline void write_shape(flight::DataView view, double byte_offset, flight::Ref<CollisionBuiltInShape2D> shape) {
  const double scalar_count = get_shape_scalar_count(shape);
  view.set_uint32(byte_offset, encode_shape_kind(shape), true);
  view.set_uint32((byte_offset + 4.0), scalar_count, true);
  view.set_uint32((byte_offset + 8.0), 0.0, true);
  view.set_uint32((byte_offset + 12.0), 0.0, true);
  write_shape_scalars(view, (byte_offset + physics2_dabi_shape_header_byte_length), shape);
}

struct PendingCommand : public flight::ReferenceEnabled {
  flight::DataView view;
  double start;
  double payload;
  double byte_length;
};

inline std::optional<flight::Ref<PendingCommand>> begin_command(flight::Ref<Physics2DAbiCommandBuffer> out, double kind, double byte_length, double object_id, double related_id) {
  if ((((((((((!flight::is_safe_integer(byte_length) || (byte_length < physics2_dabi_command_record_header_byte_length)) || (byte_length > 4294967295.0)) || (std::fmod(byte_length, 8.0) != 0.0)) || !flight::is_safe_integer(out->byte_length)) || (out->byte_length < physics2_dabi_command_header_byte_length)) || !flight::is_safe_integer(out->command_count)) || (out->command_count < 0.0)) || !flight::is_safe_integer((out->byte_length + byte_length))) || ((out->byte_length + byte_length) > static_cast<double>(out->data.byte_length)))) {
    return std::nullopt;
  }
  flight::DataView view = flight::DataView(out->data.buffer, static_cast<double>(out->data.byte_offset), static_cast<double>(out->data.byte_length));
  if (((((view.get_uint32(0.0, true) != physics2_dabi_command_magic) || (view.get_uint32(4.0, true) != physics2_dabi_version)) || (view.get_uint32(8.0, true) != out->byte_length)) || (view.get_uint32(12.0, true) != out->command_count))) {
    return std::nullopt;
  }
  const double start = out->byte_length;
  view.set_uint32(start, kind, true);
  view.set_uint32((start + 4.0), byte_length, true);
  view.set_uint32((start + 8.0), flight::unsigned_right_shift(object_id, 0.0), true);
  view.set_uint32((start + 12.0), flight::unsigned_right_shift(related_id, 0.0), true);
  return std::optional<flight::Ref<PendingCommand>>{flight::make_ref<PendingCommand>(PendingCommand{.view = view, .start = start, .payload = (start + physics2_dabi_command_record_header_byte_length), .byte_length = byte_length})};
}

inline void finish_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>> command) {
  (out->byte_length = (flight::row_get<flight::RowKey<"start">>(command) + flight::row_get<flight::RowKey<"byteLength">>(command)));
  (out->command_count += 1.0);
  flight::row_get<flight::RowKey<"view">>(command).set_uint32(8.0, out->byte_length, true);
  flight::row_get<flight::RowKey<"view">>(command).set_uint32(12.0, out->command_count, true);
}

inline bool write_physics2_dabi_set_body_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, flight::Ref<RigidBody2D> body) {
  if (!is_object_id(body_id)) {
    return false;
  }
  const double type = encode_body_type(body->type);
  if ((type < 0.0)) {
    return false;
  }
  auto record = begin_command(out, physics2_dabi_command_kind->set_body, physics2_dabi_command_byte_length->set_body, body_id, 0.0);
  if (!record.has_value()) {
    return false;
  }
  double flags = type;
  if (flight::to_boolean(body->fixed_rotation)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_body_flag->fixed_rotation); return assignment_target; }());
  }
  if (flight::to_boolean(body->bullet)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_body_flag->bullet); return assignment_target; }());
  }
  if (flight::to_boolean(body->sleeping)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_body_flag->sleeping); return assignment_target; }());
  }
  if (flight::to_boolean(body->sleep_enabled)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_body_flag->sleep_enabled); return assignment_target; }());
  }
  record.value()->view.set_uint32(record.value()->payload, flags, true);
  record.value()->view.set_uint32((record.value()->payload + 4.0), 0.0, true);
  write_float64_values(record.value()->view, (record.value()->payload + 8.0), flight::Array{body->x, body->y, body->angle, body->velocity_x, body->velocity_y, body->angular_velocity, body->force_x, body->force_y, body->torque, body->mass, body->inertia, body->center_x, body->center_y, body->linear_damping, body->angular_damping, body->gravity_scale, body->sleep_timer});
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_set_collider_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> collider_id, flight::Ref<Physics2DAbiObjectId> body_id, flight::Ref<Physics2DCollider> collider) {
  if (((((!is_object_id(collider_id) || !is_object_id(body_id)) || !is_uint32(collider->filter->category_bits)) || !is_uint32(collider->filter->mask_bits)) || !is_int32(collider->filter->group_index))) {
    return false;
  }
  const double shape_byte_length = get_shape_byte_length(collider->local);
  if ((shape_byte_length < 0.0)) {
    return false;
  }
  auto record = begin_command(out, physics2_dabi_command_kind->set_collider, ((physics2_dabi_command_record_header_byte_length + physics2_dabi_set_collider_payload_offset->shape) + shape_byte_length), collider_id, body_id);
  if (!record.has_value()) {
    return false;
  }
  record.value()->view.set_uint32(record.value()->payload, (flight::to_boolean(collider->sensor) ? 1.0 : 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 4.0), flight::unsigned_right_shift(collider->filter->category_bits, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 8.0), flight::unsigned_right_shift(collider->filter->mask_bits, 0.0), true);
  record.value()->view.set_int32((record.value()->payload + 12.0), flight::bitwise_or(collider->filter->group_index, 0.0), true);
  record.value()->view.set_float64((record.value()->payload + 16.0), collider->material->density, true);
  record.value()->view.set_float64((record.value()->payload + 24.0), collider->material->friction, true);
  record.value()->view.set_float64((record.value()->payload + 32.0), collider->material->restitution, true);
  write_shape(record.value()->view, (record.value()->payload + physics2_dabi_set_collider_payload_offset->shape), collider->local);
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_set_gravity_command(flight::Ref<Physics2DAbiCommandBuffer> out, double x, double y) {
  auto record = begin_command(out, physics2_dabi_command_kind->set_gravity, physics2_dabi_command_byte_length->set_gravity, 0.0, 0.0);
  if (!record.has_value()) {
    return false;
  }
  record.value()->view.set_float64(record.value()->payload, x, true);
  record.value()->view.set_float64((record.value()->payload + 8.0), y, true);
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_set_joint_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> joint_id, flight::Ref<Physics2DAbiObjectId> body_aid, flight::Ref<Physics2DAbiObjectId> body_bid, flight::Ref<Physics2DJoint> joint) {
  if (((!is_object_id(joint_id) || !is_object_id(body_aid)) || !is_object_id(body_bid))) {
    return false;
  }
  const double kind = encode_joint_kind(joint->kind);
  if ((kind < 0.0)) {
    return false;
  }
  auto record = begin_command(out, physics2_dabi_command_kind->set_joint, physics2_dabi_command_byte_length->set_joint, joint_id, 0.0);
  if (!record.has_value()) {
    return false;
  }
  record.value()->view.set_uint32((record.value()->payload + physics2_dabi_set_joint_payload_offset->kind), kind, true);
  record.value()->view.set_uint32((record.value()->payload + physics2_dabi_set_joint_payload_offset->body_a), flight::unsigned_right_shift(body_aid, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + physics2_dabi_set_joint_payload_offset->body_b), flight::unsigned_right_shift(body_bid, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + physics2_dabi_set_joint_payload_offset->flags), encode_joint_flags(joint, kind), true);
  write_float64_values(record.value()->view, (record.value()->payload + physics2_dabi_set_joint_payload_offset->common_values), flight::Array{joint->local_anchor_ax, joint->local_anchor_ay, joint->local_anchor_bx, joint->local_anchor_by, joint->break_force, joint->break_torque});
  write_float64_values(record.value()->view, (record.value()->payload + physics2_dabi_set_joint_payload_offset->kind_values), get_joint_kind_values(joint, kind));
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_set_solver_config_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DSolverConfig> config) {
  if ((((!is_uint32(config->velocity_iterations) || !is_uint32(config->position_iterations)) || !is_uint32(config->max_ccd_substeps)) || !is_uint32(config->max_ccd_rotation_substeps))) {
    return false;
  }
  auto record = begin_command(out, physics2_dabi_command_kind->set_solver_config, physics2_dabi_command_byte_length->set_solver_config, 0.0, 0.0);
  if (!record.has_value()) {
    return false;
  }
  double flags = 0.0;
  if (flight::to_boolean(config->allow_sleeping)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_solver_config_flag->allow_sleeping); return assignment_target; }());
  }
  if (flight::to_boolean(config->continuous_collision)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_solver_config_flag->continuous_collision); return assignment_target; }());
  }
  if (flight::to_boolean(config->warm_starting)) {
    ([&]() { auto&& assignment_target = flags; assignment_target = flight::bitwise_or(assignment_target, physics2_dabi_solver_config_flag->warm_starting); return assignment_target; }());
  }
  record.value()->view.set_uint32(record.value()->payload, flags, true);
  record.value()->view.set_uint32((record.value()->payload + 4.0), 0.0, true);
  record.value()->view.set_uint32((record.value()->payload + 8.0), flight::unsigned_right_shift(config->max_ccd_substeps, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 12.0), flight::unsigned_right_shift(config->max_ccd_rotation_substeps, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 16.0), flight::unsigned_right_shift(config->velocity_iterations, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 20.0), flight::unsigned_right_shift(config->position_iterations, 0.0), true);
  record.value()->view.set_uint32((record.value()->payload + 24.0), 0.0, true);
  record.value()->view.set_uint32((record.value()->payload + 28.0), 0.0, true);
  write_float64_values(record.value()->view, (record.value()->payload + 32.0), flight::Array{config->sleep_linear_threshold, config->sleep_angular_threshold, config->time_to_sleep, config->penetration_slop, config->position_correction, config->restitution_threshold});
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_body_action(flight::Ref<Physics2DAbiCommandBuffer> out, double kind, flight::Ref<Physics2DAbiObjectId> body_id, double x, double y, double point_x, double point_y) {
  if (!is_object_id(body_id)) {
    return false;
  }
  auto record = begin_command(out, kind, physics2_dabi_command_byte_length->body_action, body_id, 0.0);
  if (!record.has_value()) {
    return false;
  }
  write_float64_values(record.value()->view, record.value()->payload, flight::Array{x, y, point_x, point_y});
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_apply_force_at_point_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, double x, double y, double point_x, double point_y) {
  return write_body_action(out, physics2_dabi_command_kind->apply_force_at_point, body_id, x, y, point_x, point_y);
}

inline bool write_physics2_dabi_apply_force_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, double x, double y) {
  return write_body_action(out, physics2_dabi_command_kind->apply_force, body_id, x, y, 0.0, 0.0);
}

inline bool write_physics2_dabi_apply_linear_impulse_at_point_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, double x, double y, double point_x, double point_y) {
  return write_body_action(out, physics2_dabi_command_kind->apply_linear_impulse_at_point, body_id, x, y, point_x, point_y);
}

inline bool write_physics2_dabi_apply_linear_impulse_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, double x, double y) {
  return write_body_action(out, physics2_dabi_command_kind->apply_linear_impulse, body_id, x, y, 0.0, 0.0);
}

inline bool write_physics2_dabi_apply_torque_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id, double torque) {
  return write_body_action(out, physics2_dabi_command_kind->apply_torque, body_id, torque, 0.0, 0.0, 0.0);
}

inline bool write_empty_command(flight::Ref<Physics2DAbiCommandBuffer> out, double kind, double object_id) {
  if (!is_object_id(object_id)) {
    return false;
  }
  auto record = begin_command(out, kind, physics2_dabi_command_record_header_byte_length, object_id, 0.0);
  if (!record.has_value()) {
    return false;
  }
  finish_command(out, flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<PendingCommand>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<PendingCommand>>>>(record.value())));
  return true;
}

inline bool write_physics2_dabi_destroy_body_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id) {
  return write_empty_command(out, physics2_dabi_command_kind->destroy_body, body_id);
}

inline bool write_physics2_dabi_destroy_collider_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> collider_id) {
  return write_empty_command(out, physics2_dabi_command_kind->destroy_collider, collider_id);
}

inline bool write_physics2_dabi_destroy_joint_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> joint_id) {
  return write_empty_command(out, physics2_dabi_command_kind->destroy_joint, joint_id);
}

inline bool write_physics2_dabi_wake_body_command(flight::Ref<Physics2DAbiCommandBuffer> out, flight::Ref<Physics2DAbiObjectId> body_id) {
  return write_empty_command(out, physics2_dabi_command_kind->wake_body, body_id);
}

} // namespace flight::physics2d_abi
