// Generated by @flighthq/tool-compiler from @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts#NodeInteractiveStateBinding at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: interface InteractiveStateRuntime -- source line 27
//   missing: function applyCorePropertyImmediately -- source line 129
//   missing: function applyCoreProperty -- source line 113
//   missing: function getActiveLayers -- source line 263
//   missing: function collectExtensionFieldNames -- source line 240
//   missing: function hasInteractiveStateProperty -- source line 278
//   missing: function applyNodeInteractiveStates -- source line 41
//   missing: function disposeNodeInteractiveStateBinding -- source line 85
//   missing: function buildInteractiveStateRuntime -- source line 141
#include <flight/any.hpp>
#include <flight/boolean.hpp>
#include <flight/erased_ref.hpp>
#include <flight/record.hpp>
#include <optional>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/node_interactive_state_binding.hpp>

#include <flight/types/node.hpp>

#include <flight/types/flight_document_schema_registry.hpp>

#include <flight/types/flight_document_interactive_state.hpp>

#include <flight/types/flight_document_field_schema.hpp>

#include <flight/types/entity.hpp>

namespace flight::interaction {

using flight::types::FlightDocumentFields;
using flight::types::FlightDocumentInteractiveStateTransitionDescriptor;
using flight::types::FlightDocumentInteractiveStates;
using flight::types::FlightDocumentSchemaRegistry;
using flight::types::NodeAny;
using flight::types::NodeInteractiveStateBinding;
using flight::types::NodeInteractiveStateExplanation;
using flight::types::NodeInteractiveStateExtensionRuntime;
using flight::types::NodeInteractiveStateFlags;
using flight::types::entity_runtime_key;

struct InteractiveExtension;
struct InteractiveStateRuntime;
struct BuildResult;

struct InteractiveExtension : public flight::ReferenceEnabled {
  flight::Ref<FlightDocumentFields> base;
  flight::String kind;
  flight::Ref<NodeInteractiveStateExtensionRuntime> runtime;
};


// NOT GENERATED: interface InteractiveStateRuntime -- source line 27
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   interface InteractiveStateRuntime extends NodeInteractiveStateBindingRuntime {
//     base: Partial<Record<NodeInteractiveStateProperty, NodeInteractiveStateTransitionValue>>;
//     extensions: InteractiveExtension[];
//     flags: NodeInteractiveStateFlags;
//     node: NodeAny;
//     states: Readonly<FlightDocumentInteractiveStates>;
//     transition: Readonly<NodeInteractiveStateTransition> | null;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts:
// Partial<Record<K, V>> has an open member set with no fixed shape: a JavaScript dictionary's keys are optional
// already, so Partial adds no member set to recover -- it widens each value to admit undefined, and that
// widening is what the runtime record cannot hold. Declare the members the code reads, or use the record
// directly through its key where the code only reads
struct InteractiveStateRuntime;

struct BuildResult : public flight::ReferenceEnabled {
  std::optional<flight::Ref<NodeInteractiveStateExplanation>> explanation;
  std::optional<flight::Ref<InteractiveStateRuntime>> runtime;
};


// NOT GENERATED: function applyCorePropertyImmediately -- source line 129
// refusal: cpp-erased-record-assertion-unrepresented [source-portability]
//
// The source it stood for:
//   function applyCorePropertyImmediately(
//     node: NodeAny,
//     property: NodeInteractiveStateProperty,
//     value: NodeInteractiveStateTransitionValue,
//   ): void {
//     const target = node as unknown as Record<NodeInteractiveStateProperty, NodeInteractiveStateTransitionValue>;
//     if (Object.is(target[property], value)) return;
//     target[property] = value;
//     if (property === 'alpha' || property === 'visible') invalidateNodeAppearance(node);
//     else invalidateNodeLocalTransform(node);
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts: an
// erased assertion hides the represented source carrier flight::Ref<NodeAny> before naming
// flight::Record<flight::Ref<NodeInteractiveStateProperty>, flight::Ref<NodeInteractiveStateTransitionValue>>,
// but a Flight object reference and Record keyed storage are not representation-equivalent. Keep the exact
// Record carrier from its construction boundary, or keep a finite key union on a typed object and dispatch to
// its declared fields; the compiler will not cast between owners, copy or materialize replacement keyed storage,
// or add side storage


// NOT GENERATED: function applyCoreProperty -- source line 113
// refusal: cpp-erased-record-assertion-unrepresented [source-portability]
//
// The source it stood for:
//   function applyCoreProperty(
//     runtime: InteractiveStateRuntime,
//     property: NodeInteractiveStateProperty,
//     value: NodeInteractiveStateTransitionValue,
//   ): void {
//     const target = runtime.node as unknown as Record<NodeInteractiveStateProperty, unknown>;
//     const from = target[property];
//     if ((typeof from !== 'boolean' && typeof from !== 'number') || Object.is(from, value)) return;
//     const apply = (next: NodeInteractiveStateTransitionValue = value) => {
//       if (runtime.disposed || typeof next !== typeof from) return;
//       applyCorePropertyImmediately(runtime.node, property, next);
//     };
//     if (runtime.transition === null) apply();
//     else runtime.transition.run({ apply, from, property, target: runtime.node, value });
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts: an
// erased assertion hides the represented source carrier flight::Ref<NodeAny> before naming
// flight::Record<flight::Ref<NodeInteractiveStateProperty>, flight::Any>, but a Flight object reference and
// Record keyed storage are not representation-equivalent. Keep the exact Record carrier from its construction
// boundary, or keep a finite key union on a typed object and dispatch to its declared fields; the compiler will
// not cast between owners, copy or materialize replacement keyed storage, or add side storage

inline void dispose_extensions(flight::Array<flight::Ref<InteractiveExtension>> extensions) {
  for (auto extension : extensions) {
    extension->runtime->dispose();
  }
}


// NOT GENERATED: function getActiveLayers -- source line 263
// refusal: cpp-presence-test-without-absence-storage [compiler-restriction]
//
// The source it stood for:
//   function getActiveLayers(
//     states: Readonly<FlightDocumentInteractiveStates>,
//     flags: Readonly<NodeInteractiveStateFlags>,
//   ): readonly Readonly<FlightDocumentInteractiveState>[] {
//     if (flags.disabled) return states.disabled === null ? [] : [states.disabled];
//     const out: Readonly<FlightDocumentInteractiveState>[] = [];
//     if (flags.hovered && states.hover !== null) out.push(states.hover);
//     if (flags.pressed && states.pressed !== null) out.push(states.pressed);
//     return out;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts: a
// presence test against null has no absence channel in the emitted C++ storage for property

inline flight::Ref<InteractiveStateRuntime> get_interactive_state_runtime(flight::Ref<NodeInteractiveStateBinding> binding) {
  (void)binding;
  throw flight::Error(flight::String(
      "Interactive state runtime recovery requires checked derived-runtime ownership"));
}

inline bool same_flags(flight::Ref<NodeInteractiveStateFlags> left, flight::Ref<NodeInteractiveStateFlags> right) {
  return (((left->disabled == right->disabled) && (left->hovered == right->hovered)) && (left->pressed == right->pressed));
}

inline flight::Array<flight::String> interactive_state_phases = flight::Array<flight::String>{flight::String("disabled"), flight::String("hover"), flight::String("pressed")};


// NOT GENERATED: function collectExtensionFieldNames -- source line 240
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   function collectExtensionFieldNames(states: Readonly<FlightDocumentInteractiveStates>): Map<string, readonly string[]> {
//     const names = new Map<string, string[]>();
//     for (const phase of INTERACTIVE_STATE_PHASES) {
//       const state = states[phase];
//       if (state === null) continue;
//       for (const extension of state.extensions) {
//         let fieldNames = names.get(extension.kind);
//         if (fieldNames === undefined) {
//           fieldNames = [];
//           names.set(extension.kind, fieldNames);
//         }
//         for (const name of Object.keys(extension.fields)) {
//           if (!fieldNames.includes(name)) fieldNames.push(name);
//         }
//       }
//     }
//     return names;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts:
// contextual optionalSingle construction requires expression type evidence


// NOT GENERATED: function hasInteractiveStateProperty -- source line 278
// refusal: cpp-presence-test-without-absence-storage [compiler-restriction]
//
// The source it stood for:
//   function hasInteractiveStateProperty(
//     states: Readonly<FlightDocumentInteractiveStates>,
//     property: NodeInteractiveStateProperty,
//   ): boolean {
//     for (const phase of INTERACTIVE_STATE_PHASES) {
//       if (states[phase]?.[property] !== undefined) return true;
//     }
//     return false;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts: a
// presence test against undefined has no absence channel in the emitted C++ storage for element

inline flight::Array<flight::String> interactive_state_properties = flight::Array<flight::String>{flight::String("alpha"), flight::String("scaleX"), flight::String("scaleY"), flight::String("visible"), flight::String("x"), flight::String("y")};


// NOT GENERATED: function applyNodeInteractiveStates -- source line 41
// refusal: cpp-contextual-union-inequivalent [source-portability]
//
// The source it stood for:
//   export function applyNodeInteractiveStates(
//     binding: NodeInteractiveStateBinding,
//     flags: Readonly<NodeInteractiveStateFlags>,
//   ): boolean {
//     const runtime = getInteractiveStateRuntime(binding);
//     if (runtime.disposed) return false;
//     if (sameFlags(runtime.flags, flags)) return true;
//   
//     const layers = getActiveLayers(runtime.states, flags);
//     for (const property of INTERACTIVE_STATE_PROPERTIES) {
//       const base = runtime.base[property];
//       if (base === undefined) continue;
//       let value = base;
//       for (const layer of layers) {
//         const next = layer[property];
//         if (next !== undefined) value = next;
//       }
//       applyCoreProperty(runtime, property, value);
//     }
//   
//     for (const extension of runtime.extensions) {
//       const fields = { ...extension.base };
//       for (const layer of layers) {
//         const descriptor = layer.extensions.find((entry) => entry.kind === extension.kind);
//         if (descriptor !== undefined) Object.assign(fields, descriptor.fields);
//       }
//       if (!extension.runtime.apply(fields, runtime.transition)) return false;
//     }
//   
//     runtime.flags = { ...flags };
//     return true;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts:
// contextual C++ union conversion requires equivalent source union evidence: target optionalVariant carriers
// [bool, double] from element source optionalSingle carriers [flight::Ref<NodeInteractiveStateTransitionValue>].
// Narrow or convert the source expression so each of its alternatives names exactly one destination union
// alternative. The carrier lists show which alternatives lack an exact carrier; preserve the declared collection
// or member union alias before flow expansion. For a Map or WeakMap lookup followed by a rebind, ensure every
// rebound member already has the declared value owner member's carrier -- a Readonly structural view does not
// become a mutable nominal Ref.


// NOT GENERATED: function disposeNodeInteractiveStateBinding -- source line 85
// refusal: cpp-contextual-union-inequivalent [source-portability]
//
// The source it stood for:
//   export function disposeNodeInteractiveStateBinding(binding: NodeInteractiveStateBinding): void {
//     const runtime = getInteractiveStateRuntime(binding);
//     if (runtime.disposed) return;
//     for (const property of INTERACTIVE_STATE_PROPERTIES) {
//       const value = runtime.base[property];
//       if (value !== undefined) applyCorePropertyImmediately(runtime.node, property, value);
//     }
//     for (const extension of runtime.extensions) {
//       extension.runtime.apply(extension.base, null);
//       extension.runtime.dispose();
//     }
//     runtime.extensions.length = 0;
//     runtime.disposed = true;
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts:
// contextual C++ union conversion requires equivalent source union evidence: target optionalVariant carriers
// [bool, double] from element source optionalSingle carriers [flight::Ref<NodeInteractiveStateTransitionValue>].
// Narrow or convert the source expression so each of its alternatives names exactly one destination union
// alternative. The carrier lists show which alternatives lack an exact carrier; preserve the declared collection
// or member union alias before flow expansion. For a Map or WeakMap lookup followed by a rebind, ensure every
// rebound member already has the declared value owner member's carrier -- a Readonly structural view does not
// become a mutable nominal Ref.


// NOT GENERATED: function buildInteractiveStateRuntime -- source line 141
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   function buildInteractiveStateRuntime(
//     node: NodeAny,
//     interactiveStates: Readonly<FlightDocumentInteractiveStates>,
//     schemas: Readonly<FlightDocumentSchemaRegistry>,
//     transitionDescriptor: Readonly<FlightDocumentInteractiveStateTransitionDescriptor> | null,
//   ): BuildResult {
//     const base: InteractiveStateRuntime['base'] = {};
//     for (const property of INTERACTIVE_STATE_PROPERTIES) {
//       if (!hasInteractiveStateProperty(interactiveStates, property)) continue;
//       const value = (node as unknown as Record<string, unknown>)[property];
//       if (typeof value !== 'boolean' && typeof value !== 'number') {
//         return {
//           explanation: {
//             kind: node.kind,
//             property,
//             reason: NodeInteractiveStateRefusalReason.PropertyTargetUnsupported,
//           },
//           runtime: null,
//         };
//       }
//       base[property] = value;
//     }
//   
//     let transition: Readonly<NodeInteractiveStateTransition> | null = null;
//     if (transitionDescriptor !== null) {
//       const schema = getRegistryTableEntry(schemas.interactiveStateTransitionSchemas, transitionDescriptor.kind);
//       if (schema === null) {
//         return {
//           explanation: {
//             kind: transitionDescriptor.kind,
//             reason: NodeInteractiveStateRefusalReason.TransitionKindUnregistered,
//           },
//           runtime: null,
//         };
//       }
//       transition = schema.createTransition(transitionDescriptor.fields);
//       if (transition === null) {
//         return {
//           explanation: {
//             kind: transitionDescriptor.kind,
//             reason: NodeInteractiveStateRefusalReason.TransitionCreationFailed,
//           },
//           runtime: null,
//         };
//       }
//     }
//   
//     const extensions: InteractiveExtension[] = [];
//     for (const [kind, fieldNames] of collectExtensionFieldNames(interactiveStates)) {
//       const schema = getRegistryTableEntry(schemas.interactiveStateExtensionSchemas, kind);
//       if (schema === null) {
//         disposeExtensions(extensions);
//         return {
//           explanation: { kind, reason: NodeInteractiveStateRefusalReason.ExtensionKindUnregistered },
//           runtime: null,
//         };
//       }
//       if (!schema.isSupported(node)) {
//         disposeExtensions(extensions);
//         return {
//           explanation: { kind, reason: NodeInteractiveStateRefusalReason.ExtensionTargetUnsupported },
//           runtime: null,
//         };
//       }
//       const extensionRuntime = schema.createExtension(node, fieldNames);
//       if (extensionRuntime === null) {
//         disposeExtensions(extensions);
//         return {
//           explanation: { kind, reason: NodeInteractiveStateRefusalReason.ExtensionCreationFailed },
//           runtime: null,
//         };
//       }
//       const captured: FlightDocumentFields = {};
//       if (!extensionRuntime.capture(captured)) {
//         extensionRuntime.dispose();
//         disposeExtensions(extensions);
//         return {
//           explanation: { kind, reason: NodeInteractiveStateRefusalReason.ExtensionCreationFailed },
//           runtime: null,
//         };
//       }
//       extensions.push({ base: captured, kind, runtime: extensionRuntime });
//     }
//   
//     return {
//       explanation: null,
//       runtime: {
//         base,
//         binding: null,
//         disposed: false,
//         extensions,
//         flags: { disabled: false, hovered: false, pressed: false },
//         node,
//         states: interactiveStates,
//         transition,
//       },
//     };
//   }
//   
// cpp emission failed for @flighthq/interaction/packages/interaction/src/nodeInteractiveStateBinding.ts:
// Partial<Record<K, V>> has an open member set with no fixed shape: a JavaScript dictionary's keys are optional
// already, so Partial adds no member set to recover -- it widens each value to admit undefined, and that
// widening is what the runtime record cannot hold. Declare the members the code reads, or use the record
// directly through its key where the code only reads

inline std::optional<flight::Ref<NodeInteractiveStateBinding>> create_node_interactive_state_binding(flight::Ref<NodeAny> node, flight::Ref<FlightDocumentInteractiveStates> interactive_states, flight::Ref<FlightDocumentSchemaRegistry> schemas, std::optional<std::optional<flight::Ref<FlightDocumentInteractiveStateTransitionDescriptor>>> transition = std::nullopt) {
  (void)node;
  (void)interactive_states;
  (void)schemas;
  (void)transition;
  throw flight::Error(flight::String(
      "Interactive state binding requires runtime support for open partial records"));
}

inline std::optional<flight::Ref<NodeInteractiveStateExplanation>> explain_node_interactive_state_binding(flight::Ref<NodeAny> node, flight::Ref<FlightDocumentInteractiveStates> interactive_states, flight::Ref<FlightDocumentSchemaRegistry> schemas, std::optional<std::optional<flight::Ref<FlightDocumentInteractiveStateTransitionDescriptor>>> transition = std::nullopt) {
  (void)node;
  (void)interactive_states;
  (void)schemas;
  (void)transition;
  throw flight::Error(flight::String(
      "Interactive state explanation requires runtime support for open partial records"));
}

} // namespace flight::interaction
