// Generated by @flighthq/tool-compiler from @flighthq/interaction/packages/interaction/src/spatialQuery.ts#SpatialQuery at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <cmath>
#include <cstdint>
#include <flight/structural_ref.hpp>
#include <optional>
#include <random>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/geometry/rectangle.hpp>
#include <flight/node/bounds_rectangle.hpp>
#include <flight/node/bounds_rectangle_access.hpp>
#include <flight/node/node.hpp>
#include <flight/types/contract.hpp>

namespace flight::interaction {

inline flight::Array<flight::types::Node2D> hit_test_area_query(flight::types::Node2D root, flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Rectangle>>>> rect, std::optional<flight::Array<flight::types::Node2D>> out = std::nullopt) {
  out = out.value_or(flight::Array<flight::types::Node2D>{});
  if (!flight::row_get<flight::RowKey<"enabled">>(root)) {
    return out.value();
  }
  flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Rectangle>>>> world_bounds = flight::node::get_node_world_bounds_rectangle(root);
  if (flight::geometry::intersects_rectangle(flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::types::RectangleLike>>>>(world_bounds), flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::types::RectangleLike>>>>(rect))) {
    out.value().push(root);
  }
  std::optional<flight::Array<flight::types::NodeOf<flight::Ref<flight::types::Node2DTraits>>>> children = flight::row_get<flight::RowKey<"children">>(flight::node::get_node_runtime<flight::Ref<flight::types::Node2DTraits>>(root));
  if (children.has_value()) {
    for (auto child : children.value()) {
      hit_test_area_query(flight::structural_ref_cast<flight::types::Node2D>(child), rect, out.value());
    }
  }
  return out.value();
}

inline flight::Array<flight::types::Node2D> hit_test_area_query_circle(flight::types::Node2D root, double cx, double cy, double radius, std::optional<flight::Array<flight::types::Node2D>> out = std::nullopt) {
  out = out.value_or(flight::Array<flight::types::Node2D>{});
  if (!flight::row_get<flight::RowKey<"enabled">>(root)) {
    return out.value();
  }
  flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Rectangle>>>> b = flight::node::get_node_world_bounds_rectangle(root);
  const double near_x = flight::maximum(flight::row_get<flight::RowKey<"x">>(b), flight::minimum(cx, (flight::row_get<flight::RowKey<"x">>(b) + flight::row_get<flight::RowKey<"width">>(b))));
  const double near_y = flight::maximum(flight::row_get<flight::RowKey<"y">>(b), flight::minimum(cy, (flight::row_get<flight::RowKey<"y">>(b) + flight::row_get<flight::RowKey<"height">>(b))));
  const double dx = (cx - near_x);
  const double dy = (cy - near_y);
  if ((((dx * dx) + (dy * dy)) <= (radius * radius))) {
    out.value().push(root);
  }
  std::optional<flight::Array<flight::types::NodeOf<flight::Ref<flight::types::Node2DTraits>>>> children = flight::row_get<flight::RowKey<"children">>(flight::node::get_node_runtime<flight::Ref<flight::types::Node2DTraits>>(root));
  if (children.has_value()) {
    for (auto child : children.value()) {
      hit_test_area_query_circle(flight::structural_ref_cast<flight::types::Node2D>(child), cx, cy, radius, out.value());
    }
  }
  return out.value();
}

} // namespace flight::interaction
