// Generated by @flighthq/tool-compiler from @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts#QuadBatch at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function copyLocalBoundsRectangle -- source line 75
//   missing: function computeQuadBatchLocalBoundsRectangle -- source line 117
//   missing: function getQuadBatchRuntime -- source line 267
//   missing: function hitTestQuadBatchPointXY -- source line 357
//   missing: function initializeQuadBatchData -- source line 408
//   missing: function createQuadBatchData -- source line 201
//   missing: function setQuadBatchInstanceTint -- source line 559
//   missing: function setQuadBatchLocalBoundsRectangle -- source line 570
//   missing: variable (binding) -- source line 617
//   missing: function createQuadBatchRuntime -- source line 207
//   missing: function createQuadBatch -- source line 197
//   missing: function enableQuadBatchSignals -- source line 225
//   missing: function getQuadBatchSignals -- source line 272
//   missing: function hitTestQuadBatchPointExactXY -- source line 300
#include <cmath>
#include <cstdint>
#include <flight/symbol.hpp>
#include <flight/weak_map.hpp>
#include <functional>
#include <optional>
#include <random>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/vector2.hpp>

#include <flight/types/tint_material_data.hpp>

#include <flight/types/rectangle.hpp>

#include <flight/types/quad_transform_type.hpp>

#include <flight/types/quad_batch_signals.hpp>

#include <flight/types/partial_node.hpp>

#include <flight/types/node.hpp>

#include <flight/types/entity.hpp>

#include <flight/signals/signal.hpp>

#include <flight/types/quad_batch.hpp>

#include <flight/entity/entity.hpp>
#include <flight/geometry/typedarray.hpp>

namespace flight::quadbatch {

using flight::types::QuadBatchData;
using flight::types::QuadBatchRuntime;
using flight::types::QuadBatchSignals;
using flight::types::QuadTransformType;
using flight::types::EntityConstruction;
using flight::types::Node;
using flight::types::Node2DTraits;
using flight::types::PartialNode;
using flight::types::Rectangle;
using flight::types::MaterialData;
using flight::types::TextureAtlas;
using flight::types::TintMaterialData;
using flight::types::Vector2Like;
using flight::types::BoundsNodeAny;

using flight::signals::create_signal;

using flight::types::QuadBatch;

using flight::entity::allocate_entity;
using flight::entity::finish_entity;

using flight::geometry::reserve_float32_array;
using flight::geometry::reserve_uint16_array;

struct QuadBatchWithSignals;

inline const double quad_vector2_stride = 2.0;

inline const double quad_matrix3_x2_stride = 6.0;

inline const double quad_batch_deleted_id = 65535.0;


// NOT GENERATED: function copyLocalBoundsRectangle -- source line 75
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   function copyLocalBoundsRectangle(out: Rectangle, source: Readonly<Node>): void {
//     const runtime = getNode2DRuntime(source as QuadBatch) as QuadBatchRuntime;
//     if (runtime.localBoundsRectangle !== null) copyRectangle(out, runtime.localBoundsRectangle);
//   }
//   
//   /**
//    * Removes swap-remove holes by compacting all live instances (`[0, instanceCount)`) to the
//    * front of the buffer in index order, skipping entries that have been logically deleted.
//    * This is not needed for swap-remove–only callers, but is useful when stable iteration order
//    * must be restored after a batch of removals. After compaction, `instanceCount` equals the
//    * number of entries whose id is `>= 0`.
//    *
//    * Note: this function does NOT filter by id; it simply copies all `instanceCount` entries to a
//    * fresh contiguous layout. To remove specific entries, call `removeQuadBatchInstance` first, then
//    * compact if needed.
//    */
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<Node2DRuntime> to flight::Ref<QuadBatchRuntime> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage


// NOT GENERATED: function computeQuadBatchLocalBoundsRectangle -- source line 117
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function computeQuadBatchLocalBoundsRectangle(out: Rectangle, source: Readonly<QuadBatch>): void {
//     const { atlas, ids, instanceCount, transforms, transformType } = source.data;
//     if (atlas === null || instanceCount === 0) {
//       out.x = 0;
//       out.y = 0;
//       out.width = 0;
//       out.height = 0;
//       return;
//     }
//     const regions = atlas.regions;
//     const numRegions = regions.length;
//     let minX = Infinity;
//     let minY = Infinity;
//     let maxX = -Infinity;
//     let maxY = -Infinity;
//     if (transformType === 'vector2') {
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         if (region.width <= 0 || region.height <= 0) continue;
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const width = rotated ? region.height : region.width;
//         const height = rotated ? region.width : region.height;
//         const dx = transforms[i * QUAD_VECTOR2_STRIDE];
//         const dy = transforms[i * QUAD_VECTOR2_STRIDE + 1];
//         if (dx < minX) minX = dx;
//         if (dy < minY) minY = dy;
//         const rx = dx + width;
//         const ry = dy + height;
//         if (rx > maxX) maxX = rx;
//         if (ry > maxY) maxY = ry;
//       }
//     } else {
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         if (region.width <= 0 || region.height <= 0) continue;
//         const o = i * QUAD_MATRIX3X2_STRIDE;
//         const a = transforms[o];
//         const b = transforms[o + 1];
//         const c = transforms[o + 2];
//         const d = transforms[o + 3];
//         const tx = transforms[o + 4];
//         const ty = transforms[o + 5];
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const w = rotated ? region.height : region.width;
//         const h = rotated ? region.width : region.height;
//         const x0 = tx;
//         const y0 = ty;
//         const x1 = a * w + tx;
//         const y1 = b * w + ty;
//         const x2 = c * h + tx;
//         const y2 = d * h + ty;
//         const x3 = a * w + c * h + tx;
//         const y3 = b * w + d * h + ty;
//         const qMinX = Math.min(x0, x1, x2, x3);
//         const qMinY = Math.min(y0, y1, y2, y3);
//         const qMaxX = Math.max(x0, x1, x2, x3);
//         const qMaxY = Math.max(y0, y1, y2, y3);
//         if (qMinX < minX) minX = qMinX;
//         if (qMinY < minY) minY = qMinY;
//         if (qMaxX > maxX) maxX = qMaxX;
//         if (qMaxY > maxY) maxY = qMaxY;
//       }
//     }
//     if (minX === Infinity) {
//       out.x = 0;
//       out.y = 0;
//       out.width = 0;
//       out.height = 0;
//     } else {
//       out.x = minX;
//       out.y = minY;
//       out.width = maxX - minX;
//       out.height = maxY - minY;
//     }
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: contextual optionalSingle
// construction requires expression type evidence

inline double get_quad_batch_instance_id(flight::Ref<QuadBatch> source, double index) {
  if (((index < 0.0) || (index >= source->data->instance_count))) {
    return -1.0;
  }
  return source->data->ids.get_index(index);
}

inline bool get_quad_batch_instance_transform(flight::Ref<Vector2Like> out, flight::Ref<QuadBatch> source, double index) {
  flight::Ref<QuadBatchData> object_pattern_value = source->data;
  const double instance_count = object_pattern_value->instance_count;
  flight::Float32Array transforms = object_pattern_value->transforms;
  flight::Ref<QuadTransformType> transform_type = object_pattern_value->transform_type;
  if (((index < 0.0) || (index >= instance_count))) {
    return false;
  }
  if ((transform_type == flight::String("vector2"))) {
    const double o = (index * quad_vector2_stride);
    (out->x = transforms.get_index(o));
    (out->y = transforms.get_index((o + 1.0)));
  }
  else {
    const double o_2 = (index * quad_matrix3_x2_stride);
    (out->x = transforms.get_index((o_2 + 4.0)));
    (out->y = transforms.get_index((o_2 + 5.0)));
  }
  return true;
}


// NOT GENERATED: function getQuadBatchRuntime -- source line 267
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   export function getQuadBatchRuntime(source: Readonly<QuadBatch>): Readonly<QuadBatchRuntime> {
//     return getNode2DRuntime(source) as QuadBatchRuntime;
//   }
//   
//   /** Returns the {@link QuadBatchSignals} attached to `source`, or `null` if not yet enabled. */
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<Node2DRuntime> to flight::Ref<QuadBatchRuntime> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage


// NOT GENERATED: function hitTestQuadBatchPointXY -- source line 357
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function hitTestQuadBatchPointXY(source: Readonly<QuadBatch>, x: number, y: number): number {
//     const { atlas, ids, instanceCount, transforms, transformType } = source.data;
//     if (atlas === null || instanceCount === 0) return -1;
//     const regions = atlas.regions;
//     const numRegions = regions.length;
//     if (transformType === 'vector2') {
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         const dx = transforms[i * QUAD_VECTOR2_STRIDE];
//         const dy = transforms[i * QUAD_VECTOR2_STRIDE + 1];
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const width = rotated ? region.height : region.width;
//         const height = rotated ? region.width : region.height;
//         if (x >= dx && x < dx + width && y >= dy && y < dy + height) return i;
//       }
//     } else {
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         if (region.width <= 0 || region.height <= 0) continue;
//         const o = i * QUAD_MATRIX3X2_STRIDE;
//         const a = transforms[o];
//         const b = transforms[o + 1];
//         const c = transforms[o + 2];
//         const d = transforms[o + 3];
//         const tx = transforms[o + 4];
//         const ty = transforms[o + 5];
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const w = rotated ? region.height : region.width;
//         const h = rotated ? region.width : region.height;
//         const x0 = tx;
//         const y0 = ty;
//         const x1 = a * w + tx;
//         const y1 = b * w + ty;
//         const x2 = c * h + tx;
//         const y2 = d * h + ty;
//         const x3 = a * w + c * h + tx;
//         const y3 = b * w + d * h + ty;
//         const minX = Math.min(x0, x1, x2, x3);
//         const minY = Math.min(y0, y1, y2, y3);
//         const maxX = Math.max(x0, x1, x2, x3);
//         const maxY = Math.max(y0, y1, y2, y3);
//         if (x >= minX && x < maxX && y >= minY && y < maxY) return i;
//       }
//     }
//     return -1;
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: contextual optionalSingle
// construction requires expression type evidence

inline double hit_test_quad_batch_point_xy(flight::Ref<QuadBatch>, double, double) {
  return -1.0;
}

inline double hit_test_quad_batch_point(flight::Ref<QuadBatch> source, flight::Ref<Vector2Like> point) {
  return hit_test_quad_batch_point_xy(source, point->x, point->y);
}


// NOT GENERATED: function initializeQuadBatchData -- source line 408
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   export function initializeQuadBatchData(
//     out: EntityConstruction<QuadBatchData>,
//     data?: Readonly<Partial<QuadBatchData>>,
//   ): void {
//     out.atlas = data?.atlas ?? null;
//     out.ids = data?.ids ?? new Uint16Array();
//     out.instanceCount = data?.instanceCount ?? 0;
//     out.materialData = data?.materialData ?? null;
//     out.transforms = data?.transforms ?? new Float32Array();
//     out.transformType = data?.transformType ?? 'vector2';
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: Partial<T> requires a
// statically resolvable C++ object shape; T is named


// NOT GENERATED: function createQuadBatchData -- source line 201
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   export function createQuadBatchData(data?: Readonly<Partial<QuadBatchData>>): QuadBatchData {
//     const out = allocateEntity<QuadBatchData>();
//     initializeQuadBatchData(out, data);
//     return finishEntity(out);
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: Partial<T> requires a
// statically resolvable C++ object shape; T is named

inline void initialize_quad_batch_signals(flight::Ref<EntityConstruction<flight::Ref<QuadBatchSignals>>> out) {
  (out->on_cleared = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_cleared)>::element_type>>());
  (out->on_instance_appended = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_instance_appended)>::element_type>>());
  (out->on_instance_removed = create_signal<flight::template_argument_t<typename std::remove_cvref_t<decltype(out->on_instance_removed)>::element_type>>());
}

inline flight::Ref<QuadBatchSignals> create_quad_batch_signals() {
  flight::Ref<EntityConstruction<flight::Ref<QuadBatchSignals>>> out = allocate_entity<flight::Ref<QuadBatchSignals>>();
  initialize_quad_batch_signals(out);
  return finish_entity(out);
}

inline void set_quad_batch_instance(flight::Ref<QuadBatch> target, double index, double id, double x, double y) {
  flight::Ref<QuadBatchData> data = target->data;
  if (((index < 0.0) || (index >= data->instance_count))) {
    return;
  }
  ([&]() { auto&& typed_array = data->ids; const auto typed_index = index; const auto typed_value = id; return typed_array.set_index(typed_index, typed_value); }());
  const double o = (index * quad_vector2_stride);
  ([&]() { auto&& typed_array_2 = data->transforms; const auto typed_index_2 = o; const auto typed_value_2 = x; return typed_array_2.set_index(typed_index_2, typed_value_2); }());
  ([&]() { auto&& typed_array_3 = data->transforms; const auto typed_index_3 = (o + 1.0); const auto typed_value_3 = y; return typed_array_3.set_index(typed_index_3, typed_value_3); }());
}

inline void set_quad_batch_instance_matrix(flight::Ref<QuadBatch> target, double index, double id, double a, double b, double c, double d, double tx, double ty) {
  flight::Ref<QuadBatchData> data = target->data;
  if (((index < 0.0) || (index >= data->instance_count))) {
    return;
  }
  ([&]() { auto&& typed_array_4 = data->ids; const auto typed_index_4 = index; const auto typed_value_4 = id; return typed_array_4.set_index(typed_index_4, typed_value_4); }());
  const double o = (index * quad_matrix3_x2_stride);
  ([&]() { auto&& typed_array_5 = data->transforms; const auto typed_index_5 = o; const auto typed_value_5 = a; return typed_array_5.set_index(typed_index_5, typed_value_5); }());
  ([&]() { auto&& typed_array_6 = data->transforms; const auto typed_index_6 = (o + 1.0); const auto typed_value_6 = b; return typed_array_6.set_index(typed_index_6, typed_value_6); }());
  ([&]() { auto&& typed_array_7 = data->transforms; const auto typed_index_7 = (o + 2.0); const auto typed_value_7 = c; return typed_array_7.set_index(typed_index_7, typed_value_7); }());
  ([&]() { auto&& typed_array_8 = data->transforms; const auto typed_index_8 = (o + 3.0); const auto typed_value_8 = d; return typed_array_8.set_index(typed_index_8, typed_value_8); }());
  ([&]() { auto&& typed_array_9 = data->transforms; const auto typed_index_9 = (o + 4.0); const auto typed_value_9 = tx; return typed_array_9.set_index(typed_index_9, typed_value_9); }());
  ([&]() { auto&& typed_array_10 = data->transforms; const auto typed_index_10 = (o + 5.0); const auto typed_value_10 = ty; return typed_array_10.set_index(typed_index_10, typed_value_10); }());
}


// NOT GENERATED: function setQuadBatchInstanceTint -- source line 559
// refusal: cpp-contextual-union-value-type-unrepresented [compiler-restriction]
//
// The source it stood for:
//   export function setQuadBatchInstanceTint(target: QuadBatch, index: number, rgba: number): void {
//     const data = target.data;
//     if (index < 0 || index >= data.instanceCount) return;
//     if (data.materialData === null) data.materialData = new Array(data.instanceCount).fill(null);
//     data.materialData[index] = (() => {
//       const out = allocateEntity<TintMaterialData>();
//       out.tint = rgba >>> 0;
//       return finishEntity(out);
//     })();
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: contextual union value type
// flight::Array is not a represented runtime domain


// NOT GENERATED: function setQuadBatchLocalBoundsRectangle -- source line 570
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   export function setQuadBatchLocalBoundsRectangle(target: QuadBatch, rect: Readonly<Rectangle>): void {
//     const runtime = getNode2DRuntime(target) as QuadBatchRuntime;
//     if (runtime.localBoundsRectangle === null) runtime.localBoundsRectangle = createRectangle();
//     copyRectangle(runtime.localBoundsRectangle, rect);
//     invalidateNodeLocalBounds(target);
//   }
//   
//   /**
//    * Switches `target`'s `transformType`, re-striding the `transforms` buffer in place.
//    * - `'vector2' → 'matrix3x2'`: each existing (x, y) pair is expanded to `[1, 0, 0, 1, x, y]` (identity + translation).
//    * - `'matrix3x2' → 'vector2'`: each matrix is collapsed to its `(tx, ty)` translation, discarding scale/rotation.
//    * Does nothing when `newType` matches the current `transformType`.
//    */
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<Node2DRuntime> to flight::Ref<QuadBatchRuntime> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage

inline void set_quad_batch_transform_type(flight::Ref<QuadBatch> target, flight::Ref<QuadTransformType> new_type) {
  flight::Ref<QuadBatchData> data = target->data;
  if ((data->transform_type == new_type)) {
    return;
  }
  const double count = data->instance_count;
  if ((new_type == flight::String("matrix3x2"))) {
    flight::Float32Array new_transforms = flight::Float32Array((flight::maximum((static_cast<double>(data->transforms.size()) / quad_vector2_stride), count) * quad_matrix3_x2_stride));
    {
      double i = (count - 1.0);
      while ((i >= 0.0)) {
        {
          const double src = (i * quad_vector2_stride);
          const double dst = (i * quad_matrix3_x2_stride);
          const double x = data->transforms.get_index(src);
          const double y = data->transforms.get_index((src + 1.0));
          ([&]() { auto&& typed_array_11 = new_transforms; const auto typed_index_11 = dst; const auto typed_value_11 = 1.0; return typed_array_11.set_index(typed_index_11, typed_value_11); }());
          ([&]() { auto&& typed_array_12 = new_transforms; const auto typed_index_12 = (dst + 1.0); const auto typed_value_12 = 0.0; return typed_array_12.set_index(typed_index_12, typed_value_12); }());
          ([&]() { auto&& typed_array_13 = new_transforms; const auto typed_index_13 = (dst + 2.0); const auto typed_value_13 = 0.0; return typed_array_13.set_index(typed_index_13, typed_value_13); }());
          ([&]() { auto&& typed_array_14 = new_transforms; const auto typed_index_14 = (dst + 3.0); const auto typed_value_14 = 1.0; return typed_array_14.set_index(typed_index_14, typed_value_14); }());
          ([&]() { auto&& typed_array_15 = new_transforms; const auto typed_index_15 = (dst + 4.0); const auto typed_value_15 = x; return typed_array_15.set_index(typed_index_15, typed_value_15); }());
          ([&]() { auto&& typed_array_16 = new_transforms; const auto typed_index_16 = (dst + 5.0); const auto typed_value_16 = y; return typed_array_16.set_index(typed_index_16, typed_value_16); }());
        }
        (i -= 1.0);
      }
    }
    (data->transforms = new_transforms);
  }
  else {
    {
      double i_2 = 0.0;
      while ((i_2 < count)) {
        {
          const double src_2 = (i_2 * quad_matrix3_x2_stride);
          const double dst_2 = (i_2 * quad_vector2_stride);
          ([&]() { auto&& typed_array_17 = data->transforms; const auto typed_index_17 = dst_2; const auto typed_value_17 = data->transforms.get_index((src_2 + 4.0)); return typed_array_17.set_index(typed_index_17, typed_value_17); }());
          ([&]() { auto&& typed_array_18 = data->transforms; const auto typed_index_18 = (dst_2 + 1.0); const auto typed_value_18 = data->transforms.get_index((src_2 + 5.0)); return typed_array_18.set_index(typed_index_18, typed_value_18); }());
        }
        (i_2 += 1.0);
      }
    }
  }
  (data->transform_type = new_type);
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_CAN_ADD_CHILD_COMPUTE_LOCAL_BOUNDS_RECTANGLE_AF1F918F97747DFB
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_CAN_ADD_CHILD_COMPUTE_LOCAL_BOUNDS_RECTANGLE_AF1F918F97747DFB
struct can_add_child_compute_local_bounds_rectangle_af1f918f97747dfb : public flight::ReferenceEnabled {
  std::optional<std::function<bool(std::shared_ptr<Node<flight::Ref<Node2DTraits>>>, std::shared_ptr<Node<flight::Ref<Node2DTraits>>>)>> can_add_child;
  std::optional<std::function<void(flight::Ref<Rectangle>, flight::Ref<BoundsNodeAny>)>> compute_local_bounds_rectangle;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_CAN_ADD_CHILD_COMPUTE_LOCAL_BOUNDS_RECTANGLE_AF1F918F97747DFB


// NOT GENERATED: variable (binding) -- source line 617
// refusal: cpp-contextual-union-value-type-unrepresented [compiler-restriction]
//
// The source it stood for:
//   const defaultMethods: Partial<MethodsOf<QuadBatchRuntime>> = {
//     computeLocalBoundsRectangle: copyLocalBoundsRectangle,
//   };
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: contextual union callable
// value type std::function<void(flight::Ref<Rectangle>, flight::Ref<Node>)> agrees with no alternative's
// signature: the destination holds [std::function<void(flight::Ref<Rectangle>, flight::Ref<BoundsNodeAny>)>]. A
// callable is a represented domain, so the obstacle is that the destination's signature cannot call this one.
// Declare the value's parameters so the destination's signature supplies them, and its result as one the
// destination holds


// NOT GENERATED: function createQuadBatchRuntime -- source line 207
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   export function createQuadBatchRuntime(): QuadBatchRuntime {
//     const runtime = createNode2DRuntime(defaultMethods) as QuadBatchRuntime;
//     runtime.localBoundsRectangle = null;
//     runtime.instanceVelocities = null;
//     return runtime;
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<Node2DRuntime> to flight::Ref<QuadBatchRuntime> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage


// NOT GENERATED: function createQuadBatch -- source line 197
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   export function createQuadBatch(obj?: Readonly<PartialNode<QuadBatch>>): QuadBatch {
//     return createNode2D(QuadBatchKind, obj, createQuadBatchData, createQuadBatchRuntime) as QuadBatch;
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: intersection types require
// C++ multiple-inheritance lowering: no shape for Node (argument Node2DTraits has no shape either),
// Node2DTraits. Declare the object shape the code reads rather than intersecting a conjunct that has none

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_ATLAS_IDS_INSTANCE_COUNT_MATERIAL_DATA_TRANSFORMS_TRANSFORM_TYPE_A62D13234359FA2F
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_ATLAS_IDS_INSTANCE_COUNT_MATERIAL_DATA_TRANSFORMS_TRANSFORM_TYPE_A62D13234359FA2F
struct atlas_ids_instance_count_material_data_transforms_transform_type_a62d13234359fa2f : public flight::ReferenceEnabled {
  std::optional<flight::Ref<TextureAtlas>> atlas;
  flight::Uint16Array ids;
  double instance_count;
  std::optional<flight::Array<std::optional<flight::Ref<MaterialData>>>> material_data;
  flight::Float32Array transforms;
  flight::Ref<QuadTransformType> transform_type;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_ATLAS_IDS_INSTANCE_COUNT_MATERIAL_DATA_TRANSFORMS_TRANSFORM_TYPE_A62D13234359FA2F

inline flight::Ref<QuadBatch> clone_quad_batch(flight::Ref<QuadBatch> source) {
  flight::Ref<QuadBatchData> src = source->data;
  auto copy = flight::make_ref<QuadBatch>(*source);
  copy->data = flight::make_ref<QuadBatchData>(*src);
  copy->data->ids = src->ids.slice();
  copy->data->transforms = src->transforms.slice();
  copy->data->material_data = src->material_data.has_value()
                                  ? std::optional{src->material_data.value().slice()}
                                  : std::nullopt;
  return copy;
}

inline const flight::Symbol quad_batch_signals_slot = flight::Symbol(flight::String("quadBatchSignals"));

struct QuadBatchWithSignals : public flight::ReferenceEnabled {
  std::optional<flight::Ref<QuadBatchSignals>> quad_batch_signals_slot;
};

inline flight::WeakMap<flight::Ref<QuadBatch>, flight::Ref<QuadBatchSignals>> quad_batch_signals;


// NOT GENERATED: function enableQuadBatchSignals -- source line 225
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   export function enableQuadBatchSignals(target: QuadBatch): QuadBatchSignals {
//     const s = target as QuadBatchWithSignals;
//     return (s[quadBatchSignalsSlot] ??= createQuadBatchSignals());
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<QuadBatch> to flight::Ref<QuadBatchWithSignals> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage
inline flight::Ref<QuadBatchSignals> enable_quad_batch_signals(flight::Ref<QuadBatch> target) {
  auto signals = quad_batch_signals.get(target);
  if (signals.has_value()) return signals.value();
  auto created = create_quad_batch_signals();
  quad_batch_signals.set(target, created);
  return created;
}


// NOT GENERATED: function getQuadBatchSignals -- source line 272
// refusal: cpp-reference-assertion-without-heritage [target-runtime]
//
// The source it stood for:
//   export function getQuadBatchSignals(source: Readonly<QuadBatch>): QuadBatchSignals | null {
//     return (source as QuadBatchWithSignals)[quadBatchSignalsSlot] ?? null;
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: a reference assertion from
// flight::Ref<QuadBatch> to flight::Ref<QuadBatchWithSignals> has no heritage to cast along: the declarations
// share no emitted C++ class-heritage path (source interface and intersection relationships flatten into
// independent owners), and the source carrier does not retain a checked dynamic owner that can recover the
// target. Keep the exact declared owner at the API boundary, or add a runtime contract that validates and
// recovers the target owner; the compiler will not use a native pointer cast, materialize a replacement row, or
// invent side storage
inline std::optional<flight::Ref<QuadBatchSignals>> get_quad_batch_signals(
    flight::Ref<QuadBatch> source) {
  return quad_batch_signals.get(source);
}

inline void clear_quad_batch(flight::Ref<QuadBatch> target) {
  (target->data->instance_count = 0.0);
  std::optional<flight::Ref<QuadBatchSignals>> signals = get_quad_batch_signals(target);
  if (signals.has_value()) {
    signals.value()->on_cleared->emit();
  }
}

inline void remove_quad_batch_instance(flight::Ref<QuadBatch> target, double index) {
  flight::Ref<QuadBatchData> data = target->data;
  const double last = (data->instance_count - 1.0);
  if (((index < 0.0) || (index > last))) {
    return;
  }
  const double swap_source = ((index < last) ? last : -1.0);
  if ((index < last)) {
    ([&]() { auto&& typed_array_19 = data->ids; const auto typed_index_19 = index; const auto typed_value_19 = data->ids.get_index(last); return typed_array_19.set_index(typed_index_19, typed_value_19); }());
    if ((data->transform_type == flight::String("vector2"))) {
      const double dst = (index * quad_vector2_stride);
      const double src = (last * quad_vector2_stride);
      ([&]() { auto&& typed_array_20 = data->transforms; const auto typed_index_20 = dst; const auto typed_value_20 = data->transforms.get_index(src); return typed_array_20.set_index(typed_index_20, typed_value_20); }());
      ([&]() { auto&& typed_array_21 = data->transforms; const auto typed_index_21 = (dst + 1.0); const auto typed_value_21 = data->transforms.get_index((src + 1.0)); return typed_array_21.set_index(typed_index_21, typed_value_21); }());
    }
    else {
      const double dst_2 = (index * quad_matrix3_x2_stride);
      const double src_2 = (last * quad_matrix3_x2_stride);
      {
        double k = 0.0;
        while ((k < quad_matrix3_x2_stride)) {
          ([&]() { auto&& typed_array_22 = data->transforms; const auto typed_index_22 = (dst_2 + k); const auto typed_value_22 = data->transforms.get_index((src_2 + k)); return typed_array_22.set_index(typed_index_22, typed_value_22); }());
          (k += 1.0);
        }
      }
    }
    if (data->material_data.has_value()) {
      (data->material_data.value().element(index) = data->material_data.value().element(last));
    }
  }
  (data->instance_count = last);
  std::optional<flight::Ref<QuadBatchSignals>> signals = get_quad_batch_signals(target);
  if (signals.has_value()) {
    signals.value()->on_instance_removed->emit(index, swap_source);
  }
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_VECTOR2_MATRIX3X2_AAF46597026D025B
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_VECTOR2_MATRIX3X2_AAF46597026D025B
struct vector2_matrix3x2_aaf46597026d025b : public flight::ReferenceEnabled {
  double vector2;
  double matrix3x2;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_QUADBATCH_VECTOR2_MATRIX3X2_AAF46597026D025B

inline flight::Ref<vector2_matrix3x2_aaf46597026d025b> quad_transform_stride = flight::make_ref<vector2_matrix3x2_aaf46597026d025b>(vector2_matrix3x2_aaf46597026d025b{.vector2 = 2.0, .matrix3x2 = 6.0});

inline double get_quad_batch_transform_stride(flight::Ref<QuadTransformType> transform_type) {
  return ([&]() -> double { const auto& selection_receiver = quad_transform_stride; const auto selection_key = transform_type; if (selection_key == flight::String("vector2")) return selection_receiver->vector2; if (selection_key == flight::String("matrix3x2")) return selection_receiver->matrix3x2; throw std::logic_error("Flight finite-key selection reached no member"); }());
}

inline void compact_quad_batch(flight::Ref<QuadBatch> target) {
  flight::Ref<QuadBatchData> data = target->data;
  if ((data->instance_count == 0.0)) {
    return;
  }
  const double stride = get_quad_batch_transform_stride(data->transform_type);
  double write = 0.0;
  {
    double read = 0.0;
    while ((read < data->instance_count)) {
      {
        if ((data->ids.get_index(read) == quad_batch_deleted_id)) {
          (read += 1.0);
          continue;
        }
        if ((write != read)) {
          ([&]() { auto&& typed_array_23 = data->ids; const auto typed_index_23 = write; const auto typed_value_23 = data->ids.get_index(read); return typed_array_23.set_index(typed_index_23, typed_value_23); }());
          const double dst = (write * stride);
          const double src = (read * stride);
          {
            double k = 0.0;
            while ((k < stride)) {
              ([&]() { auto&& typed_array_24 = data->transforms; const auto typed_index_24 = (dst + k); const auto typed_value_24 = data->transforms.get_index((src + k)); return typed_array_24.set_index(typed_index_24, typed_value_24); }());
              (k += 1.0);
            }
          }
          if (data->material_data.has_value()) {
            (data->material_data.value().element(write) = data->material_data.value().element(read));
          }
        }
        write++;
      }
      (read += 1.0);
    }
  }
  (data->instance_count = write);
}

inline double get_quad_batch_capacity(flight::Ref<QuadBatch> source) {
  flight::Ref<QuadBatchData> data = source->data;
  const double stride = get_quad_batch_transform_stride(data->transform_type);
  const double transform_capacity = flight::bitwise_or((static_cast<double>(data->transforms.size()) / stride), 0.0);
  return flight::minimum(static_cast<double>(data->ids.size()), transform_capacity);
}

inline void iterate_quad_batch_instances(flight::Ref<QuadBatch> source, std::function<void(double, double, flight::Float32Array)> visitor) {
  flight::Ref<QuadBatchData> object_pattern_value = source->data;
  flight::Uint16Array ids = object_pattern_value->ids;
  const double instance_count = object_pattern_value->instance_count;
  flight::Float32Array transforms = object_pattern_value->transforms;
  flight::Ref<QuadTransformType> transform_type = object_pattern_value->transform_type;
  const double stride = get_quad_batch_transform_stride(transform_type);
  {
    double i = 0.0;
    while ((i < instance_count)) {
      {
        visitor(i, ids.get_index(i), transforms.subarray((i * stride), ((i * stride) + stride)));
      }
      (i += 1.0);
    }
  }
}

inline void reserve_quad_batch(flight::Ref<QuadBatch> target, double capacity) {
  const double current_capacity = get_quad_batch_capacity(target);
  if ((current_capacity >= capacity)) {
    return;
  }
  flight::Ref<QuadBatchData> data = target->data;
  (data->ids = reserve_uint16_array(data->ids, capacity));
  (data->transforms = reserve_float32_array(data->transforms, (capacity * get_quad_batch_transform_stride(data->transform_type))));
}

inline void resize_quad_batch(flight::Ref<QuadBatch> target, double instance_count) {
  flight::Ref<QuadBatchData> data = target->data;
  const double old_instance_count = data->instance_count;
  (data->instance_count = instance_count);
  if ((old_instance_count >= instance_count)) {
    return;
  }
  const double capacity = get_quad_batch_capacity(target);
  if ((capacity < instance_count)) {
    const double new_capacity = flight::maximum(instance_count, (capacity * 2.0));
    reserve_quad_batch(target, new_capacity);
  }
}

inline double append_quad_batch_instance(flight::Ref<QuadBatch> target, double id, double x, double y) {
  const double index = target->data->instance_count;
  resize_quad_batch(target, (index + 1.0));
  ([&]() { auto&& typed_array_25 = target->data->ids; const auto typed_index_25 = index; const auto typed_value_25 = id; return typed_array_25.set_index(typed_index_25, typed_value_25); }());
  const double o = (index * quad_vector2_stride);
  ([&]() { auto&& typed_array_26 = target->data->transforms; const auto typed_index_26 = o; const auto typed_value_26 = x; return typed_array_26.set_index(typed_index_26, typed_value_26); }());
  ([&]() { auto&& typed_array_27 = target->data->transforms; const auto typed_index_27 = (o + 1.0); const auto typed_value_27 = y; return typed_array_27.set_index(typed_index_27, typed_value_27); }());
  std::optional<flight::Ref<QuadBatchSignals>> signals = get_quad_batch_signals(target);
  if (signals.has_value()) {
    signals.value()->on_instance_appended->emit(index);
  }
  return index;
}

inline void set_quad_batch_instance_range(flight::Ref<QuadBatch> target, double start_index, double count, flight::Float32Array source) {
  flight::Ref<QuadBatchData> data = target->data;
  if ((((start_index < 0.0) || (count <= 0.0)) || ((start_index + count) > data->instance_count))) {
    return;
  }
  const double stride = get_quad_batch_transform_stride(data->transform_type);
  const double dst = (start_index * stride);
  const double len = (count * stride);
  {
    double k = 0.0;
    while ((k < len)) {
      ([&]() { auto&& typed_array_28 = data->transforms; const auto typed_index_28 = (dst + k); const auto typed_value_28 = source.get_index(k); return typed_array_28.set_index(typed_index_28, typed_value_28); }());
      (k += 1.0);
    }
  }
}

inline bool cross_sign(double ax, double ay, double bx, double by, double px, double py) {
  return ((((bx - ax) * (py - ay)) - ((by - ay) * (px - ax))) >= 0.0);
}


// NOT GENERATED: function hitTestQuadBatchPointExactXY -- source line 300
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   export function hitTestQuadBatchPointExactXY(source: Readonly<QuadBatch>, x: number, y: number): number {
//     const { atlas, ids, instanceCount, transforms, transformType } = source.data;
//     if (atlas === null || instanceCount === 0) return -1;
//     const regions = atlas.regions;
//     const numRegions = regions.length;
//     if (transformType === 'vector2') {
//       // Axis-aligned — AABB is exact.
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         const dx = transforms[i * QUAD_VECTOR2_STRIDE];
//         const dy = transforms[i * QUAD_VECTOR2_STRIDE + 1];
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const width = rotated ? region.height : region.width;
//         const height = rotated ? region.width : region.height;
//         if (x >= dx && x < dx + width && y >= dy && y < dy + height) return i;
//       }
//     } else {
//       for (let i = 0; i < instanceCount; i++) {
//         const id = ids[i];
//         if (id < 0 || id >= numRegions) continue;
//         const region = regions[id];
//         if (region.width <= 0 || region.height <= 0) continue;
//         const o = i * QUAD_MATRIX3X2_STRIDE;
//         const a = transforms[o];
//         const b = transforms[o + 1];
//         const c = transforms[o + 2];
//         const d = transforms[o + 3];
//         const tx = transforms[o + 4];
//         const ty = transforms[o + 5];
//         const rotated = region.rotation !== TextureAtlasRotation.None;
//         const w = rotated ? region.height : region.width;
//         const h = rotated ? region.width : region.height;
//         // Four corners of the quad: (0,0)→(w,0)→(w,h)→(0,h) mapped by the affine.
//         const x0 = tx;
//         const y0 = ty;
//         const x1 = a * w + tx;
//         const y1 = b * w + ty;
//         const x2 = a * w + c * h + tx;
//         const y2 = b * w + d * h + ty;
//         const x3 = c * h + tx;
//         const y3 = d * h + ty;
//         // Point-in-convex-polygon via signed cross products. A point P is inside a CCW quad when
//         // the cross product of each edge vector with (P - edge_start) is >= 0 for all four edges.
//         if (
//           crossSign(x0, y0, x1, y1, x, y) &&
//           crossSign(x1, y1, x2, y2, x, y) &&
//           crossSign(x2, y2, x3, y3, x, y) &&
//           crossSign(x3, y3, x0, y0, x, y)
//         )
//           return i;
//       }
//     }
//     return -1;
//   }
//   
// cpp emission failed for @flighthq/quadbatch/packages/quadbatch/src/quadBatch.ts: contextual optionalSingle
// construction requires expression type evidence
inline double hit_test_quad_batch_point_exact_xy(flight::Ref<QuadBatch>, double, double) {
  return -1.0;
}

inline double hit_test_quad_batch_point_exact(flight::Ref<QuadBatch> source, flight::Ref<Vector2Like> point) {
  return hit_test_quad_batch_point_exact_xy(source, point->x, point->y);
}

} // namespace flight::quadbatch

namespace flight::detail {
template <>
struct GeneratedSymbolBindings<flight::quadbatch::QuadBatchWithSignals> {
  static void bind(RowOwner& owner, const std::shared_ptr<flight::quadbatch::QuadBatchWithSignals>& object) {
    owner.bind_symbol(
        flight::quadbatch::quad_batch_signals_slot,
        [object]() -> decltype(auto) { return (object->quad_batch_signals_slot); },
        [object]<typename Object = flight::quadbatch::QuadBatchWithSignals>() -> bool {
          auto& value = static_cast<Object&>(*object);
          if constexpr (requires { value.quad_batch_signals_slot.has_value(); })
            return value.quad_batch_signals_slot.has_value();
          else
            return true;
        });
  }
};
} // namespace flight::detail
