// Generated by @flighthq/tool-compiler from @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts#WgpuEffectPass at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function getOrCreateTextureBG -- source line 147
//   missing: function beginEffectPass -- source line 181
//   missing: function resolveEffectPipeline -- source line 214
//   missing: function createWgpuDualSourceEffectPipeline -- source line 238
//   missing: function createWgpuEffectPipeline -- source line 248
#include <cmath>
#include <flight/any.hpp>
#include <flight/host_sdl/wgpu.hpp>
#include <flight/string.hpp>
#include <flight/weak_map.hpp>
#include <functional>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/wgpu_render_state.hpp>
#include <flight/types/entity.hpp>
#include <flight/types/wgpu_dual_source_effect_pipeline.hpp>
#include <flight/types/wgpu_effect_blend_mode.hpp>
#include <flight/types/wgpu_effect_pipeline.hpp>
#include <flight/types/wgpu_render_target.hpp>

namespace flight::effects_wgpu {

using flight::types::WgpuRenderState;
using flight::types::EntityConstruction;
using flight::types::WgpuDualSourceEffectPipeline;
using flight::types::WgpuEffectBlendMode;
using flight::types::WgpuEffectPipeline;
using flight::types::WgpuTextureRenderTarget;

inline const flight::String effect_vertex_wgsl = flight::String("\nstruct VertexOut {\n  @builtin(position) position : vec4f,\n  @location(0) uv : vec2f,\n}\n\n@vertex\nfn vs_main(@builtin(vertex_index) vi : u32) -> VertexOut {\n  let xi = vi == 1u || vi == 2u || vi == 4u;\n  let yi = vi == 2u || vi == 4u || vi == 5u;\n  var out : VertexOut;\n  out.position = vec4f(select(-1.0, 1.0, xi), select(-1.0, 1.0, yi), 0.0, 1.0);\n  out.uv = vec2f(select(0.0, 1.0, xi), select(1.0, 0.0, yi));\n  return out;\n}\n");

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_SRC_FACTOR_DST_FACTOR_OPERATION_734D8E3FCC3C03FB
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_SRC_FACTOR_DST_FACTOR_OPERATION_734D8E3FCC3C03FB
struct src_factor_dst_factor_operation_734d8e3fcc3c03fb : public flight::ReferenceEnabled {
  flight::String src_factor;
  flight::String dst_factor;
  flight::String operation;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_SRC_FACTOR_DST_FACTOR_OPERATION_734D8E3FCC3C03FB

inline flight::host_sdl::WgpuBlendState premul_blend = ([]() { flight::host_sdl::WgpuBlendState external_gpublend_state{}; external_gpublend_state.color = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("one"), .dst_factor = flight::String("one-minus-src-alpha"), .operation = flight::String("add")}); external_gpublend_state.alpha = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("one"), .dst_factor = flight::String("one-minus-src-alpha"), .operation = flight::String("add")}); return external_gpublend_state; }());

inline flight::host_sdl::WgpuBlendState replace_blend = ([]() { flight::host_sdl::WgpuBlendState external_gpublend_state_2{}; external_gpublend_state_2.color = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("one"), .dst_factor = flight::String("zero"), .operation = flight::String("add")}); external_gpublend_state_2.alpha = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("one"), .dst_factor = flight::String("zero"), .operation = flight::String("add")}); return external_gpublend_state_2; }());

inline flight::host_sdl::WgpuBlendState erase_blend = ([]() { flight::host_sdl::WgpuBlendState external_gpublend_state_3{}; external_gpublend_state_3.color = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("zero"), .dst_factor = flight::String("one-minus-src-alpha"), .operation = flight::String("add")}); external_gpublend_state_3.alpha = flight::make_ref<src_factor_dst_factor_operation_734d8e3fcc3c03fb>(src_factor_dst_factor_operation_734d8e3fcc3c03fb{.src_factor = flight::String("zero"), .dst_factor = flight::String("one-minus-src-alpha"), .operation = flight::String("add")}); return external_gpublend_state_3; }());

struct WgpuEffectPassState : public flight::ReferenceEnabled {
  flight::host_sdl::WgpuBuffer uniform_buffer;
  flight::Float32Array uniform_data;
  flight::Int32Array uniform_data_i32;
  double uniform_offset;
  double uniform_stride;
  double uniform_slots;
  flight::host_sdl::WgpuBindGroupLayout uniform_bglayout;
  flight::host_sdl::WgpuBindGroup uniform_bg;
  flight::host_sdl::WgpuBindGroupLayout texture_bglayout;
  flight::WeakMap<flight::host_sdl::WgpuTextureView, flight::host_sdl::WgpuBindGroup, flight::host_sdl::WgpuTextureViewWeakPolicy> texture_bgs;
  flight::host_sdl::WgpuSampler sampler;
  flight::String format;
};

inline flight::WeakMap<flight::Ref<WgpuRenderState>, flight::Ref<WgpuEffectPassState>> effect_pass_states = flight::WeakMap<flight::Ref<WgpuRenderState>, flight::Ref<WgpuEffectPassState>>();

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BUFFER_UNIFORM_DATA_UNIFORM_DATA_I32_UNIFORM_OFFSET_UNIFORM_STRIDE_UNIFORM_SLOTS_UNIFORM_BGLAYOUT_UNIFORM_BG_TEXTURE_BGLAYOUT_TEXTURE_BGS_SAMPLER_FORMAT_E74550EE8F9954DA
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BUFFER_UNIFORM_DATA_UNIFORM_DATA_I32_UNIFORM_OFFSET_UNIFORM_STRIDE_UNIFORM_SLOTS_UNIFORM_BGLAYOUT_UNIFORM_BG_TEXTURE_BGLAYOUT_TEXTURE_BGS_SAMPLER_FORMAT_E74550EE8F9954DA
struct uniform_buffer_uniform_data_uniform_data_i32_uniform_offset_uniform_stride_uniform_slots_uniform_bglayout_uniform_bg_texture_bglayout_texture_bgs_sampler_format_e74550ee8f9954da : public flight::ReferenceEnabled {
  flight::host_sdl::WgpuBuffer uniform_buffer;
  flight::Float32Array uniform_data;
  flight::Int32Array uniform_data_i32;
  double uniform_offset;
  double uniform_stride;
  double uniform_slots;
  flight::host_sdl::WgpuBindGroupLayout uniform_bglayout;
  flight::host_sdl::WgpuBindGroup uniform_bg;
  flight::host_sdl::WgpuBindGroupLayout texture_bglayout;
  flight::WeakMap<flight::host_sdl::WgpuTextureView, flight::host_sdl::WgpuBindGroup, flight::host_sdl::WgpuTextureViewWeakPolicy> texture_bgs;
  flight::host_sdl::WgpuSampler sampler;
  flight::String format;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BUFFER_UNIFORM_DATA_UNIFORM_DATA_I32_UNIFORM_OFFSET_UNIFORM_STRIDE_UNIFORM_SLOTS_UNIFORM_BGLAYOUT_UNIFORM_BG_TEXTURE_BGLAYOUT_TEXTURE_BGS_SAMPLER_FORMAT_E74550EE8F9954DA

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TYPE_HAS_DYNAMIC_OFFSET_048327435FFD92D7
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TYPE_HAS_DYNAMIC_OFFSET_048327435FFD92D7
struct type_has_dynamic_offset_048327435ffd92d7 : public flight::ReferenceEnabled {
  flight::String type;
  bool has_dynamic_offset;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TYPE_HAS_DYNAMIC_OFFSET_048327435FFD92D7

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_VISIBILITY_BUFFER_6BA814800D23896C
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_VISIBILITY_BUFFER_6BA814800D23896C
struct binding_visibility_buffer_6ba814800d23896c : public flight::ReferenceEnabled {
  double binding;
  flight::Any visibility;
  flight::Ref<type_has_dynamic_offset_048327435ffd92d7> buffer;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_VISIBILITY_BUFFER_6BA814800D23896C

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BUFFER_SIZE_FB2AC6D30ECF54A7
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BUFFER_SIZE_FB2AC6D30ECF54A7
struct buffer_size_fb2ac6d30ecf54a7 : public flight::ReferenceEnabled {
  flight::Any buffer;
  double size;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BUFFER_SIZE_FB2AC6D30ECF54A7

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_RESOURCE_7DC8BF29C07F44CD
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_RESOURCE_7DC8BF29C07F44CD
struct binding_resource_7dc8bf29c07f44cd : public flight::ReferenceEnabled {
  double binding;
  flight::Ref<buffer_size_fb2ac6d30ecf54a7> resource;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_BINDING_RESOURCE_7DC8BF29C07F44CD

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_ANONYMOUS_3E6B344A3B6BD77E
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_ANONYMOUS_3E6B344A3B6BD77E
struct anonymous_3e6b344a3b6bd77e : public flight::ReferenceEnabled {
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_ANONYMOUS_3E6B344A3B6BD77E

inline flight::Ref<WgpuEffectPassState> get_or_create_effect_pass_state(flight::Ref<WgpuRenderState> state) {
  if (auto fs = effect_pass_states.get(state); fs.has_value()) return fs.value();
  throw flight::Error(flight::String("effects-wgpu: WebGPU device operations are unavailable in this profile"));
}


// NOT GENERATED: function getOrCreateTextureBG -- source line 147
// refusal: cpp-contextual-union-missing-expression-type:optionalSingle [compiler-restriction]
//
// The source it stood for:
//   function getOrCreateTextureBG(fs: WgpuEffectPassState, device: GPUDevice, view: GPUTextureView): GPUBindGroup {
//     let bg = fs.textureBGs.get(view);
//     if (bg === undefined) {
//       bg = device.createBindGroup({
//         layout: fs.textureBGLayout,
//         entries: [
//           { binding: 0, resource: view },
//           { binding: 1, resource: fs.sampler },
//         ],
//       });
//       fs.textureBGs.set(view, bg);
//     }
//     return bg;
//   }
//   
// cpp emission failed for @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts: contextual
// optionalSingle construction requires expression type evidence

inline double acquire_uniform_slot(flight::Ref<WgpuEffectPassState> fs) {
  const double offset = fs->uniform_offset;
  (fs->uniform_offset = std::fmod((offset + fs->uniform_stride), (fs->uniform_slots * fs->uniform_stride)));
  return offset;
}

inline void write_uniform_slot(flight::Ref<WgpuRenderState> state, flight::Ref<WgpuEffectPassState> fs, double slot_offset, std::function<void(flight::Float32Array, flight::Int32Array)> set_uniforms) {
  throw flight::Error(flight::String("effects-wgpu: WebGPU queue operations are unavailable in this profile"));
}

inline flight::host_sdl::WgpuBindGroup get_or_create_texture_bg(
    flight::Ref<WgpuEffectPassState>, flight::host_sdl::WgpuDevice,
    flight::host_sdl::WgpuTextureView) {
  throw flight::Error(flight::String("effects-wgpu: bind-group creation is unavailable in this profile"));
}

inline flight::host_sdl::WgpuRenderPassEncoder begin_effect_pass(
    flight::Ref<WgpuRenderState>, std::optional<flight::Ref<WgpuTextureRenderTarget>>, flight::String) {
  throw flight::Error(flight::String("effects-wgpu: render-pass operations are unavailable in this profile"));
}

template <typename Pipeline>
inline flight::host_sdl::WgpuRenderPipeline resolve_effect_pipeline(
    flight::Ref<WgpuRenderState>, Pipeline, std::optional<flight::Ref<WgpuTextureRenderTarget>>) {
  throw flight::Error(flight::String("effects-wgpu: pipeline resolution is unavailable in this profile"));
}


// NOT GENERATED: function beginEffectPass -- source line 181
// refusal: cpp-presence-test-without-absence-storage [compiler-restriction]
//
// The source it stood for:
//   function beginEffectPass(
//     state: WgpuRenderState,
//     dest: WgpuTextureRenderTarget | null,
//     loadOp: GPULoadOp,
//   ): GPURenderPassEncoder {
//     const runtime = getWgpuRenderStateRuntime(state);
//     if (runtime.commandEncoder === null) {
//       throw new Error('No active command encoder — open a frame with beginWgpuRenderPass first');
//     }
//     // A fullscreen effect pass is recorded alongside the caller's pass rather than inside it, so the
//     // caller's pass steps aside; endWgpuEffectState resumes it once the chain has presented.
//     const enclosing = getWgpuActiveRenderPass(state);
//     if (enclosing !== null) suspendWgpuRenderPass(enclosing);
//   
//     // A null destination means "where the enclosing pass is drawing" — the screen, ordinarily. The view
//     // comes from that pass rather than from a canvas view on the state, because the state does not know
//     // which surface a frame is landing on.
//     const view = dest !== null ? dest.view : enclosing!.colorView;
//     const pass = runtime.commandEncoder.beginRenderPass({
//       colorAttachments: [{ view, loadOp, storeOp: 'store', clearValue: { r: 0, g: 0, b: 0, a: 0 } }],
//     });
//     if (dest !== null) {
//       pass.setViewport(0, 0, dest.width, dest.height, 0, 1);
//     } else {
//       const extent = getWgpuRenderPassViewport(state);
//       pass.setViewport(0, 0, extent.width, extent.height, 0, 1);
//     }
//     return pass;
//   }
//   
//   // Returns the GPURenderPipeline whose color target format matches `dest` (the canvas format when dest is
//   // null). Compiles and caches a per-format variant on demand so a pipeline built for the canvas format can
//   // still draw into an HDR (rgba16float) effect target without an attachment-format mismatch.
// cpp emission failed for @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts: a presence test
// against null has no absence channel in the emitted C++ storage for property


// NOT GENERATED: function resolveEffectPipeline -- source line 214
// refusal: cpp-presence-test-without-absence-storage [compiler-restriction]
//
// The source it stood for:
//   function resolveEffectPipeline(
//     state: WgpuRenderState,
//     pipeline: Readonly<WgpuEffectPipeline>,
//     dest: WgpuTextureRenderTarget | null,
//   ): GPURenderPipeline {
//     const canvasFormat = getOrCreateEffectPassState(state).format;
//     const targetFormat = dest !== null ? dest.format : canvasFormat;
//     if (pipeline.compileForFormat === undefined || pipeline.variants === undefined || targetFormat === canvasFormat) {
//       return pipeline.pipeline;
//     }
//     let variant = pipeline.variants.get(targetFormat);
//     if (variant === undefined) {
//       variant = pipeline.compileForFormat(targetFormat);
//       pipeline.variants.set(targetFormat, variant);
//     }
//     return variant;
//   }
//   
//   /** Clears a render target to fully transparent. Ends any active render pass. */
// cpp emission failed for @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts: a presence test
// against undefined has no absence channel in the emitted C++ storage for property

inline void clear_wgpu_effect_target(flight::Ref<WgpuRenderState> state, flight::Ref<WgpuTextureRenderTarget> target) {
  throw flight::Error(flight::String("effects-wgpu: render-pass operations are unavailable in this profile"));
}

inline void draw_wgpu_dual_source_effect_pass(flight::Ref<WgpuRenderState> state, flight::Ref<WgpuTextureRenderTarget> source0, flight::Ref<WgpuTextureRenderTarget> source1, std::optional<flight::Ref<WgpuTextureRenderTarget>> dest, flight::Ref<WgpuDualSourceEffectPipeline> pipeline, std::function<void(flight::Float32Array, flight::Int32Array)> set_uniforms) {
  throw flight::Error(flight::String("effects-wgpu: render-pass operations are unavailable in this profile"));
}

inline void draw_wgpu_effect_pass(flight::Ref<WgpuRenderState> state, flight::Ref<WgpuTextureRenderTarget> source, std::optional<flight::Ref<WgpuTextureRenderTarget>> dest, flight::Ref<WgpuEffectPipeline> pipeline, std::function<void(flight::Float32Array, flight::Int32Array)> set_uniforms) {
  throw flight::Error(flight::String("effects-wgpu: render-pass operations are unavailable in this profile"));
}

inline flight::host_sdl::WgpuBlendState get_blend_state(WgpuEffectBlendMode blend) {
  if ((blend == flight::String("replace"))) {
    return replace_blend;
  }
  if ((blend == flight::String("erase"))) {
    return erase_blend;
  }
  return premul_blend;
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BG_TEXTURE_BGLAYOUT_UNIFORM_BGLAYOUT_SAMPLER_ACQUIRE_SLOT_WRITE_SLOT_BEGIN_PASS_6E85051CE2E6AC30
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BG_TEXTURE_BGLAYOUT_UNIFORM_BGLAYOUT_SAMPLER_ACQUIRE_SLOT_WRITE_SLOT_BEGIN_PASS_6E85051CE2E6AC30
struct uniform_bg_texture_bglayout_uniform_bglayout_sampler_acquire_slot_write_slot_begin_pass_6e85051ce2e6ac30 : public flight::ReferenceEnabled {
  flight::host_sdl::WgpuBindGroup uniform_bg;
  flight::host_sdl::WgpuBindGroupLayout texture_bglayout;
  flight::host_sdl::WgpuBindGroupLayout uniform_bglayout;
  flight::host_sdl::WgpuSampler sampler;
  std::function<double()> acquire_slot;
  std::function<void(double, std::function<void(flight::Float32Array, flight::Int32Array)>)> write_slot;
  std::function<flight::host_sdl::WgpuRenderPassEncoder(std::optional<flight::Ref<WgpuTextureRenderTarget>>, flight::String)> begin_pass;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_UNIFORM_BG_TEXTURE_BGLAYOUT_UNIFORM_BGLAYOUT_SAMPLER_ACQUIRE_SLOT_WRITE_SLOT_BEGIN_PASS_6E85051CE2E6AC30

inline flight::Ref<uniform_bg_texture_bglayout_uniform_bglayout_sampler_acquire_slot_write_slot_begin_pass_6e85051ce2e6ac30> get_wgpu_effect_pass_state(flight::Ref<WgpuRenderState> state) {
  auto fs = get_or_create_effect_pass_state(state);
  return flight::make_ref<uniform_bg_texture_bglayout_uniform_bglayout_sampler_acquire_slot_write_slot_begin_pass_6e85051ce2e6ac30>(uniform_bg_texture_bglayout_uniform_bglayout_sampler_acquire_slot_write_slot_begin_pass_6e85051ce2e6ac30{.uniform_bg = fs->uniform_bg, .texture_bglayout = fs->texture_bglayout, .uniform_bglayout = fs->uniform_bglayout, .sampler = fs->sampler, .acquire_slot = [=]() { return acquire_uniform_slot(fs); }, .write_slot = [=](double offset, std::function<void(flight::Float32Array, flight::Int32Array)> fn) { return write_uniform_slot(state, fs, offset, fn); }, .begin_pass = [=](std::optional<flight::Ref<WgpuTextureRenderTarget>> dest, flight::String load_op) { return begin_effect_pass(state, dest, load_op); }});
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_4D3C337401507620
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_4D3C337401507620
struct module_entry_point_4d3c337401507620 : public flight::ReferenceEnabled {
  flight::Any module;
  flight::String entry_point;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_4D3C337401507620

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_FORMAT_BLEND_44905F6442074C10
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_FORMAT_BLEND_44905F6442074C10
struct format_blend_44905f6442074c10 : public flight::ReferenceEnabled {
  flight::Any format;
  flight::host_sdl::WgpuBlendState blend;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_FORMAT_BLEND_44905F6442074C10

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_TARGETS_9C54D993F2030CD7
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_TARGETS_9C54D993F2030CD7
struct module_entry_point_targets_9c54d993f2030cd7 : public flight::ReferenceEnabled {
  flight::Any module;
  flight::String entry_point;
  flight::Array<flight::Ref<format_blend_44905f6442074c10>> targets;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_MODULE_ENTRY_POINT_TARGETS_9C54D993F2030CD7

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TOPOLOGY_7C8278728B18051E
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TOPOLOGY_7C8278728B18051E
struct topology_7c8278728b18051e : public flight::ReferenceEnabled {
  flight::String topology;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_EFFECTS_WGPU_TOPOLOGY_7C8278728B18051E

inline void initialize_wgpu_dual_source_effect_pipeline(flight::Ref<EntityConstruction<flight::Ref<WgpuEffectPipeline>>> out, flight::Ref<WgpuRenderState> state, flight::String fragment_wgsl, std::optional<WgpuEffectBlendMode> blend = std::nullopt) {
  throw flight::Error(flight::String("effects-wgpu: pipeline creation is unavailable in this profile"));
}

inline flight::Ref<WgpuEffectPipeline> create_wgpu_dual_source_effect_pipeline(
    flight::Ref<WgpuRenderState> state,
    flight::String fragment_wgsl,
    std::optional<WgpuEffectBlendMode> blend = std::nullopt) {
  auto out = flight::make_ref<WgpuEffectPipeline>();
  initialize_wgpu_dual_source_effect_pipeline(out, state, fragment_wgsl, blend);
  return out;
}


// NOT GENERATED: function createWgpuDualSourceEffectPipeline -- source line 238
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   export function createWgpuDualSourceEffectPipeline(
//     state: WgpuRenderState,
//     fragmentWGSL: string,
//     blend: WgpuEffectBlendMode = 'premul',
//   ): WgpuDualSourceEffectPipeline {
//     const out = allocateEntity<WgpuEffectPipeline>();
//     initializeWgpuDualSourceEffectPipeline(out, state, fragmentWGSL, blend);
//     return finishEntity(out);
//   }
//   
// cpp emission failed for @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts: intersection types
// require C++ multiple-inheritance lowering: no shape for Entity. Declare the object shape the code reads rather
// than intersecting a conjunct that has none

inline void initialize_wgpu_effect_pipeline(flight::Ref<EntityConstruction<flight::Ref<WgpuEffectPipeline>>> out, flight::Ref<WgpuRenderState> state, flight::String fragment_wgsl, std::optional<WgpuEffectBlendMode> blend = std::nullopt) {
  throw flight::Error(flight::String("effects-wgpu: pipeline creation is unavailable in this profile"));
}

inline flight::Ref<WgpuEffectPipeline> create_wgpu_effect_pipeline(
    flight::Ref<WgpuRenderState> state,
    flight::String fragment_wgsl,
    std::optional<WgpuEffectBlendMode> blend = std::nullopt) {
  auto out = flight::make_ref<WgpuEffectPipeline>();
  initialize_wgpu_effect_pipeline(out, state, fragment_wgsl, blend);
  return out;
}


// NOT GENERATED: function createWgpuEffectPipeline -- source line 248
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   export function createWgpuEffectPipeline(
//     state: WgpuRenderState,
//     fragmentWGSL: string,
//     blend: WgpuEffectBlendMode = 'premul',
//   ): WgpuEffectPipeline {
//     const out = allocateEntity<WgpuEffectPipeline>();
//     initializeWgpuEffectPipeline(out, state, fragmentWGSL, blend);
//     return finishEntity(out);
//   }
//   
//   /**
//    * Draws a full-screen pass reading from two source textures.
//    * source0 binds to group 1, source1 to group 2.
//    */
// cpp emission failed for @flighthq/effects-wgpu/packages/effects-wgpu/src/wgpuEffectPass.ts: intersection types
// require C++ multiple-inheritance lowering: no shape for Entity. Declare the object shape the code reads rather
// than intersecting a conjunct that has none

} // namespace flight::effects_wgpu
