// Generated by @flighthq/tool-compiler from @flighthq/materials/packages/materials/src/material.ts#Material at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function getMaterialOfKind -- source line 50
//   missing: function copyMaterialFields -- source line 62
#include <flight/any.hpp>
#include <flight/structural_ref.hpp>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/entity/entity.hpp>

#include <flight/types/material.hpp>

#include <flight/types/entity.hpp>

namespace flight::materials {

using flight::entity::allocate_entity;
using flight::entity::finish_entity;

using flight::types::EntityConstruction;
using flight::types::Kind;
using flight::types::Material;

inline bool equals_material(flight::Ref<Material> a, flight::Ref<Material> b) {
  if ((a == b)) {
    return true;
  }
  if ((a->kind != b->kind)) {
    return false;
  }
  flight::NamedProperties a_fields = flight::named_properties(a);
  flight::NamedProperties b_fields = flight::named_properties(b);
  flight::Array<flight::String> a_keys = ([&]() { const auto named_view = a_fields; const auto named_keys = named_view.keys(); return flight::Array<flight::String>(named_keys.begin(), named_keys.end()); }());
  flight::Array<flight::String> b_keys = ([&]() { const auto named_view_2 = b_fields; const auto named_keys_2 = named_view_2.keys(); return flight::Array<flight::String>(named_keys_2.begin(), named_keys_2.end()); }());
  if ((static_cast<double>(a_keys.size()) != static_cast<double>(b_keys.size()))) {
    return false;
  }
  for (auto key : a_keys) {
    if (!b_fields.has(key)) {
      return false;
    }
    if ((key == flight::String("kind"))) {
      continue;
    }
    if ((a_fields.get(key) != b_fields.get(key))) {
      return false;
    }
  }
  return true;
}


// NOT GENERATED: function getMaterialOfKind -- source line 50
// refusal: cpp-dependent-indexed-access-unproven [compiler-restriction]
//
// The source it stood for:
//   export function getMaterialOfKind<T extends Material>(material: Readonly<Material> | null, kind: T['kind']): T | null {
//     return material !== null && material.kind === kind ? (material as T) : null;
//   }
//   
// cpp emission failed for @flighthq/materials/packages/materials/src/material.ts: indexedAccess types require
// C++ type computation lowering: 'kind' is not a member of every inhabited constraint branch of T, whose
// constraint is Material

inline void initialize_material(flight::Ref<EntityConstruction<flight::Ref<Material>>> material, Kind kind) {
  (material->kind = kind);
  (material->name = nullptr);
}

inline flight::Ref<Material> create_material(Kind kind) {
  flight::Ref<EntityConstruction<flight::Ref<Material>>> material = allocate_entity<flight::Ref<Material>>();
  initialize_material(material, kind);
  return finish_entity(material);
}


// NOT GENERATED: function copyMaterialFields -- source line 62
// refusal: cpp-named-properties-write-unsupported [target-runtime]
//
// The source it stood for:
//   function copyMaterialFields(dst: Material, src: Readonly<Material>, kind: Kind): void {
//     const dstFields = dst as unknown as Record<string, unknown>;
//     const srcFields = src as unknown as Record<string, unknown>;
//     for (const key of Object.keys(srcFields)) {
//       if (key === 'kind') continue;
//       const value = srcFields[key];
//       if (key === 'standard' && value != null && typeof value === 'object') {
//         // Shallow-copy the StandardPbrMaterialProperties block into an existing or new object.
//         dstFields[key] = { ...(value as object) };
//       } else {
//         dstFields[key] = value;
//       }
//     }
//     // Ensure `kind` is always the source kind (the caller may have already set it, but verify).
//     dstFields['kind'] = kind;
//   }
//   
// cpp emission failed for @flighthq/materials/packages/materials/src/material.ts: a dynamic named-property write
// through the owner-preserving view of Material requires target-runtime mutation support: Material remains the
// concrete object carrier and is not Record storage, flight::NamedProperties is deliberately read-only, and this
// key has no finite declared member set the compiler can dispatch. For an intentionally open extension domain,
// declare mutable string-indexed storage on the base/output type and construct every owner in that carrier; a
// registry of keys or roles cannot recover cells on an owner that lacks them. Otherwise add an owner-preserving
// checked NamedProperties::set(String, Any) contract, or keep the key as a finite union of declared member names
// and assign through the typed object. Two things a reader tries here do not work and one does: adding an index
// signature to a type that DECLARES members does not make it that record carrier -- the declared members keep it
// a closed owner and the dynamic write still has no cell -- while a carrier whose storage IS the record is
// mutable and lowers, and assigning through the declared members lowers too. The compiler will not cast between
// owners, copy into replacement storage, materialize a replacement owner, or add side storage

template <typename Destination>
[[noreturn]] inline void copy_material_fields(
    Destination, flight::Ref<Material>, Kind) {
  throw flight::Error(
      flight::String("Material cloning is unavailable because this runtime cannot copy open "
                     "extension properties without losing fields"));
}

inline flight::Ref<Material> clone_material(flight::Ref<Material> source) {
  flight::Ref<EntityConstruction<flight::Ref<Material>>> clone = allocate_entity<flight::Ref<Material>>();
  (clone->kind = source->kind);
  copy_material_fields(clone, source, source->kind);
  return finish_entity(clone);
}

inline void copy_material(flight::Ref<Material> out, flight::Ref<Material> source) {
  if ((out == source)) {
    return;
  }
  copy_material_fields(out, source, source->kind);
}

} // namespace flight::materials
