// Generated by @flighthq/tool-compiler from @flighthq/physics3d/packages/physics3d/src/stepValidation.ts#StepValidation at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function isPhysics3DStaticSurfaceCollider -- source line 43
//   missing: function isPhysics3DContactValid -- source line 69
//   missing: function isPhysics3DSolverConfigValid -- source line 134
//   missing: function getPhysics3DColliderShapeValidationStatus -- source line 259
//   missing: function isPhysics3DColliderWorldShapeCompatible -- source line 267
//   missing: function isPhysics3DColliderValid -- source line 239
//   missing: function isPhysics3DJointValid -- source line 175
//   missing: function isRigidBody3DStateValid -- source line 203
#include <cmath>
#include <flight/number.hpp>
#include <limits>
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/physics3_d.hpp>

namespace flight::physics3d {

using flight::types::Physics3DCollider;
using flight::types::Physics3DContact;
using flight::types::Physics3DJoint;
using flight::types::Physics3DSolverConfig;
using flight::types::Physics3DWorld;
using flight::types::RigidBody3D;

inline bool is_physics3_dstatic_surface_collider(flight::Ref<Physics3DCollider> collider) {
  const auto kind = std::visit([](const auto& shape) { return shape->kind; }, collider->local);
  return kind == flight::String("triangle-mesh") || kind == flight::String("heightfield");
}

inline bool is_physics3_dcollider_valid(flight::Ref<Physics3DCollider>) {
  throw std::logic_error("Physics3D collider validation requires compiler support for open collision-shape unions");
}

inline bool is_physics3_djoint_valid(flight::Ref<Physics3DJoint>) {
  throw std::logic_error("Physics3D joint validation requires runtime reflection over open joint fields");
}

inline bool is_rigid_body3_dstate_valid(flight::Ref<RigidBody3D>) {
  throw std::logic_error("Physics3D rigid-body validation requires runtime reflection over generated field names");
}


// NOT GENERATED: function isPhysics3DStaticSurfaceCollider -- source line 43
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function isPhysics3DStaticSurfaceCollider(collider: Readonly<Physics3DCollider>): boolean {
//     return collider.local.kind === 'triangle-mesh' || collider.local.kind === 'heightfield';
//   }
//   
//   // Validates the data that will generate NEW contacts during this step. Keeping this separate from body
//   // state is diagnostic: a NaN material is repaired at a collider, not in the body's pose or inertia.
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: intersection types
// require C++ multiple-inheritance lowering: no shape for CollisionSphere3D. Declare the object shape the code
// reads rather than intersecting a conjunct that has none


// NOT GENERATED: function isPhysics3DContactValid -- source line 69
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   export function isPhysics3DContactValid(contact: Readonly<Physics3DContact>): boolean {
//     if (
//       !Number.isSafeInteger(contact.bodyA) ||
//       !Number.isSafeInteger(contact.bodyB) ||
//       !Number.isSafeInteger(contact.colliderA) ||
//       contact.colliderA < 0 ||
//       !Number.isSafeInteger(contact.colliderB) ||
//       contact.colliderB < 0 ||
//       !Number.isSafeInteger(contact.pointCount) ||
//       contact.pointCount < 0 ||
//       contact.pointCount > contact.points.length ||
//       !Number.isFinite(contact.normalX) ||
//       !Number.isFinite(contact.normalY) ||
//       !Number.isFinite(contact.normalZ) ||
//       !Number.isFinite(contact.friction) ||
//       contact.friction < 0 ||
//       !Number.isFinite(contact.restitution) ||
//       contact.restitution < 0 ||
//       typeof contact.enabled !== 'boolean' ||
//       typeof contact.sensor !== 'boolean' ||
//       typeof contact.touching !== 'boolean'
//     ) {
//       return false;
//     }
//     for (let i = 0; i < contact.pointCount; i += 1) {
//       const point = contact.points[i];
//       if (point === undefined) return false;
//       if (
//         !Number.isFinite(point.x) ||
//         !Number.isFinite(point.y) ||
//         !Number.isFinite(point.z) ||
//         !Number.isFinite(point.depth) ||
//         !Number.isFinite(point.featureId) ||
//         !Number.isFinite(point.rAX) ||
//         !Number.isFinite(point.rAY) ||
//         !Number.isFinite(point.rAZ) ||
//         !Number.isFinite(point.rBX) ||
//         !Number.isFinite(point.rBY) ||
//         !Number.isFinite(point.rBZ)
//       ) {
//         return false;
//       }
//     }
//     return true;
//   }
//   
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics3_dcontact_valid(flight::Ref<Physics3DContact> contact) {
  if (!flight::is_safe_integer(contact->body_a) ||
      !flight::is_safe_integer(contact->body_b) ||
      !flight::is_safe_integer(contact->collider_a) || contact->collider_a < 0.0 ||
      !flight::is_safe_integer(contact->collider_b) || contact->collider_b < 0.0 ||
      !flight::is_safe_integer(contact->point_count) || contact->point_count < 0.0 ||
      contact->point_count > static_cast<double>(contact->points.size()) ||
      !std::isfinite(contact->normal_x) || !std::isfinite(contact->normal_y) ||
      !std::isfinite(contact->normal_z) || !std::isfinite(contact->friction) ||
      contact->friction < 0.0 || !std::isfinite(contact->restitution) ||
      contact->restitution < 0.0) {
    return false;
  }
  for (std::ptrdiff_t index = 0;
       index < static_cast<std::ptrdiff_t>(contact->point_count); ++index) {
    const auto& point = contact->points.element(index);
    if (!point || !std::isfinite(point->x) || !std::isfinite(point->y) ||
        !std::isfinite(point->z) || !std::isfinite(point->depth) ||
        !std::isfinite(point->feature_id) || !std::isfinite(point->r_ax) ||
        !std::isfinite(point->r_ay) || !std::isfinite(point->r_az) ||
        !std::isfinite(point->r_bx) || !std::isfinite(point->r_by) ||
        !std::isfinite(point->r_bz)) {
      return false;
    }
  }
  return true;
}

inline bool is_physics3_dcontact_state_valid(flight::Ref<Physics3DWorld> world) {
  {
    double contact_index = 0.0;
    while ((contact_index < static_cast<double>(world->contacts.size()))) {
      {
        if (!is_physics3_dcontact_valid(world->contacts.element(contact_index))) {
          return false;
        }
      }
      (contact_index += 1.0);
    }
  }
  return true;
}

inline bool is_physics3_dgravity_valid(flight::Ref<Physics3DWorld> world) {
  return ((std::isfinite(world->gravity_x) && std::isfinite(world->gravity_y)) && std::isfinite(world->gravity_z));
}

inline bool is_physics3_dposition_iterations_valid(flight::Ref<Physics3DSolverConfig> config) {
  const double iterations = config->sequential_impulse->position_iterations;
  return (flight::is_safe_integer(iterations) && (iterations >= 0.0));
}


// NOT GENERATED: function isPhysics3DSolverConfigValid -- source line 134
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   export function isPhysics3DSolverConfigValid(config: Readonly<Physics3DSolverConfig>): boolean {
//     const sequential = config.sequentialImpulse;
//     return (
//       typeof config.allowSleeping === 'boolean' &&
//       Number.isFinite(config.sleepLinearThreshold) &&
//       config.sleepLinearThreshold >= 0 &&
//       Number.isFinite(config.sleepAngularThreshold) &&
//       config.sleepAngularThreshold >= 0 &&
//       Number.isFinite(config.timeToSleep) &&
//       config.timeToSleep >= 0 &&
//       typeof config.continuousCollision === 'boolean' &&
//       Number.isSafeInteger(config.maxCcdSubsteps) &&
//       config.maxCcdSubsteps >= 0 &&
//       Number.isSafeInteger(config.maxCcdRotationSubsteps) &&
//       config.maxCcdRotationSubsteps >= 0 &&
//       Number.isFinite(sequential.penetrationSlop) &&
//       sequential.penetrationSlop >= 0 &&
//       Number.isFinite(sequential.positionCorrection) &&
//       sequential.positionCorrection >= 0 &&
//       sequential.positionCorrection <= 1 &&
//       Number.isFinite(sequential.restitutionThreshold) &&
//       sequential.restitutionThreshold >= 0 &&
//       typeof sequential.warmStarting === 'boolean'
//     );
//   }
//   
//   // At least one, because `substeps` divides the timestep and the step runs the loop that many times. Zero
//   // would advance nothing while reporting a completed step, which is worse than declining to step at all.
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics3_dsolver_config_valid(flight::Ref<Physics3DSolverConfig> config) {
  const auto& sequential = config->sequential_impulse;
  return sequential &&
      std::isfinite(config->sleep_linear_threshold) && config->sleep_linear_threshold >= 0.0 &&
      std::isfinite(config->sleep_angular_threshold) && config->sleep_angular_threshold >= 0.0 &&
      std::isfinite(config->time_to_sleep) && config->time_to_sleep >= 0.0 &&
      flight::is_safe_integer(config->max_ccd_substeps) && config->max_ccd_substeps >= 0.0 &&
      flight::is_safe_integer(config->max_ccd_rotation_substeps) && config->max_ccd_rotation_substeps >= 0.0 &&
      std::isfinite(sequential->penetration_slop) && sequential->penetration_slop >= 0.0 &&
      std::isfinite(sequential->position_correction) && sequential->position_correction >= 0.0 &&
      sequential->position_correction <= 1.0 &&
      std::isfinite(sequential->restitution_threshold) && sequential->restitution_threshold >= 0.0;
}

inline bool is_physics3_dsubsteps_valid(flight::Ref<Physics3DSolverConfig> config) {
  return (flight::is_safe_integer(config->substeps) && (config->substeps >= 1.0));
}

inline bool is_physics3_dtimestep_valid(double dt) {
  return (std::isfinite(dt) && (dt > 0.0));
}

inline bool is_physics3_dvelocity_iterations_valid(flight::Ref<Physics3DSolverConfig> config) {
  const double iterations = config->sequential_impulse->velocity_iterations;
  return (flight::is_safe_integer(iterations) && (iterations >= 0.0));
}


// NOT GENERATED: function getPhysics3DColliderShapeValidationStatus -- source line 259
//
// The source it stood for:
//   function getPhysics3DColliderShapeValidationStatus(
//     shape: Readonly<Physics3DCollider['local']>,
//   ): ReturnType<typeof getCollisionShapeValidationStatus3D> {
//     if (shape.kind === 'triangle-mesh') return getCollisionTriangleMeshValidationStatus3D(shape);
//     if (shape.kind === 'heightfield') return getCollisionHeightfieldValidationStatus3D(shape);
//     return getCollisionShapeValidationStatus3D(shape);
//   }
//   
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: union member test
// requires a C++ variant binding


// NOT GENERATED: function isPhysics3DColliderWorldShapeCompatible -- source line 267
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function isPhysics3DColliderWorldShapeCompatible(collider: Readonly<Physics3DCollider>): boolean {
//     return collider.world.kind === (collider.local.kind === 'aabb' ? 'box' : collider.local.kind);
//   }
//   
//   // Every field that has to be a real number for the step to mean anything: the pose, the velocities, the
//   // accumulators, the centre of mass, and all three inertia tensors. The world tensor is derived and is
//   // included anyway — it is what every constraint row multiplies by, so a NaN there reaches both bodies of
//   // every contact and joint within one substep.
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: intersection types
// require C++ multiple-inheritance lowering: no shape for CollisionSphere3D. Declare the object shape the code
// reads rather than intersecting a conjunct that has none


// NOT GENERATED: function isPhysics3DColliderValid -- source line 239
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isPhysics3DColliderValid(collider: Readonly<Physics3DCollider>): boolean {
//     const material = collider.material;
//     const filter = collider.filter;
//     return (
//       getPhysics3DColliderShapeValidationStatus(collider.local) === null &&
//       getPhysics3DColliderShapeValidationStatus(collider.world) === null &&
//       isPhysics3DColliderWorldShapeCompatible(collider) &&
//       Number.isFinite(material.density) &&
//       material.density >= 0 &&
//       Number.isFinite(material.friction) &&
//       material.friction >= 0 &&
//       Number.isFinite(material.restitution) &&
//       material.restitution >= 0 &&
//       Number.isSafeInteger(filter.categoryBits) &&
//       Number.isSafeInteger(filter.maskBits) &&
//       Number.isSafeInteger(filter.groupIndex) &&
//       typeof collider.sensor === 'boolean'
//     );
//   }
//   
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics3_dcollider_state_valid(flight::Ref<Physics3DWorld> world) {
  {
    double body_index = 0.0;
    while ((body_index < static_cast<double>(world->bodies.size()))) {
      {
        flight::Ref<RigidBody3D> body = world->bodies.element(body_index);
        if (!flight::is_array(body->colliders)) {
          return false;
        }
        {
          double collider_index = 0.0;
          while ((collider_index < static_cast<double>(body->colliders.size()))) {
            {
              if (!is_physics3_dcollider_valid(body->colliders.element(collider_index))) {
                return false;
              }
            }
            (collider_index += 1.0);
          }
        }
      }
      (body_index += 1.0);
    }
  }
  return true;
}

inline flight::Array<flight::String> rigid_body3_dfinite_keys = flight::Array<flight::String>{flight::String("x"), flight::String("y"), flight::String("z"), flight::String("orientationX"), flight::String("orientationY"), flight::String("orientationZ"), flight::String("orientationW"), flight::String("velocityX"), flight::String("velocityY"), flight::String("velocityZ"), flight::String("angularVelocityX"), flight::String("angularVelocityY"), flight::String("angularVelocityZ"), flight::String("forceX"), flight::String("forceY"), flight::String("forceZ"), flight::String("torqueX"), flight::String("torqueY"), flight::String("torqueZ"), flight::String("centerX"), flight::String("centerY"), flight::String("centerZ"), flight::String("inertiaXX"), flight::String("inertiaYY"), flight::String("inertiaZZ"), flight::String("inertiaXY"), flight::String("inertiaXZ"), flight::String("inertiaYZ"), flight::String("inverseInertiaXX"), flight::String("inverseInertiaYY"), flight::String("inverseInertiaZZ"), flight::String("inverseInertiaXY"), flight::String("inverseInertiaXZ"), flight::String("inverseInertiaYZ"), flight::String("inverseInertiaWorldXX"), flight::String("inverseInertiaWorldYY"), flight::String("inverseInertiaWorldZZ"), flight::String("inverseInertiaWorldXY"), flight::String("inverseInertiaWorldXZ"), flight::String("inverseInertiaWorldYZ")};

inline flight::Set<flight::String> unbounded_joint_fields = flight::Set<flight::String>(flight::Array<flight::String>{flight::String("breakForce"), flight::String("breakTorque"), flight::String("maxLength")});


// NOT GENERATED: function isPhysics3DJointValid -- source line 175
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isPhysics3DJointValid(joint: Readonly<Physics3DJoint>): boolean {
//     if (
//       typeof joint.kind !== 'string' ||
//       joint.kind.length === 0 ||
//       !Number.isSafeInteger(joint.bodyA) ||
//       !Number.isSafeInteger(joint.bodyB) ||
//       typeof joint.collideConnected !== 'boolean'
//     ) {
//       return false;
//     }
//     // Every numeric field, whatever the kind added — a limit, a motor speed, a frame component. Walking the
//     // object rather than a fixed key list is what makes this cover a user's own joint kind, which is the
//     // point of an open registry.
//     //
//     // Except the fields where INFINITY IS THE VALUE, not a symptom. A `breakForce` of infinity is a joint
//     // that never breaks and a `maxLength` of infinity is a rope with no far stop, and both are the natural
//     // defaults — so a blanket finiteness walk declares every ordinary joint invalid and the world declines
//     // to step at all. That failure is silent by design (an invalid step is skipped, not thrown), so it
//     // presents as a motor that does not turn and contacts that never fire, with nothing pointing at the
//     // joint. Adding a field whose unset state is "no bound" means adding it here too.
//     for (const key in joint) {
//       if (UNBOUNDED_JOINT_FIELDS.has(key)) continue;
//       const value = joint[key as keyof typeof joint];
//       if (typeof value === 'number' && !Number.isFinite(value)) return false;
//     }
//     return true;
//   }
//   
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics3_djoint_state_valid(flight::Ref<Physics3DWorld> world) {
  {
    double joint_index = 0.0;
    while ((joint_index < static_cast<double>(world->joints.size()))) {
      {
        if (!is_physics3_djoint_valid(world->joints.element(joint_index))) {
          return false;
        }
      }
      (joint_index += 1.0);
    }
  }
  return true;
}

inline const double physics3_d_quaternion_length_tolerance = 0.000001;


// NOT GENERATED: function isRigidBody3DStateValid -- source line 203
// refusal: cpp-typeof-runtime-domain-unrepresented [source-portability]
//
// The source it stood for:
//   function isRigidBody3DStateValid(body: Readonly<RigidBody3D>): boolean {
//     const orientationLengthSquared =
//       body.orientationX * body.orientationX +
//       body.orientationY * body.orientationY +
//       body.orientationZ * body.orientationZ +
//       body.orientationW * body.orientationW;
//     if (
//       !Number.isSafeInteger(body.index) ||
//       body.index < 0 ||
//       (body.type !== 'dynamic' && body.type !== 'kinematic' && body.type !== 'static') ||
//       typeof body.fixedRotation !== 'boolean' ||
//       typeof body.bullet !== 'boolean' ||
//       typeof body.sleeping !== 'boolean' ||
//       typeof body.sleepEnabled !== 'boolean' ||
//       !Number.isFinite(body.sleepTimer) ||
//       body.sleepTimer < 0 ||
//       !Number.isFinite(body.linearDamping) ||
//       body.linearDamping < 0 ||
//       !Number.isFinite(body.angularDamping) ||
//       body.angularDamping < 0 ||
//       !Number.isFinite(body.gravityScale) ||
//       !Number.isFinite(body.mass) ||
//       body.mass < 0 ||
//       !Number.isFinite(body.inverseMass) ||
//       body.inverseMass < 0 ||
//       !Number.isFinite(orientationLengthSquared) ||
//       Math.abs(orientationLengthSquared - 1) > PHYSICS3D_QUATERNION_LENGTH_TOLERANCE
//     ) {
//       return false;
//     }
//     for (let keyIndex = 0; keyIndex < rigidBody3DFiniteKeys.length; keyIndex += 1) {
//       if (!Number.isFinite(body[rigidBody3DFiniteKeys[keyIndex]])) return false;
//     }
//     return true;
//   }
//   
// cpp emission failed for @flighthq/physics3d/packages/physics3d/src/stepValidation.ts: typeof requires closed
// runtime type evidence: the declared type does not decide it, and the target cannot ask a value it stores as a
// concrete carrier. State the type where the value is read: a closed union whose alternatives are
// distinguishable is lowered as a variant test, and a value the runtime owns -- a parameter declared `unknown`
// or `any` -- is answered by the runtime's own `typeof`

inline bool is_physics3_dbody_state_valid(flight::Ref<Physics3DWorld> world) {
  if ((!flight::is_safe_integer(world->next_body_index) || (world->next_body_index < 0.0))) {
    return false;
  }
  {
    double body_index = 0.0;
    while ((body_index < static_cast<double>(world->bodies.size()))) {
      {
        flight::Ref<RigidBody3D> body = world->bodies.element(body_index);
        if ((((!is_rigid_body3_dstate_valid(body) || !flight::is_array(body->colliders)) || ((body->type != flight::String("static")) && body->colliders.some(is_physics3_dstatic_surface_collider))) || (world->body_by_index.get(body->index) != body))) {
          return false;
        }
      }
      (body_index += 1.0);
    }
  }
  return true;
}

} // namespace flight::physics3d
