// Generated by @flighthq/tool-compiler from @flighthq/command/packages/command/src/command.ts#Command at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function readNodeProperty -- source line 179
#include <flight/any.hpp>
#include <flight/sequence_view.hpp>
#include <flight/structural_ref.hpp>
#include <functional>
#include <optional>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/types/node.hpp>

#include <flight/types/entity.hpp>

#include <flight/types/command.hpp>

#include <flight/entity/entity.hpp>

namespace flight::command {

using flight::types::AddNodeChildCommand;
using flight::types::Command;
using flight::types::CommandPropertyEntry;
using flight::types::CompositeCommand;
using flight::types::EntityConstruction;
using flight::types::NodeAny;
using flight::types::RemoveNodeChildCommand;
using flight::types::ReorderNodeChildCommand;
using flight::types::SetNodePropertyCommand;
using flight::types::add_node_child_command_kind;
using flight::types::composite_command_kind;
using flight::types::remove_node_child_command_kind;
using flight::types::reorder_node_child_command_kind;
using flight::types::set_node_property_command_kind;

using flight::entity::allocate_entity;
using flight::entity::finish_entity;

// OVERRIDE: provided get_node_child_index which the emitter called but did not generate.
// The original TypeScript iterates getNodeRuntime(source).children looking for identity
// match with child, returning the index or -1. This implementation accesses the node's
// entity_runtime_key directly (which holds the NodeRuntime for Node<Any>) and scans its
// children array for a matching shared_ptr identity.
inline double get_node_child_index(flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child) {
  if (!parent || !parent->entity_runtime_key.has_value()) return -1.0;
  const auto& runtime = parent->entity_runtime_key.value();
  if (!runtime || !runtime->children.has_value()) return -1.0;
  const auto& children = runtime->children.value();
  for (double i = 0.0; i < static_cast<double>(children.size()); i += 1.0) {
    // Compare the underlying shared_ptr identity through the structural ref.
    // NodeOf<Any> is a StructuralRef; its shared_owner() gives the underlying shared_ptr.
    const auto& child_ref = children.element(i);
    if (child_ref.shared_owner() == std::static_pointer_cast<void>(child)) return i;
  }
  return -1.0;
}

// OVERRIDE: provided read_node_property which the emitter called but refused to generate.
// The original TypeScript casts the node to Record<string, unknown> and reads a property
// by string key. In C++, Node<Any> is a typed struct without dynamic keyed storage, so
// the erased Record cast the source uses is not representable. This implementation reads
// through the node's structural row owner via named_properties, which gives the same
// dynamic keyed view the TypeScript Record cast provides. Falls back to undefined (the
// JavaScript result for an absent property).
inline flight::Any read_node_property(flight::Ref<NodeAny> target, flight::String property) {
  if (!target) return flight::Any{};
  auto props = flight::named_properties(target);
  if (props) return props.get(property);
  return flight::Any{};
}

inline void initialize_add_node_child_command(flight::Ref<EntityConstruction<flight::Ref<AddNodeChildCommand>>> out, flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child, double index) {
  (out->child = child);
  (out->index = index);
  (out->kind = add_node_child_command_kind);
  (out->label = label);
  (out->parent = parent);
}

inline flight::Ref<AddNodeChildCommand> create_add_node_child_command(flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child, std::optional<double> index = std::nullopt) {
  index = index.value_or(-1.0);
  flight::Ref<EntityConstruction<flight::Ref<AddNodeChildCommand>>> out = allocate_entity<flight::Ref<AddNodeChildCommand>>();
  initialize_add_node_child_command(out, label, parent, child, index.value());
  return finish_entity(out);
}

inline void initialize_composite_command(flight::Ref<EntityConstruction<flight::Ref<CompositeCommand>>> out, flight::String label, flight::Array<flight::Ref<Command>> children) {
  (out->children = ([&]() { flight::Array<flight::Ref<Command>> array_spread_result; for (const auto& array_spread_item : children) { array_spread_result.push(array_spread_item); } return array_spread_result; }()));
  (out->kind = composite_command_kind);
  (out->label = label);
}

inline flight::Ref<CompositeCommand> create_composite_command(flight::String label, flight::Array<flight::Ref<Command>> children) {
  flight::Ref<EntityConstruction<flight::Ref<CompositeCommand>>> out = allocate_entity<flight::Ref<CompositeCommand>>();
  initialize_composite_command(out, label, children);
  return finish_entity(out);
}

inline void initialize_remove_node_child_command(flight::Ref<EntityConstruction<flight::Ref<RemoveNodeChildCommand>>> out, flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child) {
  (out->child = child);
  (out->index = get_node_child_index(parent, child));
  (out->kind = remove_node_child_command_kind);
  (out->label = label);
  (out->parent = parent);
}

inline flight::Ref<RemoveNodeChildCommand> create_remove_node_child_command(flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child) {
  flight::Ref<EntityConstruction<flight::Ref<RemoveNodeChildCommand>>> out = allocate_entity<flight::Ref<RemoveNodeChildCommand>>();
  initialize_remove_node_child_command(out, label, parent, child);
  return finish_entity(out);
}

inline void initialize_reorder_node_child_command(flight::Ref<EntityConstruction<flight::Ref<ReorderNodeChildCommand>>> out, flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child, double to_index) {
  (out->child = child);
  (out->from_index = get_node_child_index(parent, child));
  (out->kind = reorder_node_child_command_kind);
  (out->label = label);
  (out->parent = parent);
  (out->to_index = to_index);
}

inline flight::Ref<ReorderNodeChildCommand> create_reorder_node_child_command(flight::String label, flight::Ref<NodeAny> parent, flight::Ref<NodeAny> child, double to_index) {
  flight::Ref<EntityConstruction<flight::Ref<ReorderNodeChildCommand>>> out = allocate_entity<flight::Ref<ReorderNodeChildCommand>>();
  initialize_reorder_node_child_command(out, label, parent, child, to_index);
  return finish_entity(out);
}


// NOT GENERATED: function readNodeProperty -- source line 179
// refusal: cpp-erased-record-assertion-unrepresented [source-portability]
//
// The source it stood for:
//   function readNodeProperty(target: Readonly<NodeAny>, property: string): unknown {
//     return (target as unknown as Readonly<Record<string, unknown>>)[property];
//   }
//
// cpp emission failed for @flighthq/command/packages/command/src/command.ts: an erased assertion hides the
// represented source carrier flight::Ref<NodeAny> before naming flight::Record<flight::String, flight::Any>, but
// a Flight object reference and Record keyed storage are not representation-equivalent. Keep the exact Record
// carrier from its construction boundary, or keep a finite key union on a typed object and dispatch to its
// declared fields; the compiler will not cast between owners, copy or materialize replacement keyed storage, or
// add side storage

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_COMMAND_PROPERTY_TARGET_VALUE_1FB663985ABECA9C
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_COMMAND_PROPERTY_TARGET_VALUE_1FB663985ABECA9C
struct property_target_value_1fb663985abeca9c : public flight::ReferenceEnabled {
  flight::String property;
  flight::Ref<NodeAny> target;
  flight::Any value;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_COMMAND_PROPERTY_TARGET_VALUE_1FB663985ABECA9C

inline flight::Ref<SetNodePropertyCommand> create_set_node_property_command_batch(flight::String label, flight::SequenceView<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<property_target_value_1fb663985abeca9c>>>>> entries, std::optional<double> merge_window = std::nullopt, std::optional<double> time = std::nullopt) {
  merge_window = merge_window.value_or(0.0);
  time = time.value_or(0.0);
  flight::Array<flight::Ref<CommandPropertyEntry>> captured = entries.map([=](flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<property_target_value_1fb663985abeca9c>>>> entry) {
  return flight::make_ref<CommandPropertyEntry>(CommandPropertyEntry{.after = flight::row_get<flight::RowKey<"value">>(entry), .before = read_node_property(flight::row_get<flight::RowKey<"target">>(entry), flight::row_get<flight::RowKey<"property">>(entry)), .property = flight::row_get<flight::RowKey<"property">>(entry), .target = flight::row_get<flight::RowKey<"target">>(entry)});
});
  flight::Ref<EntityConstruction<flight::Ref<SetNodePropertyCommand>>> out = allocate_entity<flight::Ref<SetNodePropertyCommand>>();
  (out->entries = captured);
  (out->kind = set_node_property_command_kind);
  (out->label = label);
  (out->merge_window = merge_window.value());
  (out->time = time.value());
  return finish_entity(out);
}

inline void initialize_set_node_property_command(flight::Ref<EntityConstruction<flight::Ref<SetNodePropertyCommand>>> out, flight::String label, flight::Ref<NodeAny> target, flight::String property, flight::Any value, double merge_window, double time) {
  (out->entries = flight::Array{flight::make_ref<CommandPropertyEntry>(CommandPropertyEntry{.after = value, .before = read_node_property(target, property), .property = property, .target = target})});
  (out->kind = set_node_property_command_kind);
  (out->label = label);
  (out->merge_window = merge_window);
  (out->time = time);
}

inline flight::Ref<SetNodePropertyCommand> create_set_node_property_command(flight::String label, flight::Ref<NodeAny> target, flight::String property, flight::Any value, std::optional<double> merge_window = std::nullopt, std::optional<double> time = std::nullopt) {
  merge_window = merge_window.value_or(0.0);
  time = time.value_or(0.0);
  flight::Ref<EntityConstruction<flight::Ref<SetNodePropertyCommand>>> out = allocate_entity<flight::Ref<SetNodePropertyCommand>>();
  initialize_set_node_property_command(out, label, target, property, value, merge_window.value(), time.value());
  return finish_entity(out);
}

} // namespace flight::command
