// Generated by @flighthq/tool-compiler from @flighthq/lighting/packages/lighting/src/environment.ts#Environment at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/structural_ref.hpp>
#include <optional>
#include <type_traits>
#include <variant>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct Entity; }
namespace flight::types { struct Environment; }
namespace flight::types { struct EnvironmentOptions; }
namespace flight::types { struct Texture2D; }
namespace flight::types { struct TextureCommon; }

#include <flight/entity/entity.hpp>
#include <flight/types/entity.hpp>
#include <flight/types/environment.hpp>
#include <flight/types/environment_options.hpp>
#include <flight/types/texture.hpp>

namespace flight::lighting {

inline void initialize_environment(flight::types::EntityConstruction<flight::Ref<flight::types::Environment>> out, std::optional<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::EnvironmentOptions>>>>> options = std::nullopt) {
  flight::row_set<flight::RowKey<"enabled">>(out, ([&]() -> bool { auto nullish_coalesce_left = ([&]() -> std::optional<bool> { auto optional_chain_receiver = options; if (!optional_chain_receiver.has_value()) return std::nullopt; return flight::row_get<flight::RowKey<"enabled">>(optional_chain_receiver.value()); }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return true; }()));
  std::optional<flight::types::Texture> environment;
  if (options.has_value()) {
    const auto& candidate = flight::row_get<flight::RowKey<"environment">>(options.value());
    std::visit([&](const auto& value) {
      using Value = std::decay_t<decltype(value)>;
      if constexpr (!std::same_as<Value, flight::Null> && !std::same_as<Value, flight::Undefined>) {
        environment.emplace(std::in_place_type<Value>, value);
      }
    }, candidate);
  }
  flight::row_set<flight::RowKey<"environment">>(out, environment);
  flight::row_set<flight::RowKey<"intensity">>(out, ([&]() -> double { auto nullish_coalesce_left = ([&]() -> std::optional<double> { auto optional_chain_receiver = options; if (!optional_chain_receiver.has_value()) return std::nullopt; return flight::row_get<flight::RowKey<"intensity">>(optional_chain_receiver.value()); }()); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return 1.0; }()));
  flight::row_set<flight::RowKey<"kind">>(out, flight::types::environment_kind);
}

inline flight::Ref<flight::types::Environment> create_environment(std::optional<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::EnvironmentOptions>>>>> options = std::nullopt) {
  flight::types::EntityConstruction<flight::Ref<flight::types::Environment>> out = flight::entity::allocate_entity<flight::Ref<flight::types::Environment>>();
  initialize_environment(out, options);
  return flight::entity::finish_entity<flight::Ref<flight::types::Environment>>(out);
}

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_95B8B467441EC19B
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_95B8B467441EC19B
struct entity_runtime_key_flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_dimension_sources_95b8b467441ec19b : public flight::ReferenceEnabled {
  std::optional<flight::Ref<flight::types::EntityRuntime>> entity_runtime_key;
  bool flip_x;
  bool flip_y;
  flight::Ref<flight::types::Vector2> uv_offset;
  double uv_rotation;
  flight::Ref<flight::types::Vector2> uv_scale;
  flight::types::TextureColorSpace color_space;
  flight::Ref<flight::types::Sampler> sampler;
  double version;
  flight::String dimension;
  flight::Array<std::optional<flight::Ref<flight::types::TextureSource>>> sources;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_95B8B467441EC19B

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCE_B54DC1BFFA369663
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCE_B54DC1BFFA369663
struct entity_runtime_key_flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_dimension_source_b54dc1bffa369663 : public flight::ReferenceEnabled {
  std::optional<flight::Ref<flight::types::EntityRuntime>> entity_runtime_key;
  bool flip_x;
  bool flip_y;
  flight::Ref<flight::types::Vector2> uv_offset;
  double uv_rotation;
  flight::Ref<flight::types::Vector2> uv_scale;
  flight::types::TextureColorSpace color_space;
  flight::Ref<flight::types::Sampler> sampler;
  double version;
  flight::String dimension;
  std::optional<flight::Ref<flight::types::VoxelGrid>> source;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCE_B54DC1BFFA369663

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_AE19201647327EBA
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_AE19201647327EBA
struct entity_runtime_key_flip_x_flip_y_uv_offset_uv_rotation_uv_scale_color_space_sampler_version_dimension_sources_ae19201647327eba : public flight::ReferenceEnabled {
  std::optional<flight::Ref<flight::types::EntityRuntime>> entity_runtime_key;
  bool flip_x;
  bool flip_y;
  flight::Ref<flight::types::Vector2> uv_offset;
  double uv_rotation;
  flight::Ref<flight::types::Vector2> uv_scale;
  flight::types::TextureColorSpace color_space;
  flight::Ref<flight::types::Sampler> sampler;
  double version;
  flight::String dimension;
  flight::types::TextureSourceCubeFaces sources;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_LIGHTING_ENTITY_RUNTIME_KEY_FLIP_X_FLIP_Y_UV_OFFSET_UV_ROTATION_UV_SCALE_COLOR_SPACE_SAMPLER_VERSION_DIMENSION_SOURCES_AE19201647327EBA

inline flight::Ref<flight::types::Environment> clone_environment(flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::Environment>>>> source) {
  auto out = flight::entity::allocate_entity<flight::Ref<flight::types::Environment>>();
  flight::row_set<flight::RowKey<"enabled">>(out, flight::row_get<flight::RowKey<"enabled">>(source));
  flight::row_set<flight::RowKey<"environment">>(out, flight::row_get<flight::RowKey<"environment">>(source));
  flight::row_set<flight::RowKey<"intensity">>(out, flight::row_get<flight::RowKey<"intensity">>(source));
  flight::row_set<flight::RowKey<"kind">>(out, flight::types::environment_kind);
  return flight::entity::finish_entity<flight::Ref<flight::types::Environment>>(out);
}

} // namespace flight::lighting
