// Generated by @flighthq/tool-compiler from @flighthq/render/packages/render/src/renderAppearance.ts#RenderAppearance at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function recalculateAppearance -- source line 19
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/node/revision.hpp>

#include <flight/types/render_state.hpp>

#include <flight/types/render_proxy.hpp>

#include <flight/types/node.hpp>

#include <flight/render/render_state.hpp>

namespace flight::render {

using flight::node::get_node_appearance_revision;

using flight::types::Node;
using flight::types::RenderProxy;
using flight::types::RenderState;


// NOT GENERATED: function recalculateAppearance -- source line 19
// refusal: cpp-intersection-member-shapeless [source-portability]
//
// The source it stood for:
//   function recalculateAppearance(state: RenderState, data: RenderProxy, parentData?: RenderProxy) {
//     const source = data.source as unknown as HasAppearance & HasBlendMode;
//     if (parentData !== undefined) {
//       data.visible = source.visible && parentData.visible;
//       if (!data.visible) return;
//       data.alpha = source.alpha * parentData.alpha;
//       if (data.alpha <= 0) return;
//       data.blendMode = source.blendMode;
//     } else {
//       data.visible = source.visible;
//       if (!data.visible) return;
//       data.alpha = source.alpha * state.renderAlpha;
//       if (data.alpha <= 0) return;
//       data.blendMode = state.renderBlendMode !== null ? state.renderBlendMode : source.blendMode;
//     }
//     data.appearanceFrameId = getRenderStateRuntime(state).currentFrameId;
//   }
//   
// cpp emission failed for @flighthq/render/packages/render/src/renderAppearance.ts: intersection types require
// C++ multiple-inheritance lowering: no shape for HasAppearance, HasBlendMode. Declare the object shape the code
// reads rather than intersecting a conjunct that has none

inline bool update_render_proxy_appearance(flight::Ref<RenderState> state, flight::Ref<RenderProxy> data, std::optional<flight::Ref<RenderProxy>> parent_data = std::nullopt) {
  (void)state;
  (void)data;
  (void)parent_data;
  throw std::logic_error("Render appearance requires the unavailable checked HasAppearance and HasBlendMode owner");
}

} // namespace flight::render
