// Generated by @flighthq/tool-compiler from @flighthq/render/packages/render/src/renderViewport.ts#RenderViewport at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused declarations in this module. Everything else compiled, and each
// omission is marked NOT GENERATED below with the reason. This file is NOT complete.
//   missing: function isSpatial2DNode -- source line 74
#include <flight/any.hpp>
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

#include <flight/geometry/rectangle.hpp>

#include <flight/geometry/matrix.hpp>

#include <flight/node/bounds_rectangle_access.hpp>

#include <flight/types/viewport.hpp>

#include <flight/types/render_proxy2_d.hpp>

#include <flight/types/rectangle.hpp>

#include <flight/types/matrix.hpp>

namespace flight::render {

using flight::geometry::create_rectangle;
using flight::geometry::matrix_transform_rectangle;

using flight::types::Matrix;
using flight::types::Rectangle;
using flight::types::RenderProxy2D;
using flight::types::Viewport;

inline bool is_spatial2_dnode(flight::Any source) {
  (void)source;
  throw std::logic_error("Spatial 2D detection requires unavailable checked transform and bounds runtime owners");
}


// NOT GENERATED: function isSpatial2DNode -- source line 74
// refusal: cpp-partial-shape-unresolvable [source-portability]
//
// The source it stood for:
//   function isSpatial2DNode(source: unknown): source is Spatial2DNode {
//     if (source === null || typeof source !== 'object') return false;
//     if (!hasEntityRuntime(source as Parameters<typeof hasEntityRuntime>[0])) return false;
//     const runtime = getEntityRuntime(source as Parameters<typeof getEntityRuntime>[0]) as Partial<
//       HasBoundsRectangleRuntime & HasTransform2DRuntime
//     >;
//     return typeof runtime.computeLocalBoundsRectangle === 'function' && 'worldMatrix' in runtime;
//   }
//   
//   // Module-level scratch rectangles used by isRenderableInViewport to avoid allocation on every call.
// cpp emission failed for @flighthq/render/packages/render/src/renderViewport.ts: Partial<T> requires a
// statically resolvable C++ object shape; T is intersection

inline bool compute_render_proxy_world_bounds(flight::Ref<Rectangle> out, flight::Any source) {
  (void)out;
  (void)source;
  throw std::logic_error("World bounds require unavailable checked transform and bounds runtime owners");
}

inline flight::Ref<Rectangle> scratch_bounds = create_rectangle(std::nullopt, std::nullopt, std::nullopt, std::nullopt);

inline flight::Ref<Rectangle> scratch_transformed = create_rectangle(std::nullopt, std::nullopt, std::nullopt, std::nullopt);

inline bool is_renderable_in_viewport(flight::Any source, flight::Ref<Viewport> viewport, std::optional<std::optional<flight::Ref<Matrix>>> render_transform2_d = std::nullopt) {
  (void)source;
  (void)viewport;
  (void)render_transform2_d;
  throw std::logic_error("Viewport culling requires unavailable checked transform and bounds runtime owners");
}

inline bool is_render_proxy_in_viewport(flight::Ref<RenderProxy2D> proxy, flight::Ref<Viewport> viewport, std::optional<std::optional<flight::Ref<Matrix>>> render_transform2_d = std::nullopt) {
  (void)proxy;
  (void)viewport;
  (void)render_transform2_d;
  throw std::logic_error("Viewport culling requires unavailable checked transform and bounds runtime owners");
}

} // namespace flight::render
