// Generated by @flighthq/tool-compiler from @flighthq/render/packages/render/src/renderRegistryGuards.ts#RenderRegistryGuards at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once
#include <flight/any.hpp>
#include <flight/record.hpp>
#include <flight/structural_ref.hpp>
#include <flight/weak_map.hpp>
#include <functional>
#include <optional>
#include <stdexcept>
#include <flight/runtime.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2", "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::types { struct RenderRegistriesMiss; }
namespace flight::types { struct RenderRegistriesMissExplanation; }
namespace flight::types { struct RenderRegistrySignals; }
namespace flight::types { struct RenderState; }
namespace flight::types { template <typename T> struct Signal; }

#include <flight/log/log.hpp>
#include <flight/signals/slot.hpp>
#include <flight/types/entity.hpp>
#include <flight/types/log.hpp>
#include <flight/types/render_registry_signals.hpp>
#include <flight/types/render_state.hpp>
#include <flight/types/signal.hpp>
#include <flight/render/render_registry_signals.hpp>

namespace flight::render {

using flight::types::RenderRegistrySignals;
using flight::types::RenderState;

inline bool has_render_backend_capability(flight::Ref<flight::types::RenderState> state, const char* capability) {
  (void)state;
  (void)capability;
  throw std::logic_error("Render registry diagnostics require an unavailable checked backend-state owner");
}

inline flight::String get_render_registries_miss_message(flight::Ref<flight::types::RenderState> state, flight::types::RenderRegistryTable registry) {
  {
    auto switch_value = registry;
    if (switch_value == flight::types::RenderRegistryTable::BlendRealization) {
      return flight::String("a blend mode this scene uses has no registered GL realization, so the node composites as Normal instead — call registerGlBlendMode(state, blendMode, realization)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::EffectPaddingResolver) {
      return flight::String("computeRenderEffectPadding: effect kind has no registered padding resolver — call registerRenderEffectPaddingResolver(state, kind, resolver)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::MaterialTextureLister) {
      return flight::String("a material kind in this scene has no registered texture lister, so an all-unlisted mesh gets no fade, while a mixed mesh can reveal before that material's textures settle and show a later texture pop-in — call registerScene3DMaterialTextures(registry, kind, lister), or the named door for that family");
    }
    else if (switch_value == flight::types::RenderRegistryTable::MaterialRenderer) {
      if (has_render_backend_capability(state, "device")) {
        return flight::String("resolveWgpuMaterialRenderer: material kind has no registered renderer, so nodes using it do not draw — call registerWgpuMaterialRenderer(state, kind, renderer)");
      }
      return flight::String("resolveGlMaterialRenderer: material kind has no registered renderer, so nodes using it do not draw — call registerGlMaterialRenderer(state, kind, renderer)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::ModifierSnippet) {
      if (has_render_backend_capability(state, "device")) {
        return flight::String("a modifier on this material has no registered shader snippet — call registerWgpuModifierSnippet(state, snippet), or registerBuiltInWgpuModifierSnippets(state)");
      }
      return flight::String("a modifier on this material has no registered shader snippet — call registerGlModifierSnippet(state, snippet), or registerBuiltInGlModifierSnippets(state)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::NodeRenderer) {
      return flight::String("createRenderProxy: node kind has no registered renderer — call registerRenderer(state, kind, renderer)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::ShapeCommandHandler) {
      return flight::String("renderCanvasShapeCommands: shape command key has no registered handler on this state — call registerCanvasShapeCommand(state, command)");
    }
    else if (switch_value == flight::types::RenderRegistryTable::ShapeRasterizer) {
      if (has_render_backend_capability(state, "device")) {
        return flight::String("drawWgpuShape: a fill this node uses has no tessellated form and no rasterizer is registered, so it does not draw — call registerWgpuShapeRasterizer(state, createCanvasShapeRasterizer(resolvers))");
      }
      if (has_render_backend_capability(state, "element")) {
        return flight::String("drawDomShape: a fill this node uses has no tessellated form and no rasterizer is registered, so it does not draw — call registerDomShapeRasterizer(state, createCanvasShapeRasterizer(resolvers))");
      }
      return flight::String("drawGlShape: a fill this node uses has no tessellated form and no rasterizer is registered, so it does not draw — call registerGlShapeRasterizer(state, createCanvasShapeRasterizer(resolvers))");
    }
    else if (switch_value == flight::types::RenderRegistryTable::TextureResolver) {
      if (has_render_backend_capability(state, "gl")) {
        return flight::String("resolveGlTexture: texture source kind has no registered resolver — rebuild the GlRenderRegistries with the required resolver and create the render state from that registry");
      }
      if (has_render_backend_capability(state, "device")) {
        return flight::String("resolveWgpuTexture: texture source kind has no registered resolver — call registerWgpuTextureResolver(state, sourceKind, resolver)");
      }
      if (has_render_backend_capability(state, "element")) {
        return flight::String("resolveDomTexture: texture source kind has no registered resolver — call registerDomTextureResolver(state, sourceKind, resolver)");
      }
      return flight::String("resolveCanvasTexture: texture source kind has no registered resolver — call registerCanvasTextureResolver(resolvers, sourceKind, resolver) on the set the caller resolves through");
    }
  }
  throw std::logic_error("Flight function completed without a value");
}

inline flight::WeakMap<flight::Ref<flight::types::RenderState>, double> state_ids = flight::WeakMap<flight::Ref<flight::types::RenderState>, double>();

inline bool are_render_registries_guards_enabled(flight::Ref<flight::types::RenderState> state) {
  return state_ids.has(state);
}

inline flight::WeakMap<flight::Ref<flight::types::RenderState>, flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>>> state_misses = flight::WeakMap<flight::Ref<flight::types::RenderState>, flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>>>();

#ifndef FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_RENDER_KIND_REGISTRY_457C78DE81B0A12A
#define FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_RENDER_KIND_REGISTRY_457C78DE81B0A12A
struct kind_registry_457c78de81b0a12a : public flight::ReferenceEnabled {
  flight::String kind;
  flight::types::RenderRegistryTable registry;
};
#endif // FLIGHT_COMPILER_ANONYMOUS__FLIGHTHQ_RENDER_KIND_REGISTRY_457C78DE81B0A12A

inline flight::Ref<flight::types::RenderRegistriesMissExplanation> explain_render_registries_misses(flight::Ref<flight::types::RenderState> state) {
  flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>> misses = ([&]() -> flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>> { auto nullish_coalesce_left = state_misses.get(state); if (nullish_coalesce_left.has_value()) return nullish_coalesce_left.value(); return flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>>{}; }());
  return flight::make_ref<flight::types::RenderRegistriesMissExplanation>(flight::types::RenderRegistriesMissExplanation{.misses = misses.map([=](flight::Ref<flight::types::RenderRegistriesMiss> miss) { return flight::structural_ref_cast<flight::StructuralRef<flight::RowReadonly<flight::RowOf<flight::Ref<flight::types::RenderRegistriesMiss>>>>>(flight::StructuralRef<flight::RowWritable<flight::RowOf<flight::Ref<kind_registry_457c78de81b0a12a>>>>(flight::make_ref<kind_registry_457c78de81b0a12a>(kind_registry_457c78de81b0a12a{.kind = miss->kind, .registry = miss->registry}))); }), .status = ((static_cast<double>(misses.size()) == 0.0) ? flight::String("complete") : flight::String("misses-recorded"))});
}

inline void record_render_registries_miss(flight::Ref<flight::types::RenderState> state, double state_id, flight::types::RenderRegistryTable registry, flight::String kind) {
  std::optional<flight::Array<flight::Ref<flight::types::RenderRegistriesMiss>>> misses = state_misses.get(state);
  if ((!misses.has_value() || misses.value().some([=](flight::Ref<flight::types::RenderRegistriesMiss> miss) { return ((miss->registry == registry) && (miss->kind == kind)); }))) {
    return;
  }
  misses.value().push(flight::make_ref<flight::types::RenderRegistriesMiss>(flight::types::RenderRegistriesMiss{.kind = kind, .registry = registry}));
  const double registry_value = static_cast<double>(registry);
  flight::log::log_once(flight::String("render:registry-miss:") + flight::to_string(state_id) + flight::String(":") + flight::to_string(registry_value) + flight::String(":") + kind, flight::types::LogLevel::Warn, flight::types::LogData{flight::Record<flight::String, flight::Any>{{flight::String("kind"), flight::Any(kind)}, {flight::String("message"), flight::Any(get_render_registries_miss_message(state, registry))}, {flight::String("registry"), flight::Any(registry_value)}}}, std::optional<flight::String>{flight::String("render")});
}

inline double next_state_id = 0.0;

inline void enable_render_registries_guards(flight::Ref<flight::types::RenderState> state) {
  (void)state;
  throw std::logic_error("Render registry guards require an unavailable typed signal-slot carrier");
}

} // namespace flight::render
