// Generated by @flighthq/tool-compiler from @flighthq/texture-formats/packages/texture-formats/src/parseAtf.ts#ParseAtf at 7e2fc7df5378313ceaf21ba8d6ef39cc18a6f4ad. Do not edit.
#pragma once

// PARTIAL: the C++ emitter refused parseAtfInternal after losing the presence proof for a nested
// array element. This override supplies that one function and retains the emitted module surface.

#include <optional>
#include <utility>

#include <flight/runtime.hpp>
#include <flight/types/texture_container.hpp>
#include <flight/types/texture_container_format.hpp>
#include <flight/types/texture_container_level.hpp>
#include <flight/types/texture_container_parse_failure_reason.hpp>
#include <flight/types/texture_container_supercompression.hpp>
#include <flight/texture_formats/byte_reader.hpp>

static_assert(flight::runtime_contract.compiler_contract == "flight-runtime-contract/2",
              "Flight compiler/runtime contract mismatch");
static_assert(flight::runtime_contract.cpp_abi == 1, "Flight C++ runtime ABI mismatch");

namespace flight::texture_formats {

using flight::types::TextureContainer;
using flight::types::TextureContainerFormat;
using flight::types::TextureContainerLevel;
using flight::types::TextureContainerParseFailureReason;

struct ParseFailure : public flight::ReferenceEnabled {
  std::optional<TextureContainerParseFailureReason> reason;
};

inline flight::Null reject(
    std::optional<flight::Ref<ParseFailure>> failure,
    TextureContainerParseFailureReason reason) {
  if (failure.has_value()) failure.value()->reason = std::move(reason);
  return flight::null;
}

inline bool has_atf_signature(flight::Uint8Array bytes) {
  return static_cast<double>(bytes.byte_length) >= 3.0 && bytes.get_index(0.0) == 65.0 &&
         bytes.get_index(1.0) == 84.0 && bytes.get_index(2.0) == 70.0;
}

inline const double atf_cube_flag = 128.0;
inline const double atf_format_code_mask = 127.0;
inline const double atf_legacy_header_offset = 6.0;
inline const double atf_new_header_offset = 12.0;
inline const double atf_new_version_marker = 255.0;
inline const double atf_max_log2_dimension = 13.0;
inline const double atf_etc2_version = 3.0;
inline const double atf_base_slot_count = 3.0;

inline flight::Set<double> atf_opaque_format_codes =
    flight::Set<double>(flight::Array<double>{2.0, 3.0, 12.0});
inline flight::Set<double> atf_alpha_format_codes =
    flight::Set<double>(flight::Array<double>{4.0, 5.0, 13.0});

inline flight::Array<flight::Ref<TextureContainerFormat>> atf_opaque_slot_formats =
    flight::Array<flight::Ref<TextureContainerFormat>>{
        flight::String("bc1"), flight::String("etc1"), flight::String("pvrtc4bppRgb"),
        flight::String("etc2Rgb")};
inline flight::Array<flight::Ref<TextureContainerFormat>> atf_alpha_slot_formats =
    flight::Array<flight::Ref<TextureContainerFormat>>{
        flight::String("bc3"), flight::String("etc1"), flight::String("pvrtc4bppRgba"),
        flight::String("etc2Rgba")};

// OVERRIDE: faithful transcription of the one refused function. The key representation choice is
// explicit: per_slot_levels is an Array of Array handles, and element(slot) proves the requested
// inner array is present before push. No optional storage is unpacked without a presence test.
inline std::optional<flight::Array<flight::Ref<TextureContainer>>> parse_atf_internal(
    flight::Uint8Array bytes,
    std::optional<flight::Ref<ParseFailure>> failure = std::nullopt) {
  using Result = std::optional<flight::Array<flight::Ref<TextureContainer>>>;
  const auto fail = [&](TextureContainerParseFailureReason reason) -> Result {
    static_cast<void>(reject(failure, std::move(reason)));
    return std::nullopt;
  };

  if (!has_atf_signature(bytes)) return fail(flight::String("container-unrecognized"));

  const bool versioned = bytes.get_index(6.0) == atf_new_version_marker;
  const double header_offset = versioned ? atf_new_header_offset : atf_legacy_header_offset;
  if (static_cast<double>(bytes.byte_length) < header_offset + 4.0) {
    return fail(flight::String("header-truncated"));
  }

  const double version = versioned ? bytes.get_index(7.0) : 0.0;
  auto length_reader = create_byte_reader(bytes, versioned ? 8.0 : 3.0);
  const double payload_length = versioned
                                    ? read_byte_reader_u32_big_endian(length_reader)
                                    : read_byte_reader_u24_big_endian(length_reader);
  if (header_offset + payload_length > static_cast<double>(bytes.byte_length)) {
    return fail(flight::String("level-range-out-of-bounds"));
  }

  const double type_format_byte = bytes.get_index(header_offset);
  const double log2_width = bytes.get_index(header_offset + 1.0);
  const double log2_height = bytes.get_index(header_offset + 2.0);
  const double mip_count = bytes.get_index(header_offset + 3.0);

  const double format_code = flight::bitwise_and(type_format_byte, atf_format_code_mask);
  const bool alpha = atf_alpha_format_codes.has(format_code);
  if (!alpha && !atf_opaque_format_codes.has(format_code)) {
    return fail(flight::String("format-unsupported"));
  }
  if (log2_width > atf_max_log2_dimension || log2_height > atf_max_log2_dimension ||
      mip_count < 1.0) {
    return fail(flight::String("structure-invalid"));
  }

  const bool cube = flight::bitwise_and(type_format_byte, atf_cube_flag) != 0.0;
  const double faces = cube ? 6.0 : 1.0;
  const double width = flight::left_shift(1.0, log2_width);
  const double height = flight::left_shift(1.0, log2_height);
  const auto slot_formats = alpha ? atf_alpha_slot_formats : atf_opaque_slot_formats;
  const double slot_count =
      version < atf_etc2_version ? atf_base_slot_count : atf_base_slot_count + 1.0;

  flight::Array<flight::Array<flight::Ref<TextureContainerLevel>>> per_slot_levels;
  for (double slot = 0.0; slot < slot_count; slot += 1.0) {
    per_slot_levels.push(flight::Array<flight::Ref<TextureContainerLevel>>{});
  }

  auto reader = create_byte_reader(bytes, header_offset + 4.0);
  const double length_width = version == 0.0 ? 3.0 : 4.0;
  for (double side = 0.0; side < faces; side += 1.0) {
    for (double level = 0.0; level < mip_count; level += 1.0) {
      for (double slot = 0.0; slot < slot_count; slot += 1.0) {
        if (!has_byte_reader_bytes(reader, length_width)) {
          return fail(flight::String("level-range-out-of-bounds"));
        }
        const double block_length = version == 0.0
                                        ? read_byte_reader_u24_big_endian(reader)
                                        : read_byte_reader_u32_big_endian(reader);
        if (!has_byte_reader_bytes(reader, block_length)) {
          return fail(flight::String("level-range-out-of-bounds"));
        }
        if (block_length == 0.0) continue;
        const double byte_offset = reader->offset;
        reader->offset += block_length;
        per_slot_levels.element(slot).push(
            flight::make_ref<TextureContainerLevel>(TextureContainerLevel{
                .byte_offset = byte_offset,
                .byte_length = block_length,
                .width = flight::maximum(1.0, flight::signed_right_shift(width, level)),
                .height = flight::maximum(1.0, flight::signed_right_shift(height, level)),
            }));
      }
    }
  }

  flight::Array<flight::Ref<TextureContainer>> containers;
  for (double slot = 0.0; slot < slot_count; slot += 1.0) {
    const auto levels = per_slot_levels.element(slot);
    if (levels.empty()) continue;
    containers.push(flight::make_ref<TextureContainer>(TextureContainer{
        .format = slot_formats.element(slot),
        .width = width,
        .height = height,
        .depth = 1.0,
        .mip_levels = static_cast<double>(levels.size()) / faces,
        .layers = 1.0,
        .faces = faces,
        .supercompression = flight::String("None"),
        .levels = levels,
    }));
  }
  if (containers.empty()) return fail(flight::String("structure-invalid"));
  return containers;
}

inline std::optional<TextureContainerParseFailureReason> get_atf_parse_failure_reason(
    flight::Uint8Array bytes) {
  auto failure = flight::make_ref<ParseFailure>(ParseFailure{.reason = std::nullopt});
  const auto containers = parse_atf_internal(bytes, failure);
  return containers.has_value() ? std::nullopt : failure->reason;
}

inline std::optional<flight::Array<flight::Ref<TextureContainer>>> parse_atf(
    flight::Uint8Array bytes) {
  return parse_atf_internal(bytes, std::nullopt);
}

} // namespace flight::texture_formats
